### PR TITLE
Added 10 courses on Android

### PR DESCRIPTION
**Pull request by contributor13**
## What does this PR do?
Adds courses available on Udacity. Already 5 free Android courses on Udacity were previously added but these 10 more were missing. These include newly added courses as well.

### Description 
Udacity is an authentic website which provides good courses.
### Why is this valuable?
Added courses will give a more useful and complete list of free Android courses available on Udacity.
### How do we know it's really free?
When go to the respective links then it is mentioned that "Free Course" and from there can select "Start Free Course" and then Sign Up/Login on Udacity to avail that course.
### For course lists, is it a course?
Yes
## Checklist:
- [x] Read our [contributing guidelines](/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists  in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
Please follow our style:

Instead of:
`* [Udacity Build Native Mobile Apps with Flutter](https://www.udacity.com/course/build-native-mobile-apps-with-flutter--ud905)`
Do:
`* [Build Native Mobile Apps with Flutter](https://www.udacity.com/course/build-native-mobile-apps-with-flutter--ud905) - (Udacity)`

**Comment by contributor13** [comment]
Should I do it for all Udacity courses?

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by contributor13** [comment]
Thank you

**Pull request merged**
