### PR TITLE
Add some hebrew podcasts

### PR DESCRIPTION
**Pull request by yehiel9523**

### CODE REVIEW

**Comment by yehiel9523** [comment]
Fixed the check problem

**Comment by eshellman** [comment]
should we add `(podcast)` annotations?

**Comment by yehiel9523** [comment]
I'm sorry i don't really understund what do you mean to add annotaions ?

**Comment by yehiel9523** [comment]
Ok i understend , they're all podcasts so do i need to add (podcast) on them?

**Comment by eshellman** [comment]
yes, or the translation

**Comment by yehiel9523** [comment]
Ok Thanks

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
