### PR TITLE
Add F# Functional Programming Textbook

### PR DESCRIPTION
**Pull request by cynic**
## What does this PR do?
Add Resource(s)

### Description 
Functional programming textbook that focuses on teaching functional concepts through F#.

### Why is this valuable (or not)
Relatively concise reference material, suitable for self-study, with plenty of exercises (including answer key) and tutorials.

### How do we know it's really free?
I'm the author.  It's free.

### For book lists, is it a book?
Yes.

### Checklist:
- [X] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [X] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
This is an excellent contribution! I think folks not familiar with overleaf might be confused when they land in a tex authoring environment. I'm also not sure if overleaf is set up to be reader-facing in this way. For example, the reader has an active recompile button. We don't have any other overleaf links in the repo. The direct download link seems to be https://www.overleaf.com/download/project/5bf2cb3cd9568d5a75bfcba9/build/16ac0dc597e-0bc6b0adec7881db/output/output.pdf?compileGroup=priority&clsiserverid=clsi-reg-jn1c&popupDownload=true

If you intend to add an open license (recommended) consider adding the pdf file to Unglue.it or archive.org (or both). 

Let us know if, after considering feedback, you want this merged as is.

**Comment by cynic** [comment]
Thanks @eshellman.  I agree with you that the environment is not very friendly (and the download-PDF button isn't obvious, either).  The contribution guidelines suggest that we always link to the most up-to-date copy, and this will be it.  The direct-download link that you've posted is a direct-download for a particular build artifact (see the 16ac..81db part of the URL) and I don't know how long that build artifact would be present on the Overleaf servers.  The overleaf link would therefore be preferable.

I'm being verified by the Unglue.it people right now -- this is the first that I'd heard of that service.  Might I suggest that we keep this pending and I'll get back to it in the following week, depending on what they say?

**Comment by eshellman** [comment]
(we ARE the Unglue.it people)

**Comment by cynic** [comment]
Right - all passed, so the link should be https://unglue.it/work/400500/ .  It has what is quite possible the worst cover art in the world, but 🤷‍♀  ... 'tis not really my forte.  With any luck, someone will benefit from it anyway.

**Comment by eshellman** [comment]
Welcome to free-programming-books!

**Pull request merged**
