### PR TITLE
style: change theme

### PR DESCRIPTION
**Pull request by LuigiImVector**
## What does this PR do?
Improve repo

### Description

I changed the theme from minimal to [cayman](https://github.com/pages-themes/cayman), you can see the new page here: https://luigiimvector.github.io/free-programming-books/
The UI wasn't very nice, as said on #5491.

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
not crazy about the cayman theme, esp on desktop.
I would like to push people towards the dynamic site, which uses minimal theme. 
Need feedback from others!

**Comment by CleanMachine1** [comment]
Just giving my opinion, I prefer the cayman style to the current one

**Comment by LuigiImVector** [comment]
What do you think @davorpa ?

**Comment by davorpa** [comment]
> What do you think @davorpa ?

I prefer the current minimal theme because is the most simple and fast. Maybe change it's styles a bit extending jekyll theme due to official github-themes development are frozen since remote-theme gem was appear

**Comment by YuvrajSHAD** [comment]
for better understanding and experience, i think Cayman theme is good.

**Comment by Thenlie** [comment]
I wonder if we could create a discussion poll or something for this? I like both themes and think it is mostly a toss up. So maybe letting the community decide would be a good option.

**Comment by eshellman** [comment]
yes, should be an issue.
we need verification that the theme will also work on free-programming-books-search

**Pull request closed without merging**
