### PR TITLE
Link directly to O'Really PDFs

### PR DESCRIPTION
**Pull request by stephenjfox**
## What does this PR do?
Add Resource(s) | Remove Resource(s)

### Description

I replaced some links for two popular books in the Software Architecture section that are hosted on O'Reilly. O'Reilly has been changing up some of these links, redirecting you to a rather scarce hub that lacks the books that were linked to.

### Why is this valuable (or not)

It restores the books to _accessibility_. Rather than being locked away through obscurity, the users of this repo can just get download the PDF

### How do we know it's really free?
It's publicly hosted on O'Reilly's domain

### For book lists, is it a book?
Yes, replacing two links.

### Checklist:
- [x] Not a duplicate
- [ ] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Good improvement, but the linter wants to see a `(pdf)` notation.

**Comment by stephenjfox** [comment]
I'll make the change

**Comment by eshellman** [comment]
@stephenjfox welcome to free-programming-books!

**Comment by stephenjfox** [comment]
@eshellman Thanks! Glad to contribute 😄

**Pull request merged**
