### PR TITLE
Add new books in Prompt Engineering (changes made)

### PR DESCRIPTION
**Pull request by Futurist-Forever**
## What does this PR do?
Add resources

### Description
* Guide to Prompt Engineering by CodeAhoy
* Prompt Engineering Guide by DAIR.AI

### Why is this valuable (or not)?
Both are excellent resources for beginners interested in learning prompt engineering because they cover practically every part of the topic from beginning to end.

### How do we know it's really free?
They are provided on a publicly accessible platform.

### For book lists, is it a book? For course lists, is it a course? etc.
Both are books.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
seems like the subject is not python?

**Comment by Futurist-Forever** [comment]
Python notebooks are included in Chapters 2, 4, 5, and 6.

**Comment by Futurist-Forever** [comment]
The book has been added to the BY SUBJECT file.

**Comment by eshellman** [comment]
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category. I would put this in the Artificial Intelligence category.
when you've made changes, please add `(changes made)` to the title of your PR

**Comment by eshellman** [comment]
this is ok for now, but I think we'll need a propt engineering category under AI.

**Comment by Futurist-Forever** [comment]
Ok

**Pull request merged**
