### PR TITLE
adding Introduction to Algorithms book

### PR DESCRIPTION
**Pull request by miador**
## What does this PR do?
Add Resource

### Description 
Introduction to Algorithms
### Why is this valuable (or not)?
It's a fundamental book for those who start learning algorithms.
### For book lists, is it a book? For course lists, is it a course? etc.
Book
### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
How do we know this is  an authorized distribution? Please see CONTRIBUTING.md guidelines. Also #4014

**Comment by miador** [comment]
> 
> 
> How do we know this is an authorized distribution? Please see CONTRIBUTING.md guidelines. Also #4014

How do we check whether that's authorized or not?

**Comment by eshellman** [comment]
check author or publisher website

**Comment by miador** [comment]
> 
> 
> check author or publisher website

Can you check my new PR?

**Pull request closed without merging**
