### PR TITLE
Added "C" book 

### PR DESCRIPTION
**Pull request by LeoDalcegio**
This book is from a university called USP, in São Paulo, Brazil.

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s)

### Description
Added "C" book , scroll down the page and click on "Slides" to read the book.

### Checklist:
- [x ] Not a duplicate
- [x ] Included author(s) if appropriate
- [ x] Lists are in alphabetical order
- [ x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
doesn't appear to be a complete book.

**Comment by LeoDalcegio** [comment]
Why not? It has a PDF with all the 162 pages. Have you scrolled down the page and clicked on "Slides" as I said on the description?

**Comment by LeoDalcegio** [comment]
If you click on "Sumario", it will give you [this](https://www.ime.usp.br/~pf/algoritmos-livro/sumario.html) page, it has all the  chapters of the book

**Comment by LeoDalcegio** [comment]
The last item of the "Sumario" is "Árvores binárias de busca" - "Desempenho dos algoritmos", and it is the last thing the PDF has, i checked the other parts and I am sure it is a complete book

**Comment by LeoDalcegio** [comment]
Not trying to be rude, just saying it is a free and complete book hehehe.

**Pull request closed without merging**
