### PR TITLE
#4966 Add new JS tutorial

### PR DESCRIPTION
**Pull request by karenkgs**
## What does this PR do?
Add Resource(s)

### Description 
This is a course on JS that teaches how to unit test BDD style in this language

### Why is this valuable (or not)?
It's valuable because it helps with the mindset of being responsible to unit test your code

### How do we know it's really free?
It's a public youtube video

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order

### CODE REVIEW

**Comment by eshellman** [comment]
For youtube, we prefer "playlist" links and the name of the producer/creator. but don't add '(YouTube)'

**Comment by eshellman** [comment]
a "playlist URL starts with 'https://www.youtube.com/playlist'

**Comment by karenkgs** [comment]
> a "playlist URL starts with 'https://www.youtube.com/playlist'

@eshellman it's not part of a playlist though, should I just create one and link it here then?

**Comment by eshellman** [comment]
A single video like this one, 2+ hours long can be a "course" without having a playlist. But the submitter needs to highlight this. We need to  add guidelines like this to CONTRIBUTING.md (volunteers?) but I'm going to merge this.
Thanks, and welcome to free-programming-books!

**Pull request merged**
