### PR TITLE
Added cheat sheet refence to swift and c#

### PR DESCRIPTION
**Pull request by dcparga**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource

### Description 
Adding a cheat sheet for Swift and C# language equivalents and code examples

### Why is this valuable (or not)?
This adds a quick reference to whomever has to work with Swift and having a background of c#

### How do we know it's really free?
It is a free resource from a webpage with free resources for developers

### CODE REVIEW

**Comment by eshellman** [comment]
that's quite a thing! is it for c#  -> swift, swift --> c# or both?
I don't think we want N^2 categories, so pick one language or create a "language translations" category.

**Comment by dcparga** [comment]
Thanks @eshellman ! It is for both languages, but I'll add a language translations category then :)

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by cxumol** [comment]
A travis-ci lint failure `Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2  remark-lint` caused by this PR. After this merge, all later commits cannot pass the format check.

**Pull request merged**
