### PR TITLE
add: kubernetes and docker play grounds

### PR DESCRIPTION
**Pull request by gkarthiks**
## What does this PR do?
Add Resource(s)

### Description 
Adding the playgrounds for Docker and Kubernetes

### Why is this valuable (or not)
This is a valuable addition to practice Docker and Kubernetes online without installing anything in local

### How do we know it's really free?
These are from Docker and Katakoda, just try hitting the link above.

### For book lists, is it a book?
-na-

### Checklist:
- [x] Not a duplicate
- [ ] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
lists need to be in alphabetical order. see travis-ci output

**Comment by gkarthiks** [comment]
thank you @eshellman. I have fixed the issues.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by gkarthiks** [comment]
Hi @eshellman I would like to contribute to this repo as a maintainer. How to become one?

**Comment by eshellman** [comment]
Super! As this repo gets many submissions from beginning users it would be very helpful to have more experienced folks comment on submissions (always in a friendly and kind way!) and to help check that submissions conform to our guidelines. 

Another thing that would be helpful is to look through stale PRs and issues and make recommendations on how to dispose of them. We recently had a flood of submissions - probably due to Hacktoberfest - many from Indonesia, and I've had to spend more time than usual on them. For many contributors, F-P-B is a first contribution to open source and we have a responsibility to make sure it's not their last!

**Comment by gkarthiks** [comment]
@eshellman Hope this is a good comment https://github.com/EbookFoundation/free-programming-books/pull/3786#pullrequestreview-503300421. Do you have any thoughts on this? 


I also feel like this https://github.com/EbookFoundation/free-programming-books/pull/3787 PR is a legit one. But I couldn't merge it, as I don't have perms. Could you please give me the perms?

**Pull request merged**
