### PR TITLE
Add OCaml Scientific Computing

### PR DESCRIPTION
**Pull request by troglotit**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ x] Read our [contributing guidelines](/CONTRIBUTING.md)
- [ x] Search for duplicates.
- [ x] Include author(s) and platform where appropriate.
- [ ] Put lists  in alphabetical order, correct spacing.
- [ x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by SethiPandi** [comment]
Hey, and welcome to free programming books! :wave:

Could you please ensure all lists, categories, and sections/subsections remain in alphabetical order?

Could you please remove the redundant part of the URL at the end?
> always prefer the shortest link: http://example.com/dir/ is better than http://example.com/dir/index.html  
> \- https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#guidelines

You can get more guidance on the formatting and conventions in this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).

**Comment by eshellman** [comment]
Unfortunately our linter (that checks alphabetization) is not working

**Comment by troglotit** [comment]
yeah, I'm not sure which exactly alphabetical order, so went with the name

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
