### PR TITLE
Update free-courses-hi.md

### PR DESCRIPTION
**Pull request by GH05T-HUNTER5**
I'm Trying To Make New free-courses-hi.md

### CODE REVIEW

**Comment by GH05T-HUNTER5** [comment]
> Bootstrap Added

I think the best choice is to close this bootstrap

**Comment by GH05T-HUNTER5** [comment]
Error

**Comment by davorpa** [comment]
> > Bootstrap Added
> 
> I think the best choice is to close this (Update)

Why do you think so? This PR is in more advanced state than #6999 now you've committed the remaining bootstrap playlist

**Comment by GH05T-HUNTER5** [comment]
> > > Bootstrap Added
> > 
> > 
> > I think the best choice is to close this (Update)
> 
> Why do you think so? This PR is in more advanced state than #6999 now you've committed the remaining bootstrap playlist

**Comment by davorpa** [comment]
Duplicate of #7006

**Comment by davorpa** [comment]
Duplicate of #7006

**Comment by davorpa** [comment]
After merging dfad627d25cdb1071cf85527af406b531557717d and d5adb415bdb81313131d4cae9e48cdf5a035bcfa in #7006, it has a more advanced state there

**Pull request closed without merging**
