### PR TITLE
Adding C++ / Learning C++ eBook

### PR DESCRIPTION
**Pull request by Saurabh-Daware**
## What does this PR do?
Add resource

### Description
This 147 chapters long ebook was compiled from StackOverflow contributions and is free for everyone.

### Why is this valuable (or not)?
It has many C++ topics to learn from

### How do we know it's really free?
Author of this book has kept this book free.

### For book lists, is it a book? For course lists, is it a course? etc.
It's a book

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by LuigiImVector** [comment]
I don't see ads, cookie or something similar #6153, I think that the riptutorial's resources should be added/keeped.

**Comment by eshellman** [comment]
see #6153

**Comment by eshellman** [comment]
image

**Comment by LuigiImVector** [comment]
what if you replaced the link to the page with the direct link to the pdf instead? It would solve the problem of ads.

**Pull request merged**
