### PR TITLE
Add Java Web Scraping handbook

### PR DESCRIPTION
**Pull request by daolf**
## What does this PR do?
Add Resource(s)

### Description 

A 130 pages free ebook about Java Web Scraping.

### Why is this valuable (or not)

The book is a good overview of web scraping in Java.

Lots of example, it covers:
- DOM
- Xpath
- Headless
- Captchas

And much more

### How do we know it's really free?

Html and PDF are not behind any kind of form, which is pretty rare.

### For book lists, is it a book?

It is a book, previously released on leanpub and now open-sourced.

### Checklist:
- [X] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [X] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
You may not have seen it because I was tardy in migrating Travis-CI for the repo to github apps, but the checks failed. Great addition, though!

**Comment by eshellman** [comment]
Also, looks like the build failure was not your fault at all. Hang on.

**Comment by daolf** [comment]
Saw a "trailing slash problem" on Travis,

Fixed the issue :)

**Comment by daolf** [comment]
I fixed nothing :(

I thought my addition was the problem, but apparently not, you're right.

**Comment by eshellman** [comment]
just update from master to fix the build. sorry for the extra trouble

**Comment by daolf** [comment]
No worries, do you want me to recreate a PR ?

**Pull request closed without merging**
