### PR TITLE
Translating to spanish - Code of conduct

### PR DESCRIPTION
**Pull request by ArielAyala**

### CODE REVIEW

**Comment by eshellman** [comment]
need to look at one of our markdown books!

**Comment by eshellman** [comment]
not sure why this is failing

**Comment by eshellman** [comment]
need to restart from a fresh branch, I think

**Comment by eshellman** [comment]
all the linters error are due to other files added since this PR was made, so I suggest taking the file and resubmitting from a fresh branch. Would be a great help if you do it - otherwise leave it and another volunteer will try - only 100 PRs left! (while you're add it, add a links to/from the other CoCs)

**Comment by ArielAyala** [comment]
I will open other pull request now

**Pull request closed without merging**
