### PR TITLE
Added favicon to the website which will make the site look great.

### LINKED ISSUE #11337: Issue: Missing Favicon on the Website
I noticed that the [website](https://ebookfoundation.github.io/free-programming-books-search/) currently does not have a favicon. A favicon is a small but important element that adds a more professional and polished look to the site. It also helps users quickly recognize the tab when multiple browser tabs are open.

I would like to suggest adding a favicon to the site.

If you're open to this improvement, I'd be happy to contribute by adding the favicon myself. Please let me know if you'd like me to proceed!

### PR DESCRIPTION
**Pull request by Ajay-singh1**
## What does this PR do?
Improve repo

### Description
Added favicon to the site which will make the site look great fixes #11337 I have tested the site locally through github pages and it works great :).I have added the ebookfoundation logo as the favicon.

### Why is this valuable (or not)?

Yes it is very valuable

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Ajay-singh1** [comment]
Screenshot from 2024-10-18 08-10-54

**Comment by eshellman** [comment]
Hmmm, looks like this change breaks the build

**Comment by Ajay-singh1** [comment]
@eshellman Yes the build will break for this PR as I have added the favicon icon and nothing else.The site uses Jekyll theme and uses a remote theme from minimal so I just injected favicon in the <head>tag.What are your thoughts?

**Comment by eshellman** [comment]
Maybe you need to inject it from the free-programming-ebooks-search repo?

**Comment by Ajay-singh1** [comment]
@eshellman Okay I will do that.

**Comment by Thenlie** [comment]
The "Check URLs" actions are failing due to the file types of the changed files. 

https://github.com/EbookFoundation/free-programming-books/blob/main/.github/workflows/check-urls.yml#L93 On this line we grab the file by getting all characters preceding a .md or .yml extension. The two files failing the check have a .html and .ico extension so this file name is blank. Because of this the upload artifact step fails.

## Options for Resolution

1. Add the .ico and .html extension to that regex linked above, however that could cause issues as we don't actually want to "check URLs" for these file types. 
2. Simply ignore the Check URLs step here as it is not relevant to these files. 
3. Update the action to skip if the file extension is not .md or .yml. I think this is likely the best option.

cc: @eshellman

**Comment by Ajay-singh1** [comment]
@Thenlie Thanks for helping out here.

**Comment by Thenlie** [comment]
@Ajay-singh1 #11760 should get this working. Let me know if not!

**Comment by Ajay-singh1** [comment]
@eshellman We can cleanly merge this PR now.

**Pull request merged**
