### PR TITLE
Added JavaScript book in Bengali (changes made)

### PR DESCRIPTION
**Pull request by pratap360**
## What does this PR do?
Add resource

### Description
 - added a Javascript book in Bengali form _**howtocode**_ 
### Why is this valuable (or not)?
- yes it's a valuable content for beginners special for who know Bengali Language 
### How do we know it's really free?
- this book is free of cost as it is maintained in [github repository ](https://github.com/howtocode-dev/js.howtocode.dev) &  it is powered by Git Book.
### For book lists, is it a book? For course lists, is it a course? etc.
- It is a book.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by sohansai** [comment]
Check the status of GitHub Actions and resolve reported warnings.

**Comment by pratap360** [comment]
> Check the status of GitHub Actions and resolve reported warnings.

_done with resolve all reported warnings_

**Comment by eshellman** [comment]
need to add JavaScript to the index, too
when you've made changes, please add `(changes made)` to the title of your PR

**Comment by pratap360** [comment]
- added (changes made) to the tittle of the PR and JavaScript is already in the index.

**Comment by eshellman** [comment]
So it is! 
Thanks, and welcome to free-programming-books!

**Pull request merged**
