### PR TITLE
Added course and book including C in bangla, linux book and Kotlin in…

### PR DESCRIPTION
**Pull request by pawaspy**
… Bangla

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

**Comment by pawaspy** [comment]
@eshellman please review the folders it is corrected now added youtube video of Kotlin and C in bangla and added book on Linux

**Comment by pawaspy** [comment]
> Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

Now you can see if there is any error. I think it is resolved. #10400 @eshellman

**Review by pawaspy — COMMENTED** [review]
Please review this file and let me know if any changes in merging.

**Comment by eshellman** [comment]
why are you adding these files?
Please read docs/CONTRIBUTING.md guidelines!

**Pull request closed without merging**
