### PR TITLE
Add Processing Resource - Fix

### PR DESCRIPTION
**Pull request by stmapman7**
## Hacktoberfest notes:

- due to the volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open-source contribution, make sure it's not your last!

## What does this PR do?
Add resources

### Description 
 Added a Processing YouTube playlist
### Why is this valuable (or not)?
For beginners to learn more about Processing, a media software application.
### How do we know it's really free?
It's posted publicly on YouTube.
### For book lists, is it a book? For course lists, is it a course? etc.
It's a course playlist.
### Checklist:
- [X] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [X] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
For youtube, we prefer "playlist" links and the name of the producer/creator.

**Comment by stmapman7** [comment]
Resubmitted.

**Comment by eshellman** [comment]
these videos constitute a course, not really a screencast. I would list it in courses this way:
`[Learning Processing: A Beginner's Guide to Programming Images, Animation, and Interaction](https://www.youtube.com/c/TheCodingTrain/playlists?view=50&sort=dd&shelf_id=10) - The Coding Train`

**Comment by stmapman7** [comment]
No problem @eshellman, 

I removed it from the screencasts list and added it to the free courses one.  

Thanks!

**Comment by eshellman** [comment]
thanks! sorry for the incomplete guidance - lots of PRs to review!

**Comment by stmapman7** [comment]
You're welcome @eshellman, 

I'm happy that you provided me the guidance and understand you've got a lot to do!

**Pull request merged**
