### PR TITLE
Add codecatalog.org to Open Source Ecosystem

### PR DESCRIPTION
**Pull request by ainzzorl**
## What does this PR do?

Add resource

### Description

Code Catalog is a collection of annotated code examples from prominent open source projects.

### Why is this valuable (or not)?

It makes learning good practices from open source easier by explaining, annotating and categorizing examples from popular open source projects.

### How do we know it's really free?

It's avaiable under the [Creative Commons Attribution 4.0 International](https://github.com/ainzzorl/goodcode/blob/main/LICENSE) license.

### For book lists, is it a book? For course lists, is it a course? etc.

It's not exactly a book, but it's close. It's a collection of articles (not a blog).

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
This is the sort of thing that I think is worth supporting in F-P-B,  but it's not a book.
The category we have that fits it best is meta-lists, which are also not books, and maybe we should move these resources to a "not-a-book" list. Comments are welcome!

**Comment by davorpa** [comment]
> This is the sort of thing that I think is worth supporting in F-P-B, but it's not a book.
> The category we have that fits it best is meta-lists, which are also not books, and maybe we should move these resources to a "not-a-book" list. Comments are welcome!

I aggree move it under metalist section since is composed by a bunch of topics.

Can I propose review changes?

**Comment by eshellman** [comment]
change proposals are welcome.

**Comment by ainzzorl** [comment]
Moving it to meta-lists sounds good to me! Waiting for the change proposal.

**Review by davorpa — CHANGES_REQUESTED** [review]
Moving resource to meta-list section L557

https://github.com/EbookFoundation/free-programming-books/blob/f744247ae61b847062b63b185175aab760325077/books/free-programming-books.md#L251-L258

**Comment by ainzzorl** [comment]
> Moving resource to meta-list section L557
> 
> https://github.com/EbookFoundation/free-programming-books/blob/f744247ae61b847062b63b185175aab760325077/books/free-programming-books.md#L251-L258
> 
> @ainzzorl, since I haven't write access rights here, you should merge the PR [ainzzorl#1](https://github.com/ainzzorl/free-programming-books/pull/1) I push in your repo and it will be automatically reflected here.

Done. Thanks!

**Review by davorpa — APPROVED** [review]
Supe 🚀 👍

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
