### PR TITLE
Update free-courses-en.md

### PR DESCRIPTION
**Pull request by saimanvitha02**
Updated tutorials for Java, R, SQL

## What does this PR do?
Add Resources | Add info | Improve Repo

## For resources
Updated tutorials for Java, R, SQL

### Why is this valuable (or not)
The updated tutorials are regarding the most used languages in the current scenario.

### How do we know it's really free?
The video links are provided from YouTube and the channels are absolutely free.

### For book lists, is it a book?
No, it's not a book, they are video lectures.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
see comment on #3737

**Comment by saimanvitha02** [comment]
> see comment on #3737

Sir, this includes complete video tutorials from freeCodeCamp as well as Edureka and video length is usually from 6-8 hours.

**Review by saimanvitha02 — COMMENTED** [review]
Sir, have updated according to #3737. Kindly check if anything else is to be added.

**Comment by S6amsavvy9** [comment]
Unsubscribe me thank you

**Pull request merged**
