### PR TITLE
Added the bash book to the books section

### PR DESCRIPTION
**Pull request by bharath-123**
I have attempted to add the bash book to the book section again. There was  an issue the last time , i tried to propose the file change as i had not placed it in alphabetical order. Someone please review this :)

### CODE REVIEW

**Comment by eshellman** [comment]
'space' < a in the collation

**Comment by bharath-123** [comment]
I am sorry, but could you please elaborate? I didnt understand what 'space' < a meant!
Thank You :D

**Comment by eshellman** [comment]
Sorry, I was in a hurry. Look at the Travis-CI output. The linter complains that the books are not in alphabetical order.  so "Bash tutorial" comes before "BashGuide" because " " comes before "G".

**Comment by charlottetan** [comment]
this PR is for #2482

**Comment by charlottetan** [comment]
Looks like this PR has been abandoned? Might be worth closing out

**Pull request merged**
