### PR TITLE
Add My Free Java Course to free-courses-en list

### PR DESCRIPTION
**Pull request by anjones1000**
## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo
Added Free Java Course by Angie Jones
### Description 
 [My Free Java Course - Automation, Development](https://angiejones.tech/free-java-course-test-automation/) - Angie Jones
### Why is this valuable (or not)
It is a self paced, online course that helps beginners in understanding the fundamentals of programming using Java. 
### How do we know it's really free?
The website says its free. I am currently taking it and it's free.
### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
please resolve conflicts. also, if this is your site, that's super!

**Comment by anjones1000** [comment]
Hi Mr. Hellman,

Ironically my name is Angelica Jones, but this course was made by Angie Jones. She’s a Developer Advocate I follow on twitter and thought her course should be shared on your site!
Here’s her twitter handle:
https://twitter.com/techgirl1908

I hope I have resolved the conflicts!

**Comment by anjones1000** [comment]
Hi Mr. Hellman,

Ironically my name is Angelica Jones, but this course was made by Angie Jones. She’s a Developer Advocate I follow on twitter and thought her course should be shared on your site!
Here’s her twitter handle:
https://twitter.com/techgirl1908

I hope I have resolved the conflicts!

**Comment by eshellman** [comment]
hmmm, I guess the linter doesn't catch empty lines the way you have them??

**Comment by anjones1000** [comment]
I'll take a look at it

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by anjones1000** [comment]
Yay! Thank you!

**Pull request merged**
