### PR TITLE
Added a new kotlin course

### PR DESCRIPTION
**Pull request by Kundai10**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo
Add resources

## Checklist:
- [x ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Ajay-singh1** [comment]
Check for the linter errors.

**Comment by raj007-star** [comment]
Please follow the alphabetical ordering in order to pass the test cases.

**Comment by Kundai10** [comment]
@raj007-star Done!

**Comment by eshellman** [comment]
Don't invent titles! Use the title given by the resource.

**Comment by Kundai10** [comment]
@eshellman I ddn't invent a title.

**Comment by Kundai10** [comment]
@eshellman Click the link and see that I did not invent a title

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
