### PR TITLE
Created and Updated CODE_OF_CONDUCT-si.md

### PR DESCRIPTION
**Pull request by jobin2233**
## PR Title
Fixed this issue: Need Sinhala translation of the code of conduct #9593

### Why is this change necessary?:
- Diversity and inclusivity are fundamental values for our project. By providing a Code of Conduct in Sinhala, we aim to make our community accessible and welcoming to Sinhala-speaking individuals.
- This addition ensures that all participants understand the expected behavior and consequences of any violations, fostering a more respectful and collaborative environment.

## Context:
- The Sinhala language (සිංහල) is one of the official languages of Sri Lanka and is spoken by a significant population worldwide. It is essential to provide content in Sinhala to cater to a broader audience.

### CODE REVIEW

**Comment by eshellman** [comment]
why are you also editing the ZH translation?

**Comment by jobin2233** [comment]
That was my earlier pull request: ( https://github.com/EbookFoundation/free-programming-books/pull/9928 ) which you have merged. When I forked this repo with my device, I need to just update with the latest one. It doesnot create any conflicts.

**Comment by jobin2233** [comment]
I haven't editted it. It just automatically updated since both are from docs branch.

**Comment by eshellman** [comment]
you'll need to start from a fresh branch

**Pull request closed without merging**
