### PR TITLE
adding-new-index-and-course

### PR DESCRIPTION
**Pull request by Ashu104**
## What does this PR do?
Add resource(s)

### Description
this pr adding a new index and book which should be there in order to provide diverse knowledge to our users.

### Why is this valuable (or not)?
there is a missing index which is important at the same time.

### How do we know it's really free?
this is pdf book which is freely available on the internet, we all can access and download it

### For book lists, is it a book? For course lists, is it a course? etc.
it is a book on computer network. which in not available in past updates. 

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
we have a networking category

**Comment by eshellman** [comment]
and DO NOT close and open a new PR, work on THIS PR

**Comment by Ashu104** [comment]
> we have a networking category

hey @eshellman  
I search and found there isn't specific book or index related to computer networking tech.
Also, I found there are books on topic like ras-pi, windows. so having a book on computer network will help us to understand them well.

**Comment by eshellman** [comment]
look in free-programming-books-subjects.md

**Comment by Ashu104** [comment]
> look in free-programming-books-subjects.md

sure.  I've added it there itself, now could you pls merge it.

**Pull request merged**
