### PR TITLE
Add Chewing C, C++, check_urls=free-programming-books-ko.md

### PR DESCRIPTION
**Pull request by DPS0340**
## What does this PR do?
Add resources

### Description 
씹어먹는 C, C++(Chewing C, C++) is Korean web book about C, C++ beginner course.

they are separated two books about C and C++, But They has some similarity in formats, book styles.. etc.

The Author is 이재범(Jaebum Lee).

### Why is this valuable (or not)?
It is considered valuable, important web material to learning C, C++ in korea.

### How do we know it's really free?
The web version is genuine, free material which author uploaded.

### For book lists, is it a book? For course lists, is it a course? etc.
It's web book made of html format on blog.

## Checklist:
- [X] Read our [contributing guidelines](/CONTRIBUTING.md)
- [X] Search for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists  in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Review by Marusyk — APPROVED** [review]

**Comment by eshellman** [comment]
In Google translate at least, these are described as "courses" rather than books. What do you think? Who would find it more useful, someone lookinig for a book, or someone looking for a course?

**Comment by DPS0340** [comment]
Web format is a course rather than book(sorry i'm confused..), but it also has pdf version.

I think that pdf version have to place book category, and web format goes course.

Link:
[C](https://modoocode.com/187)
[C++](https://modoocode.com/312)

**Comment by DPS0340** [comment]
And I found wrong typo in ```C++로 배우는 딥러닝``` in korean courses, so I fixed it.

**Comment by DPS0340** [comment]
Sorted C/C++ courses.

**Comment by DPS0340** [comment]
Wait.. my link is wrong.

**Comment by DPS0340** [comment]
I Fixed link.

**Comment by DPS0340** [comment]
Markdown link ```#c++``` is not working, so I changed this to ```#c-1```

**Comment by eshellman** [comment]
Thanks for all the corrections.
We won't add the same link to two lists; if there is a link going directly to the pdf, we can add that in the book list, but otherwise lets keep the mondoocode links in courses.

**Comment by DPS0340** [comment]
Ok. currently link on book provides some explanation and pdf link, i'll change this to download link.

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
