### PR TITLE
add new arabic cources

### PR DESCRIPTION
**Pull request by AhmedElTabarani**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by AhmedElTabarani** [comment]
## NOTES

I added new categories

- DevOps
- Elastic
- Nuxt.js
- Microservice
- RabbitMQ
- Redis


I bring back Ahmed Elemam's course about Designing Data Intensive Applications because he explains the book in his way with slideshow not copy-paste from the book, and talking about main part of each chapter

**Review by eshellman — CHANGES_REQUESTED** [review]
looks great. The only problem I see is that we don't use honorifics such as "Dr.". "Prof.", etc.

**Comment by AhmedElTabarani** [comment]
> looks great. The only problem I see is that we don't use honorifics such as "Dr.". "Prof.", etc.

Dr. Khaled Mostafa Elsayed
 ?

that the name of his channel
https://www.youtube.com/@dr.khaledmostafaelsayed7516

**Comment by eshellman** [comment]
correct. it should be credited in our list to "Khaled Mostafa Elsayed" (no "dr.")

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
