### PR TITLE
Update free-programming-interactive-tutorials-en.md

### PR DESCRIPTION
**Pull request by Sanjana-Bhat-02**
## What does this PR do?
Add resource(s) 

### Why is this valuable (or not)?
It gamifies programming

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
seems like python?

**Comment by Sanjana-Bhat-02** [comment]
Hello, what do you mean?

**Comment by eshellman** [comment]
why is it in the javascript section?

**Comment by Sanjana-Bhat-02** [comment]
Because there a lot of programming courses there, and javascript is one of
them, there was no section for all rounder courses so I put it one section

**Comment by eshellman** [comment]
all of our sections have lots of programming books! I suggest you take some time and familiarize ypurself with the repo.

**Pull request closed without merging**
