### PR TITLE
updating url addresses

### PR DESCRIPTION
**Pull request by mohamedation**
## What does this PR do?
Improve repo

### Why is this valuable (or not)?
better current url structure

### How do we know it's really free?
i am the author

### For book lists, is it a book? For course lists, is it a course? etc.
book (online guide)

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
Hmmm the link check report has a lots. https://github.com/EbookFoundation/free-programming-books/actions/runs/6389161328

**Comment by eshellman** [comment]
have you verified that all the changed links work?

**Comment by mohamedation** [comment]
@eshellman yes the 2 urls changed for the Arabic and English version of the html guide has been checked and works.

**Comment by mohamedation** [comment]
it also seems that  librebooks.org is out of service (temporarily) and that is the source of a lot of Arabic books. i will try to contact the maintainer of the site to check if it will be back soon or not.

**Comment by eshellman** [comment]
Thanks

**Pull request merged**
