### PR TITLE
Add Haskell free courses by Prof. Graham Hutton

### PR DESCRIPTION
**Pull request by tuxdna**
## What does this PR do?

Add resource(s)

### Why is this valuable (or not)?

A trusted resources for learning Haskell programming language.

### How do we know it's really free?

Lectures available online with slides and code discussed in the lectures.

### For book lists, is it a book? For course lists, is it a course? etc.

It is an online lecture series by Prof. Graham Hutton.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by tuxdna** [comment]
All checks are passing. Please merge this PR.

**Comment by eshellman** [comment]
On link per course, please. We do not allow honorifis such as "Prof."

**Comment by tuxdna** [comment]
@eshellman Updated for the changes you mentioned in your last comment.

I think  `fpb-lint` command in [CI - workflows/fpb-lint.yml ](https://github.com/EbookFoundation/free-programming-books/blob/main/.github/workflows/fpb-lint.yml#L22) should check such honorific titles in author names automatically.

**Comment by eshellman** [comment]
> @eshellman Updated for the changes you mentioned in your last comment.
> 
> I think `fpb-lint` command in [CI - workflows/fpb-lint.yml ](https://github.com/EbookFoundation/free-programming-books/blob/main/.github/workflows/fpb-lint.yml#L22) should check such honorific titles in author names automatically.

submit a PR at
https://github.com/vhf/free-programming-books-lint

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
