### PR TITLE
Revoming a book which is not free at all

### PR DESCRIPTION
**Pull request by pirrmann**
I'm sure @tpetricek can confirm his book is not free

### CODE REVIEW

**Comment by eshellman** [comment]
Agreed!

**Comment by eshellman** [comment]
Github has an fair, open and easy to use DMCA removal process should @tpetricek or Manning elect to use it.

**Comment by tpetricek** [comment]
Thanks for removing the link. It's worth noting that the link also points to an early draft with typos and very ugly formatting. So buying the final ebook not only gives you a good feeling of supporting the author (who spent some two years working on it), but you'll also get a much nicer version of the book with fewer issues 👍

**Comment by thokaka92** [comment]
_Sent from my P10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by thokaka92** [comment]
_Sent from my P10 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_thokaka92

**Pull request merged**
