### PR TITLE
Added Pandas books.

### PR DESCRIPTION
**Pull request by GintasS**
## What does this PR do?
Added resources

### Description 
I added two Pandas books.

### Why is this valuable (or not)?
They're free.

### How do we know it's really free?
One is a tutorial available on the internet, second one is a book, provided by the author.

### For book lists, is it a book? For course lists, is it a course? etc.
They're books.

## Checklist:
- [x] Read our [contributing guidelines](/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists  in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
Did you consider putting the tutorial into the interactive tutorial list? seems theres a jupyter notebook and other files to go with it.

**Comment by GintasS** [comment]
> Did you consider putting the tutorial into the interactive tutorial list? seems theres a jupyter notebook and other files to go with it.

Do you mean free courses.md, or meta-list in free-programming-books?

**Comment by eshellman** [comment]
free-programming-interactive-tutorials-en.md

**Comment by GintasS** [comment]
> free-programming-interactive-tutorials-en.md

Added. Thanks.

**Comment by eshellman** [comment]
Good. One more thing (sorry to be a pain!). in the books list Pandas is a Python subcategory. On the interactive tutorials list, this would be a single-item category, which we try to avoid. You can either make pandas  into a python subcategory or just use the python category. Try to think of a user (maybe with python experience) looking for a pandas tutorial and decide which would be most helpful.

**Comment by GintasS** [comment]
> Good. One more thing (sorry to be a pain!). in the books list Pandas is a Python subcategory. On the interactive tutorials list, this would be a single-item category, which we try to avoid. You can either make pandas into a python subcategory or just use the python category. Try to think of a user (maybe with python experience) looking for a pandas tutorial and decide which would be most helpful.

Quite the opposite, I appreciate your help and support, these things are easy to fix, thanks again 👍 
I decided to put it into the python category itself, because I saw one of the items **[How to Think Like a Computer Scientist: Learning with Python, Interactive Edition** something to do with data science, so pandas will be OK here.

**Pull request merged**
