### PR TITLE
Added computer architecture book in russian

### PR DESCRIPTION
**Pull request by GaynullinDima**

### CODE REVIEW

**Comment by vhf** [comment]
Thanks for the suggestion! Is this the official source of the pdf or is there a more official one, on Adobe website for example?

**Comment by GaynullinDima** [comment]
It's the official one actually.

**Comment by GaynullinDima** [comment]
They bought rights for printing russian edition and distribute it for free.  Registration is required.

**Comment by eshellman** [comment]
Picking this up from some months ago...

For consistency, the notation *(account required)* (translated to russian!) should be added.

**Comment by eshellman** [comment]
please add "(требуется учетная запись)" and resubmit. (This PR is 1 year old).

**Pull request closed without merging**
