### PR TITLE
add Ada for the C++ or Java Developer

### PR DESCRIPTION
**Pull request by momozor**
## What does this PR do?
add a new Ada programming language book

### Why is this valuable (or not)
There are not many *free* Ada book around.

### How do we know it's really free?
It is released under the http://creativecommons.org/licenses/by/4.0/ license at the bottom of the site.

### For book lists, is it a book?
This is a book (well, an e-book, if that counts).

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
This is a super resource, and you're right about there not being a lot of Ada free resources.

As you write, this is between an interactive tutorial and a book. In deciding between the two, I'd put weight on how the resource describes itself ("a course"), so I'd put it in the interactive tutorials list.

**Comment by momozor** [comment]
@eshellman Hi, thanks for the review. May I know, where should I put this or what do I need to change if any?

**Comment by eshellman** [comment]
Please do one of two things
1. revise the PR to add the resource to the interactive tutorials list
or
2. tell me you think this should REALLY be on the book list instead, and I'll merge the PR.

**Comment by momozor** [comment]
@eshellman I moved the former interactive tutorial into a separate PR - https://github.com/EbookFoundation/free-programming-books/pull/3227

**Comment by eshellman** [comment]
Wow, thanks for the extra work!

**Comment by momozor** [comment]
:-)

**Pull request merged**
