### PR TITLE
Add German podcast Python Podcast

### PR DESCRIPTION
**Pull request by jk4e**
## What does this PR do?
Add resource: Adding the first German podcast to the repository

### Description
A German podcast about the Python programming language.

### Why is this valuable (or not)?
Great podcast in German about Python. I am a listener myself. Podcast started in 2018.

### How do we know it's really free?
It is free. The site is run by the podcasters themselves.

### For book lists, is it a book? For course lists, is it a course? etc.
It is a fantastic podcast in the German language! (podcast)

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
@Thenlie Do you understand why the check on this PR is failing?

**Comment by Thenlie** [comment]
@eshellman I have recreated an identical PR #11229 and am seeing the same problem, so re-running probably will not help. Will continue to investigate on that branch and update here with anything I find.

**Comment by Thenlie** [comment]
Alright, made some progress, though not totally there. It seems this issue has popped up recently for a lot of people on GitHub. https://github.com/actions/download-artifact/issues/339. There are a few possible solutions, though nothing definitive. I have tried removing the `name` field from the download step and at least one of the artifacts successfully downloaded when I did that. I have to step away now but will continue digging into this ASAP.

**Comment by jk4e** [comment]
Everything looks fine now. Sorry, that my PR caused so much trouble/issues. Thanks for your help @Thenlie! Thank you so much for all the work you put into this fantastic project @eshellman!

**Comment by Thenlie** [comment]
> Everything looks fine now. Sorry, that my PR caused so much trouble/issues. 

No problem whatsoever! If anything, this PR just highlighted an existing bug, so thank you <3

**Pull request merged**
