### PR TITLE
Update free-programming-books-bg.md

### PR DESCRIPTION
**Pull request by WaLkZa**
## What does this PR do?
Add more books and fix some old links

### How do we know it's really free?
All books by Svetlin Nakov are free.

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
alphabetizing cyrillic can be confusing - the linter looks for Unicode order. Thanks for fixing the other links- that link tester is a new thing we're just getting used to. Added resources look good.

**Comment by WaLkZa** [comment]
@eshellman will it be merged or you want to fix the Unicode order? Because right now they are logically ordered.

**Comment by eshellman** [comment]
Alphabetization is in unicode order - see travis-CI output for its suggestions on how to fix it.

**Comment by WaLkZa** [comment]
@ericallam I don't understand that output. How to understand which lines to swap?

     3:1-9:20  warning  Alphabetical ordering: swap l.5 and l.4    alphabetize-lists  remark-lint
  31:1-34:103  warning  Alphabetical ordering: swap l.33 and l.32  alphabetize-lists  remark-lint
  31:1-34:103  warning  Alphabetical ordering: swap l.34 and l.33  alphabetize-lists  remark-lint

**Comment by eshellman** [comment]
```
4  * [C++](#c-plus-plus)
5  * [C#](#c-sharp)
```
'#' < '+', so C# should come before C++ (unicode(0035) < unicode(0043))

**Comment by WaLkZa** [comment]
Finally!

**Comment by eshellman** [comment]
Welcome to free-programming-books!

**Pull request merged**
