### PR TITLE
Adding 2 Vim Interactive Games/Tutorials

### PR DESCRIPTION
**Pull request by wteja**
## What does this PR do?
Adding 2 Vim Interactive Games/Tutorial

## For resources
[The Vim Adventure Games](https://vim-adventures.com) - Learn Vim by playing adventure game, it's really fun game that force player to use Vim commands and shortcut keys to pass the levels.
[Vim Genius](http://vimgenius.com/) - This a flashcard style game to help you learn the basics of Vim

### Why is this valuable (or not)?
They are popular and fun games that help beginner find the enjoyment while learning Vim Editor

### How do we know it's really free?
They are free to play

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
these will fit better into the playgrounds list

**Comment by wteja** [comment]
> these will fit better into the playgrounds list

Thank you, I moved to the playground list instead.

**Comment by nclements** [comment]
On a whim I decided to try [The Vim Adventure Games](https://vim-adventures.com/). After completing(?) level 3 a popup appears that indicates it costs $25 (game-only, or $30 with challenges) for a 6-month license. Not sure if it's playable beyond the popup.

**Comment by eshellman** [comment]
@nclements thanks for checking that. It should be removed.

**Pull request merged**
