### PR TITLE
Update free-courses-en.md

### PR DESCRIPTION
**Pull request by saimanvitha02**
## What does this PR do?
Add Resources - Video links for various courses.

## For resources
Resources for learning C, C++, C#, Data Structures, and Algorithms

### Why is this valuable (or not)
These tutorials are extremely useful for beginners to learn programming languages. 

### How do we know it's really free?
All the links I provided are from the YouTube channel, **freeCodeCamp.org**, which provides hours of free lectures that are useful for beginners in programming.

### For book lists, is it a book?
No, they are video links.

### Checklist:
- [x] Not a duplicate
- [ ] Included author(s) if appropriate
- [x] Lists are in alphabetical order 
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
for youtube, we'll link to playlists as courses, but not individual videos, in general

**Review by saimanvitha02 — COMMENTED** [review]
Removed the extra blank space, now I think the check should pass

**Comment by eshellman** [comment]
OK, linter satisfied! Could you add the  `(FreeCodeCamp)` notations. These help the readers figure out where the video is coming from. You can also add the lecturer name where appropriate.

**Review by saimanvitha02 — COMMENTED** [review]
Have updated the tutor's names and links directing to the freeCodeCamp website. I didn't understand what you meant by freeCodeCamp notations. If you can explain it, I'll do it. Otherwise, if the latest update is sufficient, we can go with it as well.

**Comment by eshellman** [comment]
instead of `[freeCodeCamp](https://www.freecodecamp.org)`, just use `(freeCodeCamp)`

**Review by saimanvitha02 — COMMENTED** [review]
Done sir.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
