### PR TITLE
Add Docker course link in free-courses-en

### PR DESCRIPTION
**Pull request by itsfarhan**
## What does this PR do?
Add resources

## For resources
This is a complete docker course by DevOps Directive 

This course covers everything from getting started all the way through building a containerized web application and deploying it to the cloud

### How do we know it's really free?
Available on youtube for free

### For book lists, is it a book? For course lists, is it a course? etc.
Its a course structured video with 4 hours+ content. Follows from docker basic commands to image buiding and orchestration with docker swarm and kubernetes.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by sohansai — COMMENTED** [review]
We prefer 'playlist' links for YouTube contributions

**Comment by itsfarhan** [comment]
> We prefer 'playlist' links for YouTube contributions

DevOps Directive have his own site and course uploaded on youtube.

I can see many single videos in docker section.

example - [Docker Tutorial for Beginners - What is Docker? Introduction to Containers](https://www.youtube.com/watch?v=17Bl31rlnRM) - Kunal Kushwaha

**Comment by eshellman** [comment]
Please read docs/CONTRIBUTING.md guidelines!

**Comment by itsfarhan** [comment]
> Please read docs/CONTRIBUTING.md guidelines!

I am sorry. My bad. I failed to mention that the course link which I added follows course like structure and its 4+ hours of video.

According to guideline -> YouTube videos. We usually don't link to individual YouTube videos unless they are more than an hour long and are structured like a course or a tutorial. If this is the case, be sure to make a note of it in the PR description.

**Pull request merged**
