### PR TITLE
added cp sites

### LINKED ISSUE #3719: Competitive Programming website suggestion
I want to add:

- [Toph](https://toph.co/)
- [URI Online Judge](https://www.urionlinejudge.com.br/judge/en/login)

under the **Competitive Programming** section of **problem-sets-competitive-programming.md** file

### PR DESCRIPTION
**Pull request by Tahanima**
## What does this PR do?
Add Resource
Fixes #3719 

### Description 
I have added links to Toph and URI Online Judge under the Competitive Programming section of problem-sets-competitive-programming.md file

### Why is this valuable (or not)
I've personally used these sites for solving problems. They contain a lot of useful programming problems that I feel any problem-solving enthusiast will find useful.

### How do we know it's really free?
I've personally used these sites. All that is required to submit a solution to a programming problem in these sites is to have an account that can easily be obtained by registering through email.

### Checklist:
- [x] Not a duplicate
- [ ] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Thanks for the PR. Please check travis-ci to see what the linter is failing for. (I have lots of Hacktoberfest submissions to process!)

**Comment by Tahanima** [comment]
> Thanks for the PR. Please check travis-ci to see what the linter is failing for. (I have lots of Hacktoberfest submissions to process!)

You're welcome and I've resolved the issue.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by Tahanima** [comment]
> Thanks, and welcome to free-programming-books!

Thank You so much for the opportunity.

**Pull request merged**
