### PR TITLE
Old site has stoped updating

### PR DESCRIPTION
**Pull request by 117028813**
new content in http://d3.decembercafe.org/

### CODE REVIEW

**Comment by eshellman** [comment]
Please check the Travis CI checks.

**Comment by zhongjiajie** [comment]
Hi @117028813 , I don't think your PR is right for this repository. This repository need the free books but you offer a link to bug the `D3` books.

**Comment by eshellman** [comment]
@zhongjiajie the PR didn't get accepted because it failed the travis check (un-needed trailing '/' on the url). I assume you mean 'buy' not 'bug', but it looks to me like the content of the book is free online. Is that correct?

**Comment by zhongjiajie** [comment]
Sorry i am poor in my Engilsh @eshellman, I kown reason PR didn't get accepted because it failed the travis check. First time I see the URL and I find out is a link to online stop to buy the D3 books, But I see the content of the book is free online just now.

**Comment by 117028813** [comment]
Oh, thank you very much, because I am poor in my English, so I didn't know what 'travis ' mean. Now I see, thank you all.

**Comment by eshellman** [comment]
Thank you @117028813 and @zhongjiajie !

**Comment by 117028813** [comment]
image
Why did the modified format look like this? I examined the code carefully but not found error.

**Pull request merged**
