### PR TITLE
Add "AWS Well-Architected Framework"

### PR DESCRIPTION
**Pull request by ainzzorl**
## What does this PR do?
Add resource

### Description

"The AWS Well-Architected Framework describes the key concepts, design principles, and architectural best practices for designing and running workloads in the cloud. By answering a set of foundational questions, you learn how well your architecture aligns with cloud best practices and are provided guidance for making improvements." - https://aws.amazon.com/architecture/well-architected

### Why is this valuable (or not)?

"AWS Well-Architected helps cloud architects build secure, high-performing, resilient, and efficient infrastructure for their applications and workloads. Based on five pillars — operational excellence, security, reliability, performance efficiency, and cost optimization — AWS Well-Architected provides a consistent approach for customers and partners to evaluate architectures, and implement designs that can scale over time." - https://aws.amazon.com/architecture/well-architected

### How do we know it's really free?

It's available on AWS' official website, e.g. linked from https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html

### For book lists, is it a book? For course lists, is it a course? etc.

They call it a whitepaper; IMO counts as a book.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by ainzzorl** [comment]
Azure, a competing cloud provider, published a very similar guide for their cloud: https://docs.microsoft.com/en-us/azure/architecture/framework/. It's even called the same.

It would be fair to add it here too, but it's only available as a collection of HTML pages; I'm not sure it counts as a "book" then.

**Comment by eshellman** [comment]
This is enough of a book for us. consider linking to the html "welcome" page, as that links to the pdf. Funny that they don't link to the kindle f=version from there.

**Comment by ainzzorl** [comment]
> consider linking to the html "welcome" page, as that links to the pdf.

Done. Also shortened it to https://docs.aws.amazon.com/wellarchitected/latest/framework and changed "PDF" to "PDF, HTML".

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
