### PR TITLE
Update free-courses-ar.md

### PR DESCRIPTION
**Pull request by Adamkaram**
adding more courses on operating system

## What does this PR do?
adding more courses on operating system

### Why is this valuable (or not)?
i've learn from these resources and were quit good 

### How do we know it's really free?
youtube courses 

### For book lists, is it a book? For course lists, is it a course? etc.
course

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Adamkaram** [comment]
why linter keep giving me these errors and nothing wrong with my alphapetical ordering ?

**Comment by eshellman** [comment]
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

**Comment by Adamkaram** [comment]
> Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

done

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!
You might look at cleaning up the right to left markup in this list - look at #6714 for info

**Comment by Adamkaram** [comment]
> Thanks, and welcome to free-programming-books! You might look at cleaning up the right to left markup in this list - look at #6714 for info

woww i like this

**Pull request merged**
