### PR TITLE
Added Crafting Interpreters

### PR DESCRIPTION
**Pull request by quobit**
Though is not yet finished it looks very promising!

### CODE REVIEW

**Comment by tedyoung** [comment]
@eshellman, given #2357, should @quobit update this PR with the 🚧 character/emoji? (The author of Crafting Interpreters is actively working on this and I'm enjoying it so far.)

**Comment by eshellman** [comment]
as I feared, the linter wants 🚧 to be alphabetized differently.

**Comment by quobit** [comment]
@eshellman do you need any other action from my side?

**Comment by eshellman** [comment]
@quobit no. will merge and see if people like it.

**Comment by quobit** [comment]
Nice!

**Pull request merged**
