### PR TITLE
Removed broken links (404)

### PR DESCRIPTION
**Pull request by dbrn**
* [CSS Básico a Avanzado](https://www.pildorasinformaticas.es/course/css-avanzado-desde-0) - Juan Díaz (Píldoras Informáticas)
* [HTML 5](https://www.pildorasinformaticas.es/course/html-5) - Juan Díaz (Píldoras Informáticas)
* [PHP MySql Módulo 1](https://www.pildorasinformaticas.es/course/php-mysql) - Juan Díaz (Píldoras Informáticas)
* [PHP MySql Módulo 2](https://www.pildorasinformaticas.es/course/php-mysql/php-mysql-modulo-2) - Juan Díaz (Píldoras Informáticas)

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Remove Resource(s)

### Checklist:
- [X] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [X] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
these links worked for me

**Comment by dbrn** [comment]
None of them works for me. They all give 404 NOT FOUND as status

**Comment by eshellman** [comment]
@dbrn That's odd! Links still work for me. Maybe correspond with the website owner to debug the problem? (I'm using Chrome 85.0.4183.121, in case it's a browser issue.)

**Comment by dbrn** [comment]
Yeah, you are right. It works on my mobile phone. Probably it's something that has to do with my home DNS.
I think it's better to close this pr :)

**Pull request closed without merging**
