### PR TITLE
Add Koodiaapinen

### PR DESCRIPTION
**Pull request by endormi**
## What does this PR do?
Add Resource(s) 

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
not really a "course" is it? Also, no need to remove trailing slashes except for website urls

**Comment by endormi** [comment]
I'd say that it is, this is a koodiaapinen-mooc course. I'm not sure if it's better to just have mooc and not include this one, but I personally think it would be good to add.

**Comment by eshellman** [comment]
could you revert the slashes on the other links?

**Comment by endormi** [comment]
Yeah, will do.

**Comment by eshellman** [comment]
please resolve conflicts

**Comment by endormi** [comment]
Resolved.

**Pull request merged**
