### PR TITLE
Update free-courses-en.md added a machine learning playlist

### PR DESCRIPTION
**Pull request by yuvrajverma25**
## What does this PR do?
Added a Machine Learning Playlist 

### Description
This is a beginner friendly machine learning playlist.

### Why is this valuable (or not)?
It is very valuable to the a beginner level machine learning learner.

### How do we know it's really free?
Yes, it is a playlist of youtube which is free for all.

## Checklist:
- [☑️ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ☑️] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [☑️ ] Include author(s) and platform where appropriate.
- [☑️ ] Put lists in alphabetical order, correct spacing.
- [☑️ ] Add needed indications (PDF, access notes, under construction).
- [☑️ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by sohansai — COMMENTED** [review]
Consider moving the course to "courses/free-courses-hi.md" since it's in Hindi. Also, replace the single video link with a playlist link.

**Comment by sohansai** [comment]
Also check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

**Comment by Ajay-singh1** [comment]
Fix the linter errors

**Comment by eshellman** [comment]
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

**Comment by eshellman** [comment]
not english, not long enough to be a course

**Pull request closed without merging**
