### PR TITLE
add zh_TW (traditional chinese) md

### PR DESCRIPTION
**Pull request by Billy4195**
This is translate from free-programming-books-zh.md

### CODE REVIEW

**Comment by Billy4195** [comment]
Does anyone know how to fix "Alphabetical ordering" error ??

**Comment by vhf** [comment]
Is this translation necessary?

`free-programming-books-zh.md` is simplified chinese, right? How many people know traditional chinese but cannot read simplified chinese?

**Comment by Billy4195** [comment]
For those who are used to use traditional chinese will be convenient to read this translation.

Because there are still some difference between simplified and traditional chinese can't be translated easily.

**Comment by eshellman** [comment]
@Billy4195 Easiest way to fix the ordering is to use the unicode collation of the headings- bopomofu or another chinese-native collation is not something travis will know about.

@vhf This appears to be a zh-TW transliteration of the headings, not a list of zh-TW resources. I think that breaks the pattern used for other languages; but then putting both simplified and traditional chinese resources in the same file already breaks the pattern. So I suggest to add traditional headings in parens in the zh file where the traditional characters differ from simplified. This will make a combined resource easier to maintain. (note that traditional characters are also used in Hong Kong).

**Comment by vhf** [comment]
Thanks for your inputs @Billy4195 and @eshellman . I quite like the idea of adding the traditional Chinese translation of the headings in parens.

**Comment by eshellman** [comment]
Should we leave this open?

**Comment by eshellman** [comment]
I have created a help-requested issue #2384  to replace this PR.

**Pull request closed without merging**
