### PR TITLE
Update free-courses-en.md

### PR DESCRIPTION
**Pull request by AkashMani1**
Harvard University:CS50's Introduction to Artificial Intelligence with Python on EDx

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by AkashMani1** [comment]
Add Latest Harvard University: CS50's Introduction to Artificial Intelligence with Python on EDx

**Comment by Thenlie** [comment]
I believe this resource already exists. https://github.com/EbookFoundation/free-programming-books/blob/main/courses/free-courses-en.md?plain=1#L242

**Comment by AkashMani1** [comment]
This i latest one

**Comment by Thenlie** [comment]
> This i latest one

The link I shared links to this same edX site however it is the actual course material. Going to https://cs50.harvard.edu/ai/ will redirect to the most up to date course and you can then go to edX from there if you want.

**Pull request closed without merging**
