### PR TITLE
added competitive programming book and problems

### PR DESCRIPTION
**Pull request by dhruvbatra810**
## What does this PR do?
Add Resource(s)

### Description 
added Competitive Programmer's Handbook for beginner( PDF) by Antti Laaksonen (https://codeforces.com/profile/pllk) and  beginner to advance level problems (sheet)

### Why is this valuable (or not)
they are beginner friendly and easy to understand 

### How do we know it's really free?
for book it is a pdf link and sheets are available on authors youtube channel

### For book lists, is it a book?
yes

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
please fix linter errors

**Comment by dhruvbatra810** [comment]
i had fixed the linter errors and  sorry for the above mess, thanks

**Comment by eshellman** [comment]
please don't create a category for a single book.

**Comment by bigbirdone** [comment]
python

在 2020-10-12 10:12:59，"Eric Hellman" <notifications@github.com> 写道：


please don't create a category for a single book.

**Pull request closed without merging**
