### PR TITLE
Added Data Structures Topic to the Cheat Sheets section and added a cheat sheet for Complexities.

### PR DESCRIPTION
**Pull request by yogan-gopi**
## What does this PR do?
I've added **Data Structures** topic in the Cheat Sheet section and also added a cheat sheet for **Complexities** (Time and Space).

### Why is this valuable (or not)?
It is valuable as Data Structures play a vital role in every part of Programming.

### How do we know it's really free?
Yes, it is free.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by yogan-gopi** [comment]
Closes #7646

**Comment by eshellman** [comment]
seems like the category should be algorithms or something

**Comment by yogan-gopi** [comment]
> seems like the category should be algorithms or something

I'll better make it **Data Structures & Algorithms (DSA)**, a common and popular term.

**Comment by yogan-gopi** [comment]
Updated the Pull Request.

**Pull request closed without merging**
