### PR TITLE
feat: Update free-courses-en.md - adding resource for C++ interview prep

### PR DESCRIPTION
**Pull request by Ayu21815**
## What does this PR do?
Add resource(s)
### Description
This PR adds a valuable C++ resource by Keerti Purswani, that covers essential C++ interview questions for freshers.
### How do we know it's really free?
This is a youtube playlist available for free.
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Ayu21815** [comment]
@sohansai @eshellman Please review the PR and approve the changes. Thank you!

**Review by sohansai — COMMENTED** [review]
Use the original title from the resource and avoid inventing new ones.

**Comment by Ayu21815** [comment]
> Use the original title from the resource and avoid inventing new ones.



> Use the original title from the resource and avoid inventing new ones.

The original title only has c++, so added more description to it. Please merge it. Thanks

**Comment by Thenlie** [comment]
> The original title only has c++, so added more description to it. Please merge it. Thanks

Be that as it may, I don't think we should be creating new titles for other's work.

**Comment by eshellman** [comment]
If you put it in the "Problems Sets" category in the problem-sets-competitive-programming list, the extra stuff in the title wouldn't be needed.

**Comment by khullarkushagra** [comment]
Added the resource in "Problems Sets" category in the problem-sets-competitive-programming list as per @eshellman's comment. Kindly review the PR. Thanks!

**Comment by Ayu21815** [comment]
Added the resource in "Problems Sets" category in the problem-sets-competitive-programming list as per @eshellman's comment. Kindly review the PR @sohansai @Thenlie @eshellman. Thanks!

**Review by Thenlie — APPROVED** [review]

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by Ayu21815** [comment]
Please add hacktoberfest label here! @sohansai @Thenlie @eshellman . Thanks

**Comment by eshellman** [comment]
not needed - entire repo has the label

**Pull request merged**
