### PR TITLE
Added cloud computing interactive tutorials

### PR DESCRIPTION
**Pull request by tinabme**
## What does this PR do?
Add Resource(s)

### Why is this valuable
Cloud Computing a new and popular way of programming without the need for traditional devOps and server farms.

### How do we know it's really free?
All of the beginning courses are free, and give users a great head-start on learning.

### For book lists, is it a book?
No these are interactive tutorials.

### Checklist:
- [√] Not a duplicate
- [√] Included author(s) if appropriate
- [√] Lists are in alphabetical order
- [√] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
These look really useful. However:
1. When I followed your EC2 link, I got non-free results. 
2. Would prefer links that went straight to individual courses. Otherwise maybe just have a single link to the site with the free filter turned on. 
3. since folks probably aren't familiar with quiklab, a notation '(registration required)' should be added.

**Comment by eshellman** [comment]
Perhaps I don't understand something, but it looks like only the s3 course is free on quiklabs. The EC2 class is 1 credit, and the minimum spend is $8 for 8 credits.

**Comment by tinabme** [comment]
> Perhaps I don't understand something, but it looks like only the s3 course is free on quiklabs. The EC2 class is 1 credit, and the minimum spend is $8 for 8 credits.

You are correct, I misunderstood the intro courses to be free, sorry. Now all of the courses listed are free.

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
