### PR TITLE
Added new embedded section in polish language

### PR DESCRIPTION
**Pull request by dariuszzbyrad**
## What does this PR do?
Add resources

### Description
I've aded two resources for learning embedded system, arduino and STM32.

### Why is this valuable (or not)?
In Poland these are some of the most popular courses for learning embedded system (arduino and STM32).

### How do we know it's really free?
From course side (STM32):
"Ten kurs programowania STM32L4 powstał w wyniku naszej współpracy z firmą STMicroelectronics. Oficjalna współpraca z producentem tych mikrokontrolerów umożliwiła nam szybszą realizację projektu i bezpłatne udostępnienie całego kursu."

"This STM32L4 programming course is the result of our cooperation with STMicroelectronics. **The official cooperation with the manufacturer of these microcontrollers allowed us to complete the project faster and provide the entire course for free**."

And (Arduino):
"Było już dużo książek tego typu, oraz innych kursów. Ten będzie inny, lepszy, bo nasz i zupełnie darmowy!"

"There have been many books of this type, and other courses. This one will be different, better, because it's ours and **completely free**!"

### For book lists, is it a book? For course lists, is it a course? etc.
Yes, it's online course.

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [X] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction).
- [X] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by Ajay-singh1 — CHANGES_REQUESTED** [review]
LGTM!

**Comment by eshellman** [comment]
It's usually not helpful to add a category for a single resource. So here, just add a single "embedded" category for the two resources. Thanks!

**Comment by dariuszzbyrad** [comment]
> It's usually not helpful to add a category for a single resource. So here, just add a single "embedded" category for the two resources. Thanks!

Fixed, thanks for tip

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
