### PR TITLE
Adding Git & Github tutorial to the English (screencast)

### PR DESCRIPTION
**Pull request by ShankyJS**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) 

### Description 

This **screencast** was performed by _ShankyJS_, and does a walk-through the main concepts of Git and also explains Github and the relation between Git  and Github.

### Why is this valuable (or not)?

Is valuable because this is a 2 hours video with free-content about Git and Github.

### How do we know it's really free?

It's a public video on youtube without ads :+1: 

### Checklist:
- [X] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [X] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by ShankyJS** [comment]
Finally, all checks passed, the screencast added was done by me :raised_hands: please merge :+1:

**Comment by eshellman** [comment]
For youtube, we prefer "playlist" links and the name of the producer/creator.

**Comment by ShankyJS** [comment]
Hi @eshellman, this youtube content is a screencast of 2 hours in the same link, I have added a new commit adding the author to the name of the content.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
