### PR TITLE
added more links to information security

### PR DESCRIPTION
**Pull request by theamanrawat**
## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by kree666** [comment]
@theamanrawat It looks like the build failed because: 
The links in the information security section is not in the correct alphabetical order.
You need to remove the slash at the end of the URL for both the https://inctf.in and the https://ctf.hacker101.com

**Comment by theamanrawat** [comment]
I've removed slash at the end Now You can merge

**Comment by kree666** [comment]
@theamanrawat It looks like the build failed because:
The links in the information security section are not in the correct alphabetical order.

For more information on the formatting and guidelines, check the contribution guide (CONTRIBUTING.md). Or, you can also look at the failed check in Travis CI to see the details of where linting has failed.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
