### PR TITLE
Added D3.js courses

### PR DESCRIPTION
**Pull request by cyeehan**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add resources.

### Description 
Added resources: 

- Data Visualization with D3.js: Full Tutorial Course 2019 (https://www.youtube.com/watch?v=_8V5o2UHG0E&t=23737s)

- Learn the basics of data visualization with D3 (https://www.codecademy.com/learn/learn-d3)

### Why is this valuable (or not)?
It is valuable for whoever would like to learn data visualization with the JavaScript library.
### How do we know it's really free?
By accessing the 2 links provided.
### For book lists, is it a book? For course lists, is it a course? etc.
They are courses.
### Checklist:
- [Y] Not a duplicate
- [Y] Included author(s) if appropriate
- [Y] Lists are in alphabetical order
- [N] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Heads up! Where the pull request template has `* [ ]` you can replace the space with an `x` to make it a checked checkbox!

* [x] Like this!

It seems you've changed the table of contents from asterisks to hyphens.

It may be nice to change them back to maintain consistency with the rest of the repository.

**Comment by ecrax** [comment]
Some text editors with automatic formating like to do that, try to disable that.

In VisualStudio Code, there is a handy feature to only enable format for the parts of the documents you have changed or turn it off completely while you work on this file.

**Comment by cyeehan** [comment]
> Heads up! Where the pull request template has `* [ ]` you can replace the space with an `x` to make it a checked checkbox!
> 
> * [x]  Like this!
> 
> It seems you've changed the table of contents from asterisks to hyphens.
> 
> It may be nice to change them back to maintain consistency with the rest of the repository.



> Some text editors with automatic formating like to do that, try to disable that.
> 
> In VisualStudio Code, there is a handy feature to only enable format for the parts of the documents you have changed or turn it off completely while you work on this file.

I noticed that and have disabled it.

VS Code (Mac):
Preferences > Search "toc.updateOnSave" in settings > Disabled it > Done!

Anyway, thanks!

**Comment by ecrax** [comment]
> > Heads up! Where the pull request template has `* [ ]` you can replace the space with an `x` to make it a checked checkbox!
> > 
> > * [x]   Like this!
> > 
> > It seems you've changed the table of contents from asterisks to hyphens.
> > It may be nice to change them back to maintain consistency with the rest of the repository.
> 
> > Some text editors with automatic formating like to do that, try to disable that.
> > In VisualStudio Code, there is a handy feature to only enable format for the parts of the documents you have changed or turn it off completely while you work on this file.
> 
> I noticed that and have disabled it.
> 
> VS Code (Mac):
> Preferences > Search "toc.updateOnSave" in settings > Disable it > Done!
> 
> Anyway, thanks!

You are very welcome!

**Comment by eshellman** [comment]
Be sure to check the output of Travis-CI for linter errors. Alphabetical order and spacing are the most common problems.

**Pull request closed without merging**
