### PR TITLE
Guia Foca Linux PT BR

### PR DESCRIPTION
**Pull request by ThalesVItal**
## What does this PR do?
Add Resource(s)

### Description 
I added a link for a free linux guides in portuguese.

### Why is this valuable (or not)
Linux is a vastly used operating system.This guide has 4 editions for all levels of knowledge in linux that is why i added it.

### How do we know it's really free?
The author is making available the guides in his official site.

### For book lists, is it a book?
Yes.

### Checklist:
- [x] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [X] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by ThalesVItal** [comment]
Why this pull request don't passed?

**Comment by eshellman** [comment]
the lists need to be in alphabetical order. Check the output of the linter on Travis-CI

**Comment by ThalesVItal** [comment]
Thanks

**Comment by eshellman** [comment]
Welcome to free-programming-books!

**Pull request merged**
