### PR TITLE
added operating system cheat sheet

### PR DESCRIPTION
**Pull request by abhay57**
## What does this PR do?
Add resource(s) 

### Description
It contains all the main topics in operating system in precise language.

### Why is this valuable (or not)?
It is highly valuable as it contains technical interview oriented topics and notes.

### How do we know it's really free?
It's a downloadable PDF made available by a youtube channel.

## Checklist:
- [*] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ *] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [* ] Include author(s) and platform where appropriate.
- [* ] Put lists in alphabetical order, correct spacing.
- [* ] Add needed indications (PDF, access notes, under construction).
- [* ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by ThakareSakshi** [comment]
remove line 328 . Adding extra blank line is creating issue

**Comment by 3R1Dev** [comment]
Please note that due to the guidelines Google drive and other file sharing sites are not accepted.

Do you have the original link? Perhaps directly from the author?

**Comment by abhay57** [comment]
@3R1Dev Actually the original documents provided by the author are discrete i.e. those are lecture wise notes. I can create a document that will contain links to the author's documents. does that work?

**Comment by abhay57** [comment]
@ThakareSakshi sure

**Pull request closed without merging**
