### PR TITLE
add french c++ course

### PR DESCRIPTION
**Pull request by x0rld**
## What does this PR do?
Add index

### Description
It's a modern course for c++
### Why is this valuable (or not)?
There is almost no good C++ course in french
### How do we know it's really free?
it's available on the website
### For book lists, is it a book? For course lists, is it a course? etc.
it's a website
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
add to index?

**Comment by eshellman** [comment]
when you add a section, you also need to add to the page index

**Review by davorpa — COMMENTED** [review]
~The index listing change has not been applied yet~

~See https://github.com/EbookFoundation/free-programming-books/pull/6181#pullrequestreview-778014427~

--- 

Resolved at https://github.com/EbookFoundation/free-programming-books/pull/6181/commits/0956528511e388e40410de808e30cf17e8c2c7a7

**Review by davorpa — CHANGES_REQUESTED** [review]
> add c++ to index

@x0rld, could you resolve this so we can merge PR?

> when you add a section, you also need to add to the page index
> 
> https://github.com/EbookFoundation/free-programming-books/blob/d21b167a3728ef8f21c565b49c0d81e3f4a52dc2/courses/free-courses-fr.md#L5-L7
> 
> ```markdown
> * [C](#c)
> * [C#](#c-sharp)
> * [C++](#cpp)
> * [Git](#git)
> ```

**Review by davorpa — APPROVED** [review]
:+1:  format ok. Resolved at https://github.com/EbookFoundation/free-programming-books/pull/6181/commits/0956528511e388e40410de808e30cf17e8c2c7a7

---

:question: Course or book / guide / tutorial?

No related real "complementary" books that I could see. Also has TOC

> Most of the english tutorials are in `books-*.md` listing :thinking:

**Comment by x0rld** [comment]
it's a course but it can be download as a pdf 🤔

**Pull request merged**
