### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by GAUTAMMANAK1**
I've removed the extra square brackets that were around the website URL, which were causing the issue. With this corrected code, the badge should work as expected, and when clicked, it will take you to the website provided in the URL.

It seems like you want to create a clickable badge that redirects to a website when clicked. However, there's a small issue with the provided Markdown code. You can correct it by using the following Markdown code:

### CODE REVIEW

**Comment by eshellman** [comment]
please describe how to repproduce the bug

**Comment by GAUTAMMANAK1** [comment]
when we scollr the link then all text hover i will change the this bug 
current only blue line hover

**Comment by 3R1Dev** [comment]
There are some issues in the pushed changes, listed as follows:

1. On line 13 the text for the ebookfoundation.github.io is being removed and replaced with "Website"
2. line 25 has an unnecessary space added after the URL
3. Line 144 was completely removed

I don't see any issues with the current markdown as it is on the present README. Links work, hover over links works without issue. I dont see the reason for the changes proposed or any bugs.

**Comment by eshellman** [comment]
couldn't reproduce the issue

**Comment by eshellman** [comment]
thanks @3R1Dev for help

**Pull request closed without merging**
