### PR TITLE
Adding courses from Kaggle

### PR DESCRIPTION
**Pull request by nanachansan**
## What does this PR do?
Add Resource(s)

### Description 
A few courses from Kaggle and two screencasts from Programação Dinâmica
### Why is this valuable (or not)
Kaggle's a free platform for Data Science competitions that has great courses for a few entry-level skills in Data Science. Programação Dinâmica is a Youtube channel with multiple resources mostly in Python and Data Science.

### How do we know it's really free?
It says on the website, but I can also attest to it, since I've studied with their materials. Also, Programação Dinâmica's courses are free on Youtube.

### Checklist:
- [x] Not a duplicate
- [x ] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
for kaggle, add instructor and optionally the platform.
for youtube, we prefer playlist links

**Comment by nanachansan** [comment]
no problem, @eshellman! Just updated it!

**Comment by eshellman** [comment]
for kaggle, add instructor and optionally the platform.

**Comment by nanachansan** [comment]
@eshellman hi, so kaggle is the platform for the course itself, should i add it in?

**Comment by bigbirdone** [comment]
收到

在 2020-10-12 04:34:42，"Eric Hellman" <notifications@github.com> 写道：


for kaggle, add instructor and optionally the platform.

**Comment by eshellman** [comment]
yes

**Pull request closed without merging**
