### PR TITLE
#hacktoberfest "Laravel Portugal Live" Portuguese Podcast (Fixed filename) and added Ubuntu Portugal podcast

### PR DESCRIPTION
**Pull request by joseborges**

### CODE REVIEW

**Comment by joseborges** [comment]
Now this file should be ok, to merge.

**Comment by SethiPandi** [comment]
Please remove trailing slashes from both URLs.

Also instead of writing a description, could you please instead just write if it's a podcast or screencast, along with an author if possible. You can see examples by looking at every other `free-podcasts-screencasts-*` document.
Especially if the description is going to be a copy/paste anyway, as all content is copyrighted, including content on webpages. I see nothing on the page that says the content of the webpage can be redistributed. If people want more information they can check out the page themselves!

**Comment by joseborges** [comment]
Done as requested.

**Comment by eshellman** [comment]
Yes, our lists don't include more than a word or two of description - it's the job or the creator to have a good title. So "Podcast Ubuntu Portugal" is the title of the podcast. We often include the creator names as well.

**Comment by eshellman** [comment]
don't forget to add a link to your new page from README.md

**Comment by joseborges** [comment]
> Yes, our lists don't include more than a word or two of description - it's the job or the creator to have a good title. So "Podcast Ubuntu Portugal" is the title of the podcast. We often include the creator names as well.

All authors are listed, for both podcasts.

**Comment by joseborges** [comment]
> don't forget to add a link to your new page from README.md

Also updated 😄

**Comment by joseborges** [comment]
Maybe all is good now?

**Comment by SethiPandi** [comment]
There should be two blank lines above a new section or subsection, in this case, above the Ubuntu heading.

I think it should be cool after that.

**Comment by joseborges** [comment]
> There should be two blank lines above a new section or subsection, in this case, above the Ubuntu heading.
> 
> I think it might be cool after that? Still wouldn't be 100% consistent with the other podcasts documents though.

What's inconsistent?

**Comment by SethiPandi** [comment]
> > There should be two blank lines above a new section or subsection, in this case, above the Ubuntu heading.
> > I think it might be cool after that? Still wouldn't be 100% consistent with the other podcasts documents though.
> 
> What's inconsistent?

An example from the English document:

> The EmberMap Podcast - Sam Selikoff and Ryan Toronto (podcast)

`{Title} - {Authors} (podcast/screencast)`

I don't know if this format is strictly a rule is all, hence I'm not going to say anything is _wrong_ right now unless @eshellman confirms it is, but just that it's not 100% identical in format to other documents is all I wanted to make note of.

**Comment by joseborges** [comment]
> > > There should be two blank lines above a new section or subsection, in this case, above the Ubuntu heading.
> > > I think it might be cool after that? Still wouldn't be 100% consistent with the other podcasts documents though.
> > 
> > 
> > What's inconsistent?
> 
> An example from the English document:
> 
> > The EmberMap Podcast - Sam Selikoff and Ryan Toronto (podcast)
> 
> `{Title} - {Authors} (podcast/screencast)`
> 
> I don't know if this format is strictly a rule is all, hence I'm not going to say anything is _wrong_ right now unless @eshellman confirms it is, but just that it's not 100% identical in format to other documents is all I wanted to make note of.

Right, fixed now.

**Pull request merged**
