### PR TITLE
Point codepen.io link to https

### PR DESCRIPTION
**Pull request by cherouvim**
## What does this PR do?
Improve Repo

### CODE REVIEW

**Comment by zhongjiajie** [comment]
LGTM, but why https://codepen.io have to resources in single file

**Comment by cherouvim** [comment]
I suppose because it's a playground both for CSS and JS, so it's listed twice.

**Comment by zhongjiajie** [comment]
> I suppose because it's a playground both for CSS and JS, so it's listed twice.

Ok

**Comment by eshellman** [comment]
@cherouvim welcome to free-programming-books

**Pull request merged**
