### PR TITLE
Added cheatsheets for SQL and Python

### PR DESCRIPTION
**Pull request by verdantfire**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) 

### Description 
I have started the SQL sub heading and added two resources to it in addition to another resource under Python:
1. Python Regex
2. MySQL 
3. PostgreSQL

### How do we know it's really free?
Direct links are provided with no paywalls or signups.
### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Could you please ensure that all lists and categories are in alphabetical order?

The SQL section should be underneath Python!

You can get more guidance on the formatting and conventions of this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).

**Comment by verdantfire** [comment]
> 
> 
> Could you please ensure that all lists and categories are in alphabetical order?
> 
> The SQL section should be underneath Python!
> 
> You can get more guidance on the formatting and conventions of this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).

Yes, I missed that earlier. Took care of it in the last commit free-programming-books@cc2d1f7

**Comment by SethiPandi** [comment]
Sorry, @verdantfire!
I was referring to the actual contents:

image

**Comment by verdantfire** [comment]
My apologies, fixed it now.

**Comment by eshellman** [comment]
this is going to be so useful!

**Comment by verdantfire** [comment]
Looking forward to use these resources and keep contributing as I encounter new cheatsheets!

**Pull request merged**
