### PR TITLE
Added a new book to Python section of free-programming-books-tr.md

### PR DESCRIPTION
**Pull request by tekrei**
Added a new book link

### CODE REVIEW

**Comment by eshellman** [comment]
Congratulations on the translation! Great to see this. Two nits to fix:
1. lists need to be in alphabetical order
2. could you add the authors in the listing?

**Comment by tekrei** [comment]
Thank you @eshellman, I updated order but didn't see any example of author listing, so I left without authors. Still would you like me to add authors?

**Comment by eshellman** [comment]
Thanks! Take a look at the english list for examples of adding author names, also, see issue #2383 for motivation.

**Comment by tekrei** [comment]
Done. I added authors to the listing of the book.

Thanks.

**Comment by eshellman** [comment]
Outstanding!

**Pull request merged**
