### PR TITLE
Add lua ebook.

### PR DESCRIPTION
**Pull request by Samuel-de-Oliveira**
I found a Lua Ebook created by Rip tutorial.

I put the link of download in official site of them.

### CODE REVIEW

**Comment by eshellman** [comment]
Please see #6153 for our practice regarding riptutorial links.

**Comment by eshellman** [comment]
please add the credit " Compiled from StackOverflow Documentation"
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

**Comment by Samuel-de-Oliveira** [comment]
Like this?

**Comment by eshellman** [comment]
yes. need check the linter

**Comment by eshellman** [comment]
missing pdf notation

**Comment by Samuel-de-Oliveira** [comment]
I really don't find any error in file, did you mean this?

If you show me the error will help me a lot.

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
