### PR TITLE
Add iOS Course from Harvard

### PR DESCRIPTION
**Pull request by Larissagilliane**
## What does this PR do?
This PR adds a free course to teach iOS basis made by Harvard

### Description 
This is a track course about iOS from Harvard.

### Why is this valuable (or not)?
This is a course made by Harvard teaching iOS.

### How do we know it's really free?
At the 'CS50 Certificate' section you can read that you only need to pay for the certificate but the course is Free.

### For book lists, is it a book? For course lists, is it a course? etc.
This is a course.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
see #4600

**Comment by eshellman** [comment]
see #4601

**Comment by Larissagilliane** [comment]
@eshellman  I want to add the same commentary as in #4600 .

**Comment by Larissagilliane** [comment]
@eshellman  I updated the course with the youtube playlist and the correct title. What do you think?

**Pull request merged**
