### PR TITLE
 Improved Readme.md . Changes aim to improve the formatting, clarify steps, and ensure consistency throughout your README

### PR DESCRIPTION
**Pull request by vinayaksoni1729**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by vinayaksoni1729** [comment]
I made the following improvements and changes to the code:

Added a title and a badge with a description to the top of the document.
Improved the formatting for alignment and layout.
Updated the search form to be centered and made it more visually appealing.
Added badges for Hacktoberfest 2023, which are becoming popular in open-source repositories.
Improved the alignment and formatting of various shields (badges).
Improved alignment and formatting of contributor-related badges.
Added a section on "How to Share" with social media sharing links.
Aligned the badges related to issues, pull requests, and help wanted sections.
Improved the alignment and formatting of the list of programming resources, making it more structured and organized.
Added anchor links for easy navigation.
Improved the formatting and layout of the "Translations" section.
These changes aim to enhance the visual appeal and organization of the code.

**Review by sohansai — COMMENTED** [review]
I believe the current README.md is already clear and concise. The existing content has been well-received and holds value, and some of the elements you've removed are essential for the project. Some of the changes you made are not all considered necessary.

**Comment by vinayaksoni1729** [comment]
@sohansai 

I made the following improvements and changes to the code:

Added a title and a badge with a description to the top of the document.
Improved the formatting for alignment and layout.
Updated the search form to be centered and made it more visually appealing.
Added badges for Hacktoberfest 2023, which are becoming popular in open-source repositories.
Improved the alignment and formatting of various shields (badges).
Improved alignment and formatting of contributor-related badges.
Added a section on "How to Share" with social media sharing links.
Aligned the badges related to issues, pull requests, and help wanted sections.
Improved the alignment and formatting of the list of programming resources, making it more structured and organized.
Added anchor links for easy navigation.
Improved the formatting and layout of the "Translations" section.
These changes aim to enhance the visual appeal and organization of the code.

**Comment by eshellman** [comment]
not merging

**Pull request closed without merging**
