### PR TITLE
Added Web Almanac

### PR DESCRIPTION
**Pull request by PraveenPal4232**
Added Web Almanac to Web Development

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
It's not helpful to add a category for a single resource. Try to find another category- probably in 'language agnostic'. we probably have a hundred "web development" books.

**Comment by PraveenPal4232** [comment]
Yes @eshellman it makes sense, I created a PR #4770 earlier in `free-courses-en.md`, but then @SethiPandi suggested to add this in `free-programming-books.md` that's why I added this here.

I think we should add it here and we can add more resources in the future. Let me know what we can do about this :)

**Comment by eshellman** [comment]
yes, add it in books, but use an existing category.

**Comment by PraveenPal4232** [comment]
Ok @eshellman, can you suggest a category for this?

**Comment by eshellman** [comment]
"Misc"

**Comment by PraveenPal4232** [comment]
Ok, Thanks @eshellman, I'll do that.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
