### PR TITLE
Add RxJS YouTube playlist in English & Hindi free course

### PR DESCRIPTION
**Pull request by Xyroid**
## What does this PR do?
Add resource(s)

### Description
RxJS is a library for reactive programming using Observables, to make it easier to compose asynchronous or callback-based code
### Why is this valuable (or not)?
It's a Reactive Extensions For JavaScript. It can be used by any JavaScript framework like Angular, React, NodeJS, etc.
### How do we know it's really free?
They are public YouTube video playlist, hence it's free.
### For book lists, is it a book? For course lists, is it a course? etc.
Course(s).
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
It's usually not helpful to add a category for a single resource. Try to find another category (maybe the javascript section), or see if there are other books in our lists that would fit into your category.

**Comment by Xyroid** [comment]
@eshellman I removed the sub-category of RxJS and merged course into JavaScript section.

**Review by davorpa — APPROVED** [review]
### Ready to merge :fireworks: :tada:

Have you a warm welcome :cara_abrazando: to `free-programming-books`

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by Xyroid** [comment]
@eshellman request you to label the PR with `hacktoberfest-accepted`. Thanks!

**Pull request merged**
