### PR TITLE
Adding a MATLAB book

### PR DESCRIPTION
**Pull request by ghleite**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ X ] Not a duplicate
- [ X ] Included author(s) if appropriate
- [ X ] Lists are in alphabetical order
- [ X ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
please use same format and notations as for other goalkicker books

**Comment by ghleite** [comment]
> please use same format and notations as for other goalkicker books

What I need to change in this format I made? I thought that was equal as asked in the guide

**Comment by eshellman** [comment]
we try for consistency in how we present listings. most of our goalkicker listings look like this:
`* [Spring Framework Notes for Professionals](https://books.goalkicker.com/SpringFrameworkBook) - Compiled from StackOverflow documentation` 
This give readers an idea of what to expect, and provides proper attribution.

**Comment by ghleite** [comment]
I made the fix to respect the goalkicker pattern

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
