### PR TITLE
Added ABAP as language as well as a first resource

### PR DESCRIPTION
**Pull request by jwigert**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s)

### Description 
Added ABAP as language as well as a first resource
### Why is this valuable (or not)?
It adds a new language and a resource
### How do we know it's really free?
The license is CC BY 3.0 according to the license file
### For book lists, is it a book? For course lists, is it a course? etc.
It is a book/style guide
### Checklist:
- [X] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [X] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Didn't we get rid of the "0" in the section headings?

**Comment by jwigert** [comment]
I removed the "0" and rearranged the content accordingly.

**Comment by eshellman** [comment]
linter is picky about spaces

**Comment by jwigert** [comment]
Now the linter seems happy. :-)

**Pull request merged**
