### PR TITLE
Add `Git Cookbook` by Dennis Kaarsemaker

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?
Add resource(s)

### Why is this valuable (or not)?

Extends the official Git book with tips and usefull advanced examples.

### How do we know it's really free?

All content is free distributable, perhaps cant be reproduced without author consent.

### For book lists, is it a book? For course lists, is it a course? etc.

it's a book hosted as webpages / blog

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by LorenzoQuiroz — APPROVED** [review]
LGTM; great addition!

**Comment by eshellman** [comment]
looks like a blog, not a book? For example,  no table of contents, just "tags".

**Review by CleanMachine1 — APPROVED** [review]

**Comment by CleanMachine1** [comment]
I have to agree, its more like a blog. However if we agree on the content of the website then LGTM.

**Comment by davorpa** [comment]
> looks more like a book if we link to the about page, don't you think?

I agree. Done at af9c931412423fdf1cf297c9afdce908a3852e26

**Pull request merged**
