### PR TITLE
Added a new course on Linux command line

### PR DESCRIPTION
**Pull request by ch-a-nd-a-n**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by ch-a-nd-a-n** [comment]
Sir, thank you for your concern. I have tried for more than 5 pull
requests, but I am unable to get to verify. The same error pops up every
time " TARVIS CI error ". Kindly take a look at my submissions and help me
get through it.

**Comment by eshellman** [comment]
be sure to check the output of Travis-CI for linter errors
For youtube, we prefer "playlist" links and the name of the producer/creator
please resolve conflicts..

**Comment by ch-a-nd-a-n** [comment]
Thanks for your email sir. I will try again.

**Comment by eshellman** [comment]
alphabetize!
please resolve conflicts
Be sure to check the output of Travis-CI for linter errors. Alphabetical order and spacing are the most common problems
For youtube, we prefer "playlist" links and the name of the producer/creator...

**Comment by kadhirash** [comment]
Closing since the correct playlist link is already added from a different PR.

**Pull request closed without merging**
