### PR TITLE
add CTFtime to  problem-sets-competitive-programming.md

### PR DESCRIPTION
**Pull request by rndd-AK**
third attempt of doing it

CTFtime is useful resource where you can find examples of real problems in information security. And info about ctf challenges that are going to happen.

### CODE REVIEW

**Comment by rndd-AK** [comment]
realized  problem with formatting, be69b10 branch is formatted correctly

**Comment by eshellman** [comment]
Thanks for you persistence! Could you also add a heading to the index?

**Comment by rndd-AK** [comment]
excuse me, but really don't understand what "add a heading to the index" means

**Comment by eshellman** [comment]
You've added a section. At the top of the file is a list of links to the sections.

**Comment by rndd-AK** [comment]
done

**Comment by eshellman** [comment]
beautiful!

**Pull request merged**
