### PR TITLE
Update problem-sets-competitive-programming.md

### PR DESCRIPTION
**Pull request by ritik-369**
Added a great resource freely available for learning algorithms it is a very popular site for learning competitive programming.

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

### Description
Site for learning competitive programming

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by VinayAmbatkar — CHANGES_REQUESTED** [review]
I want to add n-queen Problem at  -sets-competitive-programming.md

**Comment by ritik-369** [comment]
may i add this?

**Review by LuigiImVector — COMMENTED** [review]
I don't think that "Problem Sets & Competitive Programming" is the correct category, maybe "Books" is more appropriate, wait for another review

**Comment by eshellman** [comment]
I think it's fine for competitive programming

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
