### PR TITLE
Added An Application Development Course

### PR DESCRIPTION
**Pull request by Ajay-singh1**
Co-authored by: Eric Hellman <eric@hellman.net>

## What does this PR do?
Add resource(s) 

### Description
Added an android Application development course
### Why is this valuable (or not)?
Yes
### How do we know it's really free?
Youtube
### For book lists, is it a book? For course lists, is it a course? etc.
It is a course
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
why is this in Android?

**Comment by Ajay-singh1** [comment]
@eshellman Because it teaches building android applications.

**Comment by Thenlie** [comment]
> https://www.youtube.com/playlist?list=PLyqSpQzTE6M_0VfzgFbvUleae8SVonoHb

Are we sure about this? I  see a section on HTML and CSS.

**Comment by Thenlie** [comment]
> @eshellman Because it teaches building android applications.

Are we sure about this? I see a section on HTML and CSS.

**Comment by eshellman** [comment]
> @eshellman Because it teaches building android applications.

where?

**Comment by Ajay-singh1** [comment]
@eshellman Let me check and place it in a proper section.

**Pull request closed without merging**
