### PR TITLE
Add the german translation of "A byte of Python"

### PR DESCRIPTION
**Pull request by ph1p**
## What does this PR do?
This PR adds the book "A byte of Python"

### Why is this valuable (or not)?
This is a good book for Python beginners. It is recommended by the opencv community for example.

### How do we know it's really free?
Watch license section [https://python.swaroopch.com/](https://python.swaroopch.com/).
> This book is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
It seems to me that https://open.umn.edu/opentextbooks/textbooks/581 might be a better source for the book?

**Comment by ph1p** [comment]
Hi @SethiPandi sure! Thank you!
I got my link by visiting https://python.swaroopch.com/translations.html > scroll to german > click http://cito.github.io/byte_of_python/ > click PDF-Format, but yours looks great and not so "scammy" like sourceforge.

**Comment by ph1p** [comment]
Sorry I completely missed that your source was in English, too :D

**Comment by ph1p** [comment]
Have added the german source again @SethiPandi

**Comment by eshellman** [comment]
I'm a fan of the book.
Thanks, and welcome to free-programming-books!

**Pull request merged**
