### PR TITLE
Add books in Latvian

### PR DESCRIPTION
**Pull request by klappscheinwerfer**
## What does this PR do?
Add resource(s)

### Description

Added 2 books in Latvian by Jānis Zuters

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by davorpa** [comment]
Nice!

File locale is right: https://www.localeplanet.com/icu/lv/index.html

**Review by davorpa — CHANGES_REQUESTED** [review]
Needs register this new file at `README.md`

**Review by davorpa — APPROVED** [review]
It's enough now :rocket:

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books! We just need Lithuanian to have the Baltics covered.  (I was in Estonia when this PR was submitted)

**Pull request merged**
