### PR TITLE
added three Bangla courses of C and C++

### PR DESCRIPTION
**Pull request by FahimFBA**
## What does this PR do?
Add resources on two programming languages

### Description

I added three Bangla courses which are actually free (Youtube Playlist) and very much helpful.
2 of them were of C programming language and 1 of them was of C++ Programming Language.

### Why is this valuable (or not)?

I think that these 3 resources would be valuable to us because most of us, Bangladeshis crave for learning the basic of programming language through our mother tongue language, but as there are not that much helpful and decent resources of Bangla, we have to struggle a lot for that. I think that these three courses would be useful to them. I have the plan to add more of them later on.

### How do we know it's really free?

I'm providing the link of those three courses for checking the availability on free:
1. C Programming Bangla Tutorial Course - https://www.youtube.com/playlist?list=PLgH5QX0i9K3pCMBZcul1fta6UivHDbXvz
2. C - All you need to know - https://www.youtube.com/playlist?list=PL_XxuZqN0xVASsjyqiNzgjUWHbDkN2Scy
3. C++ Bangla Tutorial Course - https://www.youtube.com/playlist?list=PLgH5QX0i9K3q0ZKeXtF--CZ0PdH1sSbYL

### For book lists, is it a book? For course lists, is it a course? etc.

It contains three courses (Youtube Playlist). So, it's free.

### CODE REVIEW

**Comment by FahimFBA** [comment]
I closed the PR mistakenly earlier. I hope it won't cause any problems.

**Comment by eshellman** [comment]
Hi! These look like excellent additions, but it seems our linter is not looking at this file - it should have noticed that your C list is not in alphabetical order.

**Comment by FahimFBA** [comment]
@eshellman   Can you please check that now if I have been able to solve the problem or not?

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
