### PR TITLE
Added three books by Prakash B Hegade

### PR DESCRIPTION
**Pull request by v-hegde31**
## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Why is this valuable (or not)
The added books are valuable resources in computer science especially to absolute beginners. 
### How do we know it's really free?
They are direct links to the books, kept free by the author and can be verified on his Smashwords page linked below.
https://www.smashwords.com/profile/view/prakashbh
### For book lists, is it a book?
Yes. There are three books added in this PR. 
### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
use links like https://www.smashwords.com/books/view/639609 for smashwords as they give access to epub and mobi versions as well

**Comment by eshellman** [comment]
Are you the author?
Thanks, and welcome to free-programming-books!

**Comment by v-hegde31** [comment]
I am not the author of the books. They are by my college professor. 

Thanks for adding them!

**Comment by v-hegde31** [comment]
> Are you the author?
> Thanks, and welcome to free-programming-books!

No, they are by my professor at college. 
Thanks for the merge!

**Pull request merged**
