### PR TITLE
feat: Add "Back to top" links (to the TOC index)

### PR DESCRIPTION
**Pull request by BSA10**
## What does this PR do?
Improve repo

### Why is this valuable (or not)?
I think this helps the reader to look around the Index very quickly.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
see #5092 
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

**Comment by davorpa** [comment]
Implements part of the proposal 
- #5092

for english and arabic languages

**Comment by BSA10** [comment]
> Implements part of the proposal 
> 
> - #5092
> 
> 
> 
> for english and arabic languages

Do you want me to complete and add it to all the languages ?

**Comment by davorpa** [comment]
> > Implements part of the proposal
> > 
> > * [Improve big-file usability. Add "Return to Top" Links? #5092](https://github.com/EbookFoundation/free-programming-books/issues/5092)
> > 
> > for english and arabic languages
> 
> Do you want me to complete and add it to all the languages ?

:information_source:
- **I have the spanish listings done**. :wink:
- Some listings are a bit more advanced on #5603. Maybe there will be conflicts.

It looks really pretty although in some parts with few resources seems a bit dense.

image

I would wait to see what @SethFalco or @eshellman thinks about with the purpose of avoid do more work than necessary

**Comment by eshellman** [comment]
Thank you for giving us a demo of "back-to-index" links. It's really valuable to the discussion in #5092.
It's a really bad time to merge something like this, though, because it's guaranteed to create conflicts for every other PR, of which we have a lot because of Hacktoberfest.
The things I notice, thanks to this work are 
- significant overhead (and work for us) when new sections are created.
- seems like a lot of clutter with links after ever section
- each language will need localization

**Comment by BSA10** [comment]
> > > Implements part of the proposal
> > > 
> > > * [Improve big-file usability. Add "Return to Top" Links? #5092](https://github.com/EbookFoundation/free-programming-books/issues/5092)
> > > 
> > > for english and arabic languages
> > 
> > 
> > Do you want me to complete and add it to all the languages ?
> 
> ℹ️ Some feedback
> 
> * **I have the spanish listings done**. 😉
> * Some listings are a bit more advanced on [refactor(books): Split RE4B - Reverse Engineering For Beginners #5603](https://github.com/EbookFoundation/free-programming-books/pull/5603). Maybe there will be conflicts.
> * Also there are new listings/sections: [Add Hebrew online books #5592](https://github.com/EbookFoundation/free-programming-books/pull/5592) [Add Hebrew online courses #5590](https://github.com/EbookFoundation/free-programming-books/pull/5590) [Added Remix IDE to the Playgrounds file #5598](https://github.com/EbookFoundation/free-programming-books/pull/5598)
> 
> It looks really pretty although in some parts with few resources seems a bit dense.
> 
> image
> 
> I would wait to see what @SethFalco or @eshellman thinks about with the purpose of avoid do more work than necessary

So I have to cover all the advanced listings and the new section ?

And yes the in few resource will be some dense i thought about it but should we do?

**Comment by BSA10** [comment]
> Thank you for giving us a demo of "back-to-index" links. It's really valuable to the discussion in #5092. It's a really bad time to merge something like this, though, because it's guaranteed to create conflicts for every other PR, of which we have a lot because of Hacktoberfest. The things I notice, thanks to this work are
> 
> * significant overhead (and work for us) when new sections are created.
> * seems like a lot of clutter with links after ever section
> * each language will need localization

so, we put this aside and we have to figure out best solution for this. 
Is that what you refer to?

**Comment by BSA10** [comment]
> Thank you for giving us a demo of "back-to-index" links. It's really valuable to the discussion in #5092. It's a really bad time to merge something like this, though, because it's guaranteed to create conflicts for every other PR, of which we have a lot because of Hacktoberfest. The things I notice, thanks to this work are
> 
> * significant overhead (and work for us) when new sections are created.
> * seems like a lot of clutter with links after ever section
> * each language will need localization

So, we put this in

**Comment by davorpa** [comment]
I propose align crosslink to the right

**Comment by eshellman** [comment]
I think static "link to index" would be too hard to maintain. Maybe a javascript that works on the github pages version?
closing this for now. Very much appreciate the PR, though.

**Pull request closed without merging**
