### PR TITLE
Added Git and Github Tutorial

### PR DESCRIPTION
**Pull request by Ajay-singh1**
## What does this PR do?
Add resource(s) 

## For resources
Youtube
### Description
Added a complete youtube tutorial on git and github by kunal kushwaha.
### Why is this valuable (or not)?
Yes
### How do we know it's really free?
Available on youtube
### For book lists, is it a book? For course lists, is it a course? etc.
Tutorial
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by sohansai — COMMENTED** [review]
We prefer 'playlist' links for YouTube contributions

**Comment by Ajay-singh1** [comment]
@sohansai This is a Tutorial More than a hour length read contributing.md.

**Comment by Ajay-singh1** [comment]
> We prefer 'playlist' links for YouTube contributions

**Comment by Ajay-singh1** [comment]
@eshellman Kindly Review this PR and Merge it.

**Pull request merged**
