### PR TITLE
chore!: join `IDE and editors` into same section

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?
Add info | Improve repo

### Description

This homogenize the place where are organized the IDE and editors like Vim, Emacs, Visual Studio, Visual Studio Code, Eclipse, IntelliJ... into the same section.

Emacs Lisp is a language per sé. so apply and add some crosslinks #5535 in order to reference editors.

Moved books in `-langs.md` now are in `-subjects.md` since editors are language agnostic, I think.

At last but not least, complete this moved resources with author, formats and notes

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
I think this is a good move. Emacs lisp is a dialect of lisp, so probably belongs in lisp

**Comment by davorpa** [comment]
> I think this is a good move. Emacs lisp is a dialect of lisp, so probably belongs in lisp

Then PicoLisp too, I'm right?

**Comment by eshellman** [comment]
Would someone looking for a book on Clojure or Scheme know that it is a lisp "dialect"? I didn't. They have enough books to merit their own sections though. EmacsLisp has only one book though?

**Comment by davorpa** [comment]
> Would someone looking for a book on Clojure or Scheme know that it is a lisp "dialect"? I didn't. They have enough books to merit their own sections though. EmacsLisp has only one book though?

Ok. last update... 0a83d41b9878093db760016cedfcafbb63c26a33 Please review again.

I don't do the same in file `-langs.md` because have a cross reference to editors in `-subjects.md`.

https://github.com/davorpa/free-programming-books/blob/0a83d41b9878093db760016cedfcafbb63c26a33/books/free-programming-books-langs.md?plain=1#L1396-L1431

Let me know how to resolve in case of want to change it too.

**Pull request merged**
