### PR TITLE
Removed dead links

### PR DESCRIPTION
**Pull request by lordpansar**
## What does this PR do?
Remove resource(s)

## For resources
Android

### Why is this valuable (or not)?
This PR removes 2 dead links that would cause frustration for end users

### How do we know it's really free?
N/A

### For book lists, is it a book? For course lists, is it a course? etc.
N/A

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by davorpa** [comment]
Use `[x]` to check request steps

**Review by davorpa — COMMENTED** [review]
❓ I imagine that an alternative could not be found, it doesn't?

**Comment by lordpansar** [comment]
Changed the checks according to specific syntax in comment above

**Comment by lordpansar** [comment]
> 
> 
> Use `[x]` to check request steps (no spaces)
> 
> helps to improve #5470

Edited checks according to above syntax

**Comment by lordpansar** [comment]
> 
> 
> ❓ I imagine that an alternative could not be found, it doesn't?

I don't understand the question. Should I make any changes to the PR?

**Comment by davorpa** [comment]
> > question I imagine that an alternative could not be found, it doesn't?
> 
> I don't understand the question. Should I make any changes to the PR?

I'ts a merely question. I'm talking about [CONTRIBUTING](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#guidelines) :wink:
> - if a link has an expired certificate/self-signed certificate/SSL issue of any other kind:
>   - replace it with its http counterpart if possible (because accepting exceptions can be complicated on mobile devices).
>   - leave it if no http version is available but the link is still accessible through https by adding an exception to the browser or ignoring the warning.
>  - remove it otherwise.

**Pull request merged**
