### PR TITLE
Add file for polish podcasts and screencasts

### PR DESCRIPTION
**Pull request by ClouddJR**
## What does this PR do?
Add resources for polish podcasts and screencasts

### Description 
The podcast included is about development in general

### How do we know it's really free?
The website does not require registering or providing email address in order to listen to that podcast

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by ClouddJR** [comment]
@eshellman My PR also fixes build on master, so you may want to check it out

**Comment by eshellman** [comment]
Why the "0" in the category?  
Sorry about the problem in the master build - caused by overlapping merges. It's fixed.

**Comment by ClouddJR** [comment]
I took this from this file https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books-pl.md

"Niezależne od języka programowania" in English means more or less "Independent from programming language"

**Comment by eshellman** [comment]
yes, please remove it.

**Pull request merged**
