### PR TITLE
Added a new book Cpp_STL_ReferenceManual

### PR DESCRIPTION
**Pull request by User-DK**
## What does this PR do?
Add resource(s) 

### Description
Added a new book Cpp_STL_ReferenceManual

### Why is this valuable (or not)?
Valuable for learning C++ Standard Template Library

### How do we know it's really free?
Made available for free on Internet by the Publisher

### For book lists, is it a book? For course lists, is it a course? etc.
Book

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
Is this pdf referenced from the cppreference website? It should have a proper title, don't you think?

**Comment by User-DK** [comment]
Yes, sir you are right thankyou for pointing out. I literallly forgot it. Actually its my first Pull request :)

**Comment by eshellman** [comment]
find out where the pdf is referenced please

**Comment by eshellman** [comment]
where is the reference?

**Comment by User-DK** [comment]
i have added the reference on the right side of the link like this 
[Cpp STL ReferenceManual](https://www.cppreference.com/Cpp_STL_ReferenceManual.pdf) - cppreference.com (PDF)
isn't it enough please let me know if it is wrong and specify what went wrong.....

**Comment by eshellman** [comment]
There are no links to the pdf from that web address. That suggests to me that the pdf is not maintained and probably not appropriate for us to link to.

**Pull request closed without merging**
