### PR TITLE
Updated I Love Ruby to latest download link

### PR DESCRIPTION
**Pull request by mindaslab**

### CODE REVIEW

**Comment by vhf** [comment]
Thanks! Is there a more canonical link to this book, or a homepage for it?

**Comment by mindaslab** [comment]
Nope I don't have a home page for it.

**Comment by vhf** [comment]
Ok, then sorry, we cannot include this. :(

**Comment by eshellman** [comment]
We're hosting the book at Unglue.it https://unglue.it/work/143022/

**Comment by mindaslab** [comment]
@eshellman the book gets updated frequently and sometimes sporadically. You can get the latest here https://cloud.openmailbox.org/index.php/s/u4sX065QRgjbJL2/download

**Comment by eshellman** [comment]
@mindaslab we have a number of ways you can keep the version current; contact me directly.

**Comment by eshellman** [comment]
Maybe submit to Internet Archive?

**Comment by eshellman** [comment]
This link has been updated in another PR. Thanks for making the book free!

**Comment by mindaslab** [comment]
It will be free forever! I have a full time Ruby + Python job, so am not dependent on this book for income.

**Pull request closed without merging**
