### PR TITLE
Updated code of conduct

### PR DESCRIPTION
**Pull request by sandlib**
Link to homepage and version are updated from http to https as [Hyper Text Transfer Protocol Secure].
's' is suffixed to http to make the secure link so that it is not considered as a mallacious spam link by any browser.

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Review by sandlib — COMMENTED** [review]
convert http to https for secure redirect.

**Comment by eshellman** [comment]
one more link to upgrade!

**Review by sandlib — COMMENTED** [review]
Check the update now

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
