### PR TITLE
Add PHP AJAX jQuery Tutorial Book

### PR DESCRIPTION
**Pull request by maulanaaghnii**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Thenlie** [comment]
Is this co-authored by Oleh and Desrizal? Saw this on the cover and wasn't totally sure. If not, everything looks good! 👍 

image

**Comment by maulanaaghnii** [comment]
> Is this co-authored by Oleh and Desrizal? Saw this on the cover and wasn't totally sure. If not, everything looks good! 👍
> 
> image

Oleh word is indonesian that refered to "By"
image

**Review by Thenlie — APPROVED** [review]

**Comment by Thenlie** [comment]
> Oleh word is indonesian that refered to "By" 

😅 Good to know! Thanks for the reply.

**Comment by maulanaaghnii** [comment]
> > Oleh word is indonesian that refered to "By"
> 
> 😅 Good to know! Thanks for the reply.

Anytime , Buddy.

**Pull request merged**
