### PR TITLE
Add Technical Writing subject with one book

### PR DESCRIPTION
**Pull request by capjamesg**
## What does this PR do?

Add resource(s)

### Description

This PR adds a new Technical Writing category. I have included [Software Technical Writing: A Guidebook](https://jamesg.blog/book.pdf) as the first book in the category. 

### Why is this valuable (or not)?

The included book provides guidance on becoming a technical writer, how to write technical documents, and working with a team as a technical writer.

### How do we know it's really free?

The book can be publicly accessed from my website.

### For book lists, is it a book? For course lists, is it a course? etc.

The resource is a book.

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [X] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction).
- [X] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
Great addition, however we try not to add a category for a single resource. Use Misc.

**Comment by capjamesg** [comment]
Will update.

**Comment by capjamesg** [comment]
Updated!

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by capjamesg** [comment]
Why thank you! Free e-books are the best :)

**Comment by capjamesg** [comment]
@eshellman Can I add the book to https://unglue.it? I am not interested in the "Ask" part of the "Thanks for Ungluing" campaign (the book is free; no donations necessary!), but I am interested in distributing it to the extent I can.

**Pull request merged**
