### PR TITLE
Fix ordering and resources, check_urls=free-programming-books.md

### PR DESCRIPTION
**Pull request by kadhirash**
## What does this PR do?
Add Resource | Add info | Improve Repo
 
### Description 
Fix up the file and move ordering.

### Why is this valuable (or not)?
Improve how the file looks, correctly!

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by kadhirash** [comment]
@eshellman this should fix the ordering of resources and spacing correctly in free-programming-books (unless resources get added before this is merged)!

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by kadhirash** [comment]
There is a merge conflict now due to resources being added in the old file spot before this was merged

**Comment by kadhirash** [comment]
@eshellman a JS book was added before this was merged in the old spot so I had to move that and just fixed it. If other resources are merged to this file before this file is merged, it will keep having conflicts

**Comment by eshellman** [comment]
OK, now I see what you're proposing to do. I'm going to close the PR, not because it's a bad idea, but because it will cause merge conflicts and we have 249 open PRs. Maybe at the end of november, after we've cleared out the hacktoberfest backlog - I'll be asking for volunteers to help with that.

**Comment by kadhirash** [comment]
@eshellman okay makes sense, sounds like a plan!

**Pull request closed without merging**
