### PR TITLE
Added link to opensource Bash book

### PR DESCRIPTION
**Pull request by bobbyiliev**
## What does this PR do?
Add resource

### Description 
Added a link to a free opensource Introduction to Bash Scripting eBook
### Why is this valuable (or not)?
Shell scripting is essential and this eBook gives a great starting point.
### How do we know it's really free?
It is an opensource eBook available on GitHub. You can download the PDF version that comes in light and dark modes
## Checklist:
- [x] Read our [contributing guidelines](/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [ x] Put lists  in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
Makrdown ?

**Comment by bobbyiliev** [comment]
> Makrdown ?

Yes, is this a problem? 

I see other books with the same description as well:
image

**Comment by eshellman** [comment]
look at the spelling

**Comment by bobbyiliev** [comment]
> look at the spelling

Seems like my dyslexia is kicked in there... Thanks for pointing that out! should be better now.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!
Thanks for making your book free! As it has an Open License, consider adding it to Unglue.it and Archive.org.
Have added suggestions on the repo.

**Pull request merged**
