### PR TITLE
Update free-courses-ur.md

### PR DESCRIPTION
**Pull request by AryavT**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

### Description
a C# tutorial in Urdu/Hindi
### Why is this valuable (or not)?
this is valuable because people like me can use this to learn about C# I personally relate because I know Hindi and Urdu and it will help my parents a lot
### How do we know it's really free?
it is a YouTube video
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Ajay-singh1** [comment]
LGTM! @eshellman

**Comment by eshellman** [comment]
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

**Comment by Ajay-singh1** [comment]
@AryavT Make the necessary changes!

**Comment by eshellman** [comment]
too short to be a course

**Pull request closed without merging**
