### PR TITLE
fix: homogenize markdown across files using markdownlint rules

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?
Improve repo

### Why is this valuable (or not)?

Homogenizes using markdownlint rules (see also #6829 to check which are applied)

See each commit title/description to understand better what we are doing

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by davorpa** [comment]
Conflicts are with  #6963

**Comment by davorpa** [comment]
Conflicts remains with 
- #6983 

due to final blank lines

**Comment by LuigiImVector** [comment]
Wasn't it enough to change the value of "indent" to 2? Even if that meant disabling MD005.

**Comment by davorpa** [comment]
> Wasn't it enough to change the value of "indent" to 2? Even if that meant disabling MD005.

According to `.editorconfig` file, indentation is using 4 spaces

https://github.com/EbookFoundation/free-programming-books/blob/04cf8c84ed096caa02aaf9fd1d37db097e8e237a/.editorconfig#L11-L12

Is this why enable MD005 to use that number of spaces.

Let's discuss about it

**Comment by LuigiImVector** [comment]
On the [official kramdown website](https://kramdown.gettalong.org/syntax.html#usage-of-tabs) it says:
> kramdown assumes that tab stops are set at multiples of four. This is especially important when using tabs for indentation in lists. Also, tabs may only be used at the beginning of a line when indenting text and must not be preceded by spaces. Otherwise the results may be unexpected.

So I think 4 indent_size it's okay.

**Comment by davorpa** [comment]
Conflicts again due to #6989 merge which modifies TOC entries with ML, NLP...

**Comment by davorpa** [comment]
More conflicts after merge #6986 which modify TOC entries removing `impress.js`

**Review by eshellman — COMMENTED** [review]
What's the motivation behind replacing translated words with Englishe words?

**Comment by davorpa** [comment]
> What's the motivation behind replacing translated words with Englishe words?

I suppose you refer to 4d6a74e7d794f1f264cb2f88d9531e43038d3be2 commit which normalizes TOC section header to `Index` word, it doesn't?

I don't know yet how it works but thinking in the fpb-parser, I hope it helps to filter this section from processing. It'll be easy to do using same word and heading level (3 `#`) or even more... develop a fpb-lint rule expecting this `Index` branch as markdown listing element

make a `git revert` is always a good option here if it isn't relevant or already contemplated

**Comment by eshellman** [comment]
> > What's the motivation behind replacing translated words with Englishe words?
> 
> I suppose you're referring to [4d6a74e](https://github.com/EbookFoundation/free-programming-books/commit/4d6a74e7d794f1f264cb2f88d9531e43038d3be2) commit which normalizes TOC section header to `Index` word, it doesn't?
> 
> I don't know yet how it works but thinking in the fpb-parser, I hope it helps to filter this section from processing. It'll be easy to do using same word and heading level (3 `#`) or even more... develop a fpb-lint rule expecting this `Index` branch as markdown listing element
> 
> https://github.com/EbookFoundation/free-programming-books-parser/blob/5eaf00bfd861856a85b2ba6f2d2aa282fab55a69/index.js#L178-L192
> 
> As we can see... `Index` is expected according to current sourcecode. I open [EbookFoundation/free-programming-books-parser#1](https://github.com/EbookFoundation/free-programming-books-parser/issues/1) to address it
> 
> Of course, make a `git revert` is always a good option here if it isn't relevant or already contemplated

best not to fix something unless its broken

**Comment by davorpa** [comment]
> best not to fix something unless its broken

Then reverting 4d6a74e7d794f1f264cb2f88d9531e43038d3be2 😄

**Comment by eshellman** [comment]
LGTM. Ready to merge?

**Comment by eshellman** [comment]
go ahead

**Pull request merged**
