### PR TITLE
Update link to Modern Perl

### PR DESCRIPTION
**Pull request by wh0**
## What does this PR do?
Improve repo

### Description

The page that our Modern Perl link goes to is no longer available. This updates our list to point to the ~~publisher's~~ author's website, where you can still get the book for free.

Archive of the old link https://web.archive.org/web/20210326030126/http://onyxneon.com/books/modern_perl/ indicates that "5" is not part of the title of the book. It is about Perl 5, but it's just called Modern Perl.

### Why is this valuable (or not)?

N/A, maintaining an existing entry.

### How do we know it's really free?

The publisher's website also lists the ebooks for free https://pragprog.com/titles/swperl/modern-perl-fourth-edition/ :

> Get all eBook formats here for $0.00 (USD)

Wikipedia article on the author mentioning the book https://en.wikipedia.org/wiki/Chromatic_(programmer) :

> In 2010, he released the book Modern Perl in print and in electronic form, with the latter redistributable freely (though with a suggested donation). An updated edition was released in 2012, with the entire text online.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
seems it's not an authorized free book both links should be removed

**Comment by wh0** [comment]
oh you're right, it later asks for an email address. I'm going to repurpose this PR to remove the link then. thanks for checking

**Comment by wh0** [comment]
oh rather than removing this: I found that the author chromatic distributes the book without requiring email: http://modernperlbooks.com/books/modern_perl_2016/ I'll update to that instead

from his website http://modernperlbooks.com/

checked for https, couldn't connect

no equivalent link for "latest"

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
