### PR TITLE
added hindi book "C in Hindi" by Kuldeep Chand

### PR DESCRIPTION
**Pull request by siddharth784**
## What does this PR do?
Add resource

## For resources
https://onlineaavedan.com/study_material/1543909480.pdf

### Description
"C in Hindi" by Kuldeep Chand added 

### Why is this valuable (or not)?
Limited resources in hindi in the repo. 

### How do we know it's really free?
It is publicly available online on a secure website

### For book lists, is it a book? For course lists, is it a course? etc.
Yes, it is a book in pdf format

## Checklist:
- [ ✅] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ✅] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ✅] Include author(s) and platform where appropriate.
- [ ✅] Put lists in alphabetical order, correct spacing.
- [ ✅] Add needed indications (PDF, access notes, under construction).
- [ ✅] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by siddharth784** [comment]
Do let me know what I did wrong if this pull request isn't considered. I am new to this.

**Comment by eshellman** [comment]
how do we know the distribution is authorized by the author?

**Comment by siddharth784** [comment]
No idea..how do we even get to know that about any book?

**Comment by eshellman** [comment]
look up the author, the listed publisher, etc.

**Pull request closed without merging**
