### PR TITLE
Added Descubre React book

### PR DESCRIPTION
**Pull request by CristinaMendonca**
Added the book [Descubre React](https://leanpub.com/descubre-react) to the Spanish React books section

## What does this PR do?
Add Resource(s)

### Why is this valuable (or not)?
A more introductory book to React, made from an author that has another book in the list (the one about CoffeeScript).

### How do we know it's really free?
Published as free in Leanpub by author.

### For book lists, is it a book? For course lists, is it a course? etc.
It's a book.

### Checklist:
- [X] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [X] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Hey, and welcome to free programming books! :wave:

It looks like the books you've added aren't free, they both have a minimum price set on it of $5.00.

**Comment by CristinaMendonca** [comment]
> 
> 
> Hey, and welcome to free programming books! 👋
> 
> It looks like the books you've added aren't free, they both have a minimum price set on it of $5.00.

You're right, - it was tagged as free somewhere else, but must have changed in the meantime, will delete the merge, sorry!

**Comment by SethiPandi** [comment]
> > Hey, and welcome to free programming books! wave
> > It looks like the books you've added aren't free, they both have a minimum price set on it of $5.00.
> 
> You're right, - it was tagged as free somewhere else, but must have changed in the meantime, will delete the merge, sorry!
> 
> Edit1: Well, I can't delete it, so I will try to find another book in Spanish to add?
> Edit2: Have switched with another book that is free. Sorry and thanks for your patience @SethiPandi.

That's great, thanks for the fix! ^-^

**Comment by eshellman** [comment]
This is the type of leanpub book where we require the note "registration required". see other leanpub books for examples.

**Comment by CristinaMendonca** [comment]
> 
> 
> This is the type of leanpub book where we require the note "registration required". see other leanpub books for examples.

Okidoki, added that warning (and also to the entry above mine, that was also missing it). Thanks!

**Comment by eshellman** [comment]
Thanks

**Pull request merged**
