### PR TITLE
fix(docs): Normalize localized filename format across all files

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?
Improve repo

### Description

This handles something about file names and localization.

I see some files with a mixed nomenclature (locale code vs. language code). E.g.:
- `HOWTO.pt_BR.md` (with dot/underscore) :x:
- `CONTRIBUTING-fa_IR.md` (with dash/underscore) :heavy_check_mark:
- `CONTRIBUTING-zh-TW.md'` (with dash/dash) :x:

Some  :heavy_check_mark: repo listing files: `free-programming-books-fa_IR.md`, `free-programming-books-pt_BR.md`. Then, the 99% follows the regex `name(-locale)?.md` where locale is in underscore format `language_COUNTRY`.

Then, **`CONTRIBUTING-zh-TW.md`, `HOWTO-zh-TW.md` and `HOWTO.pt_BR.md` are renamed preserving commit history**.

### Why is this valuable (or not)?

This finishes normalizing the localized file names according to all the others in the project. Localization was introduced at:
- #4327 #4264
- #4293

Also I think it helps in some manner to improve https://github.com/EbookFoundation/free-programming-books/issues/4579

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
conflicts already!

**Comment by davorpa** [comment]
> conflicts already!

Resolved :wink:

**Comment by eshellman** [comment]
maybe I shouldn't have accepted #5561

**Comment by davorpa** [comment]
> maybe I shouldn't have accepted #5561

Solved rename conflict `HOWTO.pt_BR.md > HOWTO-pt_BR.md`, with also changes in file made in #5561

**Pull request merged**
