### PR TITLE
Added Vim Cheet Sheet

### PR DESCRIPTION
**Pull request by rutujak24**
## What does this PR do?
Add resource for Vim

## For resources
Solves issue  #5586

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by rutujak24** [comment]
Please add ‘hacktoberfest-accepted’ label to the PR to opt-in.

**Review by davorpa — CHANGES_REQUESTED** [review]
move resource to cheatsheets

**Comment by davorpa** [comment]
Will be autoclosed when merge #6597 (closing in favour of)

**Comment by davorpa** [comment]
> Will be autoclosed when merge #6597 ([closing in favour of](https://github.com/EbookFoundation/free-programming-books/pull/6091#ref-commit-143f464))

**Pull request closed without merging**
