### PR TITLE
Add new PHP resources from coderlessons (RU)

### PR DESCRIPTION
**Pull request by ShkiperMe**
## What does this PR do?
Add new PHP resources from coderlessons

### CODE REVIEW

**Comment by davorpa** [comment]
> I think these fit in the interactive tutorials list

I doubt. It has TOC in the first blog page. and each blog page has previous/next links. I can't find any `Play` buttons to experiment with code snippets

**Another question... It's really valuable with so much ads?**

**Comment by eshellman** [comment]
Russian users can make judgment about ads.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by ShkiperMe** [comment]
Hi @eshellman 
Could you please check my other pull requests tagged in this thread? They have similar changes.

**Pull request merged**
