### PR TITLE
Update free-programming-books-subjects.md

### PR DESCRIPTION
**Pull request by atharva20-coder**
## What does this PR do?
Add resource

### Description
Machine learning course by Microsoft
### Why is this valuable (or not)?
Microsoft engineers taught
### How do we know it's really free?
The attached link redirects to the GitHub repository
### For book lists, is it a book? For course lists, is it a course? etc.
it is course

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-boks/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

### CODE REVIEW

**Comment by atharva20-coder** [comment]
@shrn01 Please merge this PR if its correct

**Review by shrn01 — APPROVED** [review]

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by atharva20-coder** [comment]
> Thanks, and welcome to free-programming-books!

Please tag it as hactoberfest

**Comment by shrn01** [comment]
@atharva20-coder  You will be able to see this PR in hacktoberfest without the label

**Comment by atharva20-coder** [comment]
> @atharva20-coder  You will be able to see this PR in hacktoberfest without the label 

It shows excluded

**Pull request merged**
