### PR TITLE
Create free-programming-cheatsheets.md

### PR DESCRIPTION
**Pull request by hitaarthh**
## What does this PR do?
This PR is a collection of some useful links of Django Cheat Sheets.

## For resources
This PR provides some useful Django Cheat Sheet links which can be opened with one click and doesn't ask for any verification or signup related issues.

### Why is this valuable (or not)?
This is a valuable PR because it contains some beginner friendly Django Cheat Sheets links which are easy to understand and apply in code.

### How do we know it's really free?
The sites doesn't asks for any email/mobile no. verification and signup related issues. All the links are followed by https:// which makes it more secure.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Rituraj-13** [comment]
@hitaarthh You Just copied down my about section of my PR and tried to merge it without getting assigned for the task. And I don't think this is a good practice for a open source developer to do such things.

**Comment by hitaarthh** [comment]
@Rituraj-13 I guess this issue was open for everyone and was not even assigned to you, you may go through the changes again, the files have been modified in a differently.

**Comment by Rituraj-13** [comment]
> @Rituraj-13 I guess this issue was open for everyone and was not even assigned to you, you may go through the changes again, the files have been modified in a differently.

image
Hey bro, don't take it in a bad way I was just referring to the about section of my previous PR  and your current PR about section, the both are exactly same.
And please through assigned section of the issue.

**Review by davorpa — COMMENTED** [review]
Please, alphabetize section and add it to TOC

**Comment by davorpa** [comment]
Definitely dups

**Comment by davorpa** [comment]
Duplicate of #7132

**Pull request closed without merging**
