### PR TITLE
Add two books in swedish

### PR DESCRIPTION
**Pull request by fridokus**
## What does this PR do?
Add two books in swedish, for Python and Fortran

### Description
Python book in wikibooks and a self-published Fortran book from the University of Linköping

### Why is this valuable (or not)?
Swedish is missing many languages and these are two new added

### How do we know it's really free?
Wikibooks is known. The fortran book is published on the authors own webpage

### For book lists, is it a book? For course lists, is it a course? etc.

Books 

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
need to add the categories to the index. also spell python correctly

**Comment by fridokus** [comment]
Done

**Comment by fridokus** [comment]
@eshellman this ok now?

**Comment by eshellman** [comment]
Tack, och välkommen till free-programming-books!

**Pull request merged**
