### PR TITLE
Update free-programming-books-subjects.md

### PR DESCRIPTION
**Pull request by Francesco601**
## What does this PR do?
Add resource(s)  and Improve repo

### Description
Many OS books,

### Why is this valuable (or not)?
free books are educational and worthy of sharing

### How do we know it's really free?
Check,

### For book lists, is it a book? For course lists, is it a course? etc.
Many books.
## Checklist:
- [ x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ x] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ x] Add needed indications (PDF, access notes, under construction).
- [ x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
please use markdown

**Comment by Francesco601** [comment]
Ah, ok.

**Comment by Francesco601** [comment]
I've converted all to MD and added PDF indications, but it seems to be saying there are stilling missing PDF indicators. Let me know...

**Comment by eshellman** [comment]
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems. I think you need `(PDF)`. you have not sorted alphapetically, pay attention to the number of spaces.
Please read docs/CONTRIBUTING.md guidelines! 
Some of your links are not authorized distributions or point to file-sharing sites. 
We generally link only to books, not to other lists of books.
You have not checked for duplicates.

**Pull request closed without merging**
