### PR TITLE
Add sudoer.ir to persian

### PR DESCRIPTION
**Pull request by MortezaBashsiz**

### CODE REVIEW

**Comment by MortezaBashsiz** [comment]
Add sudoer.ir to Persian Linux courses

**Comment by eshellman** [comment]
Maybe this fits better into podcasts/screencasts?

**Comment by MortezaBashsiz** [comment]
> Maybe this fits better into podcasts/screencasts?

I have no idea about it, My website includes videos(screencasts), documents, and podcasts nut the most content is screen recorded videos with the structure of learning Linux.
Actually, I can not put it in specific category.
But I agree with you about the screencasts, I will change it.

**Comment by MortezaBashsiz** [comment]
I put the YouTube playlist address
This is more like a course

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
