### PR TITLE
 Crab

### PR DESCRIPTION
**Pull request by Adidasuz**
Adidasuz

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by GUdokermensz** [comment]
> Adidasuz
> 
> ## What does this PR do?
> Add resource(s) | Remove resource(s) | Add info | Improve repo
> 
> ## For resources
> ### Description
> ### Why is this valuable (or not)?
> ### How do we know it's really free?
> ### For book lists, is it a book? For course lists, is it a course? etc.
> ## Checklist:
> * [x]  Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
> * [x]  [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
> * [x]  Include author(s) and platform where appropriate.
> * [x]  Put lists in alphabetical order, correct spacing.
> * [x]  Add needed indications (PDF, access notes, under construction).
> * [x]  Used an informative name for this pull request.
> 
> ## Follow-up
> * Check the status of GitHub Actions and resolve any reported warnings!
[Adidasuz:patch-1](9458)

**Comment by Adidasuz** [comment]
Bizni kuzatishda davom eting

**Comment by Adidasuz** [comment]
Adidasuz@umail.uz

**Comment by harryyu1018** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您的邮件我已收到，我会尽快阅读并回复您。祝您工作顺利，心情愉悦！

**Comment by Adidasuz** [comment]
> língíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngíngín yàngìnė，kāngīngīngī!

be more specific

**Pull request closed without merging**
