### PR TITLE
Added Solidity programming language and book

### PR DESCRIPTION
**Pull request by alcole**

### CODE REVIEW

**Comment by eshellman** [comment]
This resource describes itself as an article. Is it the best free book-like resource on Solidity? Also, it's 2 years old. Is it still useful?

Also I note that we don't list the book it cites as the best place to start, https://github.com/bitcoinbook/bitcoinbook

**Comment by alcole** [comment]
Both good points. 
I found the book / article when searching for books, so perhaps it doesn't fulfill the strict definition, but there is not much out there (free or otherwise).
On your second point, the book is on Solidity which is a programming language for programming smart contracts on the Ethereum block chain. The Bitcoin book that is linked to is more about the bitcoin / blockchain environment, rather than programming smart contracts, but it might be of interest here, I'll check if it is added.

**Comment by eshellman** [comment]
On the Solidity article, I agree it could be a book, and it's in a free-book desert, so we should add it. The bitcoin book is a great addition. Could you add the authors in the listings for these two books? TIA.

**Comment by alcole** [comment]
Done! cheers

**Comment by eshellman** [comment]
much appreciated!

**Pull request merged**
