### PR TITLE
Free pdfs

### PR DESCRIPTION
**Pull request by Dreadlord075**
## Checklist:
- [✔] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [✔ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [✔ ] Include author(s) and platform where appropriate.
- [✔ ] Put lists in alphabetical order, correct spacing.
- [✔ ] Add needed indications (PDF, access notes, under construction).
- [✔ ] Used an informative name for this pull request.

### CODE REVIEW

**Comment by eshellman** [comment]
wrong list, duplicates

**Comment by Dreadlord075** [comment]
> wrong list, duplicates

which ones can you elaborate

**Comment by Dreadlord075** [comment]
I added new pdf courses in the actual .md file.
can you guide what went wrong

**Comment by Dreadlord075** [comment]
i mean i did put the list in exact alphabetical order
and i did look into that other english language list for pdf and yes i did only find one link similar to mine which i removed so that it dont get counted as duplicate

**Pull request closed without merging**
