### PR TITLE
Added C# books.

### PR DESCRIPTION
**Pull request by GintasS**
## What does this PR do?
Add Resources

### Description 
Added 9 books.

### Why is this valuable (or not)?
They're free!

### How do we know it's really free?
They're available for free by the publisher https://www.syncfusion.com/

### For book lists, is it a book? For course lists, is it a course? etc.
They're books.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
In the past we've labeled these as `(email address *requested*, not required)`. What's the story now. (try using a fake email)

**Comment by SethiPandi** [comment]
> In the past we've labeled these as `(email address *requested*, not required)`. What's the story now. (try using a fake email)

I've already tried this, it asks for email verification. The account requires verification before you're granted access to the books.

**Comment by GintasS** [comment]
@eshellman Yes, it is required to register with the working email address in order to verify it, so we can't include books that require this? But @SethiPandi mentioned you can read them without downloading.

**Comment by VitaliySh** [comment]
It seems to be not available outside of the US.

**Comment by SethiPandi** [comment]
> It seems to be not available outside of the US.

Interesting, that sounds a bit like https://github.com/EbookFoundation/free-programming-books/issues/3368, I'm in Belgium and it works perfectly for me on my mobile network and computer. :thinking:  

I have also sent one of the links (https://www.syncfusion.com/ebooks/csharpcontracts) to a friend in Bosnia, and Norway to see if they could access it. Both seemed to be able to access the site fine.

@VitaliySh At what point do you see that it's not available outside the US? Is there a particular flow you have to take first?

---

I'm actually on my computer this time, so I decided to check every link of this PR one by one instead of just a one or two:
* It seems some are free to download, no email address is required.
  * https://www.syncfusion.com/ebooks/asynchronous_programming_succinctly
  * https://www.syncfusion.com/ebooks/neuralnetworks
  * https://www.syncfusion.com/ebooks/twilio_with_c_sharp_succinctly
  * https://www.syncfusion.com/ebooks/customer_success_for_c_sharp_developers
* Some require registration to download it, but _can be viewed online freely without registration_ at all.
  * https://www.syncfusion.com/ebooks/csharp
  * https://www.syncfusion.com/ebooks/data_capture_and_extraction_with_c_sharp_succinctly
  * https://www.syncfusion.com/ebooks/machine
  * https://www.syncfusion.com/ebooks/sql_server_for_c_sharp_developers_succinctly
* Some **require** registration and a **verified email address** to download it, **no online view available**.
  * https://www.syncfusion.com/ebooks/csharpcontracts

**Comment by SethiPandi** [comment]
I've contacted Syncfusion on the matter via their on-site live chat:

> We wont support for the below US banned export countries.
> Iran
> Afghanistan
> Russia
> Yemen

Apparently, these are the countries which can't receives books via Syncfusion.

Unfortunately, the best source I can provide is a snippet from the live chat, when I asked for any official documentation, so I can cite it from a more reputable source, they said they can't help with that and that I could try their legal department.

The lack of support for certain countries also isn't mentioned on their terms of service I don't think.

**Comment by eshellman** [comment]
IIRC, Syncfusion added many of these themselves. It's not nice that they seem to have 3 different regimes. 
We're ok with books you can read online but need registration to download. 
We discourage books that "require registration and a verified email address to download it, no online view available." - If someone writes an essay saying that it's an amazing book and a worthy publisher that should be allowed anyway, we make an exception. We're more lenient about courses - some features really do require registration or need to block abuse.

Leanpub is similar in that some books are for purchase only, others require registration but can be read without, and others require registration to read. It's pretty easy to tell them apart though, and they have some really valuable CC licensed books for free. They have a strong author community, too.

So, thank you @GintasS @SethiPandi @VitaliySh for looking into this; I'm closing this PR. We probably should write up  some publisher-specific guidelines that embody the evolving policy; we'll need to wait till november though!

**Pull request closed without merging**
