### PR TITLE
Updated problem-sets-competitive-programming.md file

### PR DESCRIPTION
**Pull request by c1phani1simha**
Added one Best competitive coding platforms, i.e., Pep Coding, where people can get the best and free resources for competitive programming

## What does this PR do?
Add resource(s) | Add info | Improve repo

### Description

This PR will helps the programmers to get exposed to one of more best platforms where they can improve their coding skills while learning with the best community!

### Why is this valuable (or not)?

Because this PR includes the latest and updated platforms rather than older ones in which many bugs are not fixed.

### How do we know it's really free?

The platforms are open to all!

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by LuigiImVector** [comment]
insert specific link

**Comment by c1phani1simha** [comment]
Hello @LuigiImVector, As per your request, I had updated and committed. Please check this PR!!

**Comment by LuigiImVector** [comment]
Good

**Comment by c1phani1simha** [comment]
@eshellman, If possible, please add a hacktoberfest-accepted label; it will be beneficial and motivate me!!

**Comment by LuigiImVector** [comment]
> @eshellman, If possible, please add a hacktoberfest-accepted label; it will be beneficial and motivate me!!

merged PRs are automatically counted in your hacktoberfest profile

**Comment by c1phani1simha** [comment]
@LuigiImVector, but if label is added, there may be no chances of exclusion

**Comment by LuigiImVector** [comment]
repository has that label, everything is fine

**Pull request merged**
