### PR TITLE
Fixing issue #5176

### PR DESCRIPTION
**Pull request by computamike**
## What does this PR do?
Fixes rendering issues with Pipes within links

### Why is this valuable (or not)?
Issue #5176 identified an issue with the screencasts(en) page - however, this same issue has been identified on other pages, and has been fixed.
 
## Checklist:
- [X] Read our [contributing guidelines](/CONTRIBUTING.md)
- [X] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists  in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by computamike** [comment]
Some additional comments : 

The following Regular expression was used to scan the codebase to find other instances of this issue : 

`
^(.*)(\[)(.*)(\|)(.*)(\])
`

and the following was used to escape the `|` character (this was done using VS Code's regex replace)
`
$1$2$3\|$5$6
`
Screenshot from 2020-11-21 03-02-10
This could be useful to add to the linter to identify where this would break rendering, or to scan and fix the codebase at a later date.

**Comment by shabab477** [comment]
Interesting fix. This PR LGTM. I feel like there should be a fix in the linter too.

**Comment by computamike** [comment]
> Interesting fix. This PR LGTM. I feel like there should be a fix in the linter too.

Have raised an issue in the linter for this.

**Comment by eshellman** [comment]
This is awesome @computamike ! Thanks!

**Pull request merged**
