### PR TITLE
Rearrange js sections

### PR DESCRIPTION
**Pull request by marcelbrode**
## What does this PR do?
 Improve repo

### Description
Re-arrange JS subsections to JS to avoid confusion + merged weird split of Angular content

### Why is this valuable (or not)?
Better overview

### How do we know it's really free?
-

### For book lists, is it a book? For course lists, is it a course? etc.
-

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by Thenlie — APPROVED** [review]
I think this is a reasonable change. Having Angular split does seem wrong.

**Comment by eshellman** [comment]
see #4940
I don't know enough about Angular to know if this PR is reversing that decision or implementing that decision for newer additions. 
The other changes look good, perhps the concerns could be split?

**Comment by Thenlie** [comment]
Oh wow, didn't even realize they were two separate things. Clearly I do not know enough about Angular either 😅 

Regardless, splitting the TS changes from the Angular changes sounds like a good idea.

**Comment by marcelbrode** [comment]
Hm, true thing. But in any case, this should be a JS thing, thats true. I'll split Angular and AngularJS then!

**Comment by eshellman** [comment]
thanks!
(please forgive if I am terse, have many PRs to review.)

**Comment by marcelbrode** [comment]
Pushed. Decided to make it a sub of Angular, so that people will see there's a distinction.

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
