### PR TITLE
Added git playground link

### PR DESCRIPTION
**Pull request by shabab477**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource

## For resources
Its a play ground for Git, maintained [here](https://github.com/pcottle/learnGitBranching). It also hosts an interactive tutorial for learning Git. You can check available commands in the playground using `show commands` on the UI terminal.

### Why is this valuable (or not)?
Having a git playground for small experiments is extremely valuable for learning

### How do we know it's really free?
Its a playground link as hosted by open source contributors

### For book lists, is it a book? For course lists, is it a course? etc.
Its a playground link for learning Git

### Checklist:
- [x] Not a duplicate
- [ ] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by shabab477** [comment]
> please resolve conflicts.

Done 😸

**Comment by eshellman** [comment]
Many of us need this one!

**Comment by shabab477** [comment]
Thank you, feels good to contribute.

**Pull request merged**
