### PR TITLE
Updated links for An Introduction to Statistical Learning

### PR DESCRIPTION
**Pull request by nihilisticneuralnet**
## What does this PR do?
Improve repo

## For resources
https://www.statlearning.com/

### Description
The previous link were broken. Thus, fixed it with new links

### Why is this valuable (or not)?
This book is commonly used for data science and statistics

### How do we know it's really free?
https://www.statlearning.com/

### For book lists, is it a book? For course lists, is it a course? etc.
Book

## Checklist:
- [ ✓] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [✓ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ✓] Include author(s) and platform where appropriate.
- [✓ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [✓ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
there are two different books, use the updated links from the webage that you've linked.

**Comment by nihilisticneuralnet** [comment]
Changes have been made.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by nihilisticneuralnet** [comment]
Welcome!!!

**Pull request merged**
