### PR TITLE
さあ、見つけよう。新しい学びを(Java). 

### PR DESCRIPTION
**Pull request by Shunuk**
## What does this PR do?
Add resource(s)

## For resources
(https://codeprep.jp/books/categories)
### Description
I added resources that online ebooks about programming learning(Java). 
### Why is this valuable (or not)?
This is free to create account and you can studying depending on your level. 
### How do we know it's really free?
Because this website is top 10 famous free sites in japan. 
### For book lists, is it a book? For course lists, is it a course? etc.
Book lists 
## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [X] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction).
- [X] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
add link in just one place, remove chaff file

**Comment by Shunuk** [comment]
I deleted the chaff file, so please check it.

**Comment by eshellman** [comment]
it's still there!

**Comment by Shunuk** [comment]
I think finally deleted my chaff file.

**Review by eshellman — CHANGES_REQUESTED** [review]
you've also added extra spaces - check the linter.

**Pull request closed without merging**
