### PR TITLE
Remove dead links from free-programming-books-langs.md file | Hacktoberfest 2023

### PR DESCRIPTION
**Pull request by Bitnagar**
This PR removes all the dead links from the [free-programming-books-langs.md](https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-langs.md) file.

Dead links are those that resulted in one of the below listed errors:
- Not found or Internal server errors (404, 500, etc.)
- Invalid URLs
- Links that can't be reached with either HTTPS or HTTP protocol.

Following topics have been removed:
- Cilk
- Booty5.js
- Meteor

I have not changed anything in any file except the one i have worked in.

Why is this valuable (or not)?
This is valuable because it removes dead links and improves the quality of the repo.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

----

### CODE REVIEW

**Review by lavin-ds — APPROVED** [review]

**Comment by joedf** [comment]
I think replacing the links with Web Archive links might have been better, no?

**Comment by Bitnagar** [comment]
> Check links! this repo has been around long enough that resources have disappeared. Removing the dead links is just as important as adding new ones.

#9549 says to remove dead links.

**Comment by joedf** [comment]
No worries! Just a thought. 👍

**Comment by Bitnagar** [comment]
> The link to the title _Let's Learn ES6_ by Ryan Christiani has been moved [here](https://bubblin.io/book/let-s-learn-es6-by-ryan-christiani#frontmatter).

I have only made atomic changes as per the guidelines. I think we should update the link(s) in separate PR.

**Comment by paoloose** [comment]
I found several links from this list working fine for me, such as 

- http://www.brackeen.com/vga/
- https://cis.stvincent.edu/html/tutorials/swd/
- http://faculty.knox.edu/dbunde/teaching/chapel/
- https://github.com/esl/erlang-handbook/raw/master/output/ErlangHandbook.pdf

and so on

**Comment by Bitnagar** [comment]
I see only erlang handbook link is operational. Rest of them are still not reachable from my end. I tried to double check before deleting. What can we do about this? Can i undo some deletions?

**Comment by eshellman** [comment]
@Bitnagar yes, you can add more commits to your branch. Fewer changes will be easier to approve.

**Comment by Bitnagar** [comment]
@eshellman okay. There are 70 deletions in current commit. How many should i undo for making it easy to review?

**Comment by QaidVoid** [comment]
This is still operational: https://github.com/wasmflow/node-to-rust/raw/HEAD/from-javascript-to-rust.pdf

Also, https://vulkano.rs/guide/introduction could be changed to https://vulkano.rs

**Comment by RayyanNafees** [comment]
> I found several links from this list working fine for me, such as
 This could be a regional issue.. Mind sharing the country u visited the links from ?
Perhaps copying and making them available on a different domain may work

**Comment by thecodereule** [comment]
> I found several links from this list working fine for me, such as
> 
> * http://www.brackeen.com/vga/
> * https://cis.stvincent.edu/html/tutorials/swd/
> * http://faculty.knox.edu/dbunde/teaching/chapel/
> * https://github.com/esl/erlang-handbook/raw/master/output/ErlangHandbook.pdf
> 
> and so on

they wook for me as well

**Comment by paoloose** [comment]
> > I found several links from this list working fine for me, such as
> 
> This could be a regional issue.. Mind sharing the country u visited the links from ? Perhaps copying and making them available on a different domain may work

I checked them manually (from Lima, Perú) and then used a service (can't remember its name) that is able to HTTP ping urls from many server around the world and found that some were not available for certain countries.

**Comment by Darionas** [comment]
Hey, 
I would like to take part in this repo. I work and I am available just 2 hours per day, and All weekends. If you agree, I am in. If you have a piece of work, I will lovely do it.

**Comment by eshellman** [comment]
Since this PR now has conflicts, I suggest that new PRs be made, each covering a section, maybe 5 deletions at a time. To coordiinate work, each new PR should reference this one using '#9687'[](url)

**Comment by Thenlie** [comment]
> then used a service (can't remember its name) that is able to HTTP ping urls from many server around the world and found that some were not available for certain countries.

@paoloose If you think of the name, please share it here. This could be a useful tool for reviewers. Thanks!

**Comment by Bitnagar** [comment]
> Since this PR now has conflicts, I suggest that new PRs be made, each covering a section, maybe 5 deletions at a time. To coordiinate work, each new PR should reference this one using '#9687'

@eshellman Some links are only available for a particular region. For example, i can't open some links from India but it is operational in other countries. What can we do about this?

**Comment by Royalty252** [comment]
i found some dead links from free-programming-books-langs.md file .
Should I open a PR??

**Comment by Bitnagar** [comment]
> Since this PR now has conflicts, I suggest that new PRs be made, each covering a section, maybe 5 deletions at a time. To coordiinate work, each new PR should reference this one using '#9687'

@Royalty252 Probably yes. Just follow the above guideline given by @eshellman.

**Pull request closed without merging**
