### PR TITLE
Add Go course to pt_BR list

### PR DESCRIPTION
**Pull request by edilsonalves**
## What does this PR do?
- [x] Add resource(s)
- [ ] Remove resource(s)
- [ ] Add info
- [x] Improve repo

### Description
Introductory course to Go language.

### Why is this valuable (or not)?
Perfect for beginners familiar with programming basics, this course provides an easy introduction to Go.

### How do we know it's really free?
The course is shared through a public playlist on YouTube.

### For book lists, is it a book? For course lists, is it a course? etc.
Course.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates
- [x] Include author(s) and platform where appropriate
- [x] Put lists in alphabetical order, correct spacing
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by edilsonalves** [comment]
> looks like you're unintentionally moving the angular section. If so, please close and start with a fresh branch If not, please review the PR that moved it to the current location.

The change was in fact intentional, the previous form contemplated Angular as a subtopic of TypeScript. Should I make any corrections?

**Comment by eshellman** [comment]
if you want to move it, please address issues from #5525

**Comment by edilsonalves** [comment]
> if you want to move it, please address issues from #5525

Considering all other cases it makes sense to keep the hierarchical structure. The change was undone to respect the adopted standard.

**Comment by eshellman** [comment]
Thanks for fixing the missing index entry, and welcome to free-programming-books!

**Pull request merged**
