### PR TITLE
React Tutorial

### PR DESCRIPTION
**Pull request by Yasir-Khan22**
## What does this PR do?
Added a Resource.

## For resources
I have just added another react resource which is absolutely free.

### Why is this valuable (or not)?
This React tutorial is much worthy for beginner because it contains code snippets also.

### How do we know it's really free?
It is absolutely free resource from geeksforgeeks editor's website.

### For book lists, is it a book? For course lists, is it a course? etc.
The React resource I've added is tutorial type. 

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
Don't invent titles! Use the title given by the resource. In this case "ReactJS Tutorials"

**Comment by Yasir-Khan22** [comment]
y're talking about this title? 

image

I've updated it.

**Comment by eshellman** [comment]
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
