### PR TITLE
Added Math for Machine Learning by Marc Peter Deisenroth

### PR DESCRIPTION
**Pull request by aemiralfath**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource

### Description 
Mathematics for Machine Learning is a book developed by Marc Peter Deisenroth, A Aldo Faisal, and Cheng Soon Ong, with the aim of motivating people to learn mathematical concepts

### Why is this valuable?
The purpose of this book is to provide the math skills needed to read books on more sophisticated machine learning topics

### How do we know it's really free?
You can download the PDF of the book [here](https://mml-book.github.io/book/mml-book.pdf). Even though the book will be published this year, the author will continue to make the PDF book available for free download after publication.

### For book lists, is it a book?
Yes it's a book

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
When linking directly to a PDF, please added `(PDF)` at the end of the line.

**Comment by aemiralfath** [comment]
Thank you, I've added (PDF) at the end of the line and all checks have passed

**Comment by eshellman** [comment]
Nice addition! Maybe https://mml-book.github.io is a better link?

**Comment by aemiralfath** [comment]
Done, I've changed the link

**Pull request merged**
