### PR TITLE
free courses cc.md

### PR DESCRIPTION
**Pull request by Ash515**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Same problems as https://github.com/EbookFoundation/free-programming-books/pull/4710.

Please refer to the comment there.

**Comment by Ash515** [comment]
I don't know what is wrong in this PR I follow that contribution guidelines can you please explain to me what is the mistake.

**Comment by SethiPandi** [comment]
Ah sorry, I've looked again and I can see you've just made an honest mistake.

First, I would strongly recommend when you're making a contribution to a repository, that you always use a new branch based on the master branch unless you have reason to do otherwise? That will avoid issues like this from happening again!

For example:
```bash
# Checkout a branch called "my-first-contribution", create it if it doesn't exist.
git checkout -b my-first-contribution
```

Then when you've done that PR, and want to work on another one:
```
# Checkout master again any changes aren't in the active branch.
git checkout master

# Checkout a branch called "my-second-contribution", create it if it doesn't exist.
git checkout -b my-second-contribution
```

If you check the commit history of this pull request, you'll notice your commits from your previous pull request are still in here. You didn't reset the branch before continuing, so while you probably believe you've only made one change, you still have all the changes from your previous PR including here as well. You can also see this by checking the `Files changed` tab on GitHub.

I would recommend you back up the `free course cc.md` file you made, then do:

```bash
git reset --hard origin/master
```

Since you made your contribution to the master branch, this will be the easiest way to undo the changes you've made directly to your master branch, then you can create a new branch and make your changes there instead. After this, please try to submit your PR again.

---

When you resubmit your PR, could you please write the authors name normally, not in all caps, and see if these belong to an existing language, for example they look like English resources to me.

**Comment by eshellman** [comment]
The repo does not host books. Please read CONTRIBUTING.md guidelines

**Pull request closed without merging**
