### PR TITLE
Updated free-courses-hi.md and free-courses-en.md

### PR DESCRIPTION
**Pull request by jobin2233**
## PR Title
Updated free-courses-hi.md

### Description
Added all the available new links and sorted alphabetically.

### CODE REVIEW

**Comment by eshellman** [comment]
escape the `| `in titles

**Comment by jobin2233** [comment]
Should I replace it with -(hyphen).

**Comment by jobin2233** [comment]
I have sorted the lines 395 and 396 multiple times. what is the error?

**Comment by eshellman** [comment]
I've seen the linter report incorrect line numbers when there's a problem with the markdown syntax. line 199 is suspicious.

I'd suggest trying one section at a time.

**Comment by jobin2233** [comment]
I have sorted lines 403 and 404  AND removed the same tiltle on 127 and 197

**Comment by eshellman** [comment]
I think you just need to do the swaps suggested by the linter.

**Comment by jobin2233** [comment]
Here I have updated both free-courses-hi.md and free-courses-en.md . And I have added the available links and sorted alphabetically.

**Comment by eshellman** [comment]
Congratulations on getting the linter to accept this. 
I suggest that you remove the new link(s) and category so we can commit the linter-oriented changes separately. Once tht has been merged, create a NEW PR from a fresh branch for the added link. We won't accept "APTITUDE" as a category.
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category.

**Comment by jobin2233** [comment]
Here, as you have requested, I removed the new category and links and updated them.

**Comment by eshellman** [comment]
As you have seen, making lots of changes makes the PR susceptible to merge conflicts. If we accept it now, it will cause merge conflicts for many of the outstanding PR's (over 150 as I type this!!). So, I will mark this as "keep" and accept it after the Hacktoberfest rush has finished. Thank you for battling through this!

**Pull request closed without merging**
