### PR TITLE
Neovim Resource

### PR DESCRIPTION
**Pull request by dagenius007**
## What does this PR do?
Add resource

## For resources
Added neovim to list of IDE resources
Resolves this issue : https://github.com/EbookFoundation/free-programming-books/issues/11569

### Why is this valuable (or not)?
It was requested and a lot software Engineers are moving to vim just like myself

### How do we know it's really free?
It is clearly written on the github repo where it is been added

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Ajay-singh1** [comment]
Duplicate of #11582

**Comment by dagenius007** [comment]
> Duplicate of #11582.Kindly close this PR.

Just went through the PR , should we create a new section or add it under IDEs @Ajay-singh1 ? I will close it once you confirm this.

**Comment by Ajay-singh1** [comment]
> > Duplicate of #11582.Kindly close this PR.
> 
> Just went through the PR , should we create a new section or add it under IDEs @Ajay-singh1 ? I will close it once you confirm this.

If their is a section for IDEs we should add it under the IDEs. Thanks for the suggestion.

**Comment by Ajay-singh1** [comment]
@dagenius007 Can you Reopen your PR I had mistakenly made you closed it.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
