### PR TITLE
Updated the link to the book: Clean Architectures in Python -A practical approach to better software design by Leonardo Giordani (2nd Edition), to a direct link to the PDF file of the book.

### PR DESCRIPTION
**Pull request by SatyakiMandal**
## What does this PR do?
Improves the repository. A direct link to the PDF format of the book is now added.

## For resources

The website link for the book is, https://www.thedigitalcatbooks.com/pycabook-introduction/.
But the website to the original link was moved, so following the same, a direct link to the book's PDF was provided for the same.

### Description

The Book was published on LearnPub so essentially available for free.

### Why is this valuable (or not)?

The depreciated link was updated.

### How do we know it's really free?

Used the same link on multiple devices, the results are the same. It's FREE.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
look at the leanpub links in our list, and use that style please. yours is a "backdoor' link that disrespects the author.

**Comment by SatyakiMandal** [comment]
Link updated

**Comment by SatyakiMandal** [comment]
Make te required changes

**Comment by eshellman** [comment]
that works too

**Pull request merged**
