### PR TITLE
Bump PT-BR Courses

### PR DESCRIPTION
**Pull request by caiovlima**
## What does this PR do?
Add resources | Fix errors in some links

### Description 
Add Flutter Section and free Courses of that.
Add Angular Course

### Why is this valuable (or not)?
This resources is rich free material on pt-Br language

### How do we know it's really free?
Some resources take us on youtube channel, others in freemium education platforms

### For book lists, is it a book? For course lists, is it a course? etc.
This is a course.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists  in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
I think linter wants another linespace after flutter section

**Comment by caiovlima** [comment]
I fixed linespace and checked the links, but erros keeps going :/

**Comment by caiovlima** [comment]
thanks @eshellman i'm novice with this tools.
Now, if my pr its ok, whats the nexts steps ?

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
