### PR TITLE
Added free online course for ios development

### PR DESCRIPTION
**Pull request by SondreWang**
## What does this PR do?
Add Resource(s)

### Description 
Added a stanford course in IOS development that were uploaded to youtube and the stanford site for free due to the coronavirus.

### Why is this valuable (or not)
A good intro to developing apps with SWIFTUI, also more modern than the old with UIKit

### How do we know it's really free?
The videos are on youtube. No login required to get readings, assignments e.g.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Could you add a note about the teacher/presenter? Thanks.

**Comment by SondreWang** [comment]
As it is a Stanford course free and open to everyone i think adding the presenter (Stanford) might be ok.

**Comment by eshellman** [comment]
add 'stanford' as the attibution, then

**Comment by SondreWang** [comment]
is this ok?

**Comment by eshellman** [comment]
looks good

**Pull request merged**
