### PR TITLE
IPv6 book by Yar Tikhiy

### PR DESCRIPTION
**Pull request by Urlandi**
## What does this PR do?
Add Resource(s)

## For resources
 * [free-programming-books.md](https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books.md)
 * [free-programming-books-ru.md](https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books-ru.md)

### Description 
The complete IPv6 book in English and Russian language by Yar Tikhiy

### Why is this valuable (or not)
Because no IPv6 books present in this list

### How do we know it's really free?
There is license notes in the book on the first page

### For book lists, is it a book?
Yes

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
These look like good resources, but see CONTRIBUTING.md
"we don't accept files hosted on google drive, dropbox, mega, scribd, issuu and other similar file upload platforms"

**Comment by Urlandi** [comment]
Thank you @bluetata and @eshellman 

> These look like good resources, but see CONTRIBUTING.md

Yes, I read it carefully and long doubted about this form of URI. 

1. But I found "Introduction to Data Science" with same URI https://docs.google.com/file/d/0B6iefdnF22XQeVZDSkxjZ0Z5VUE/edit?pli=1 in [free-programming-books.md](https://github.com/EbookFoundation/free-programming-books/blob/master/free-programming-books.md)
2. _docs.google.com_ - not a file upload and store platform, formally, unlike _drive.google.com_
3. It is an official link by book author from his site on google site https://sites.google.com/site/yartikhiy/
4. Unfortunately there is no english version on other sites wich I know, only russians.

**Comment by eshellman** [comment]
I would use https://sites.google.com/site/yartikhiy/home/ipv6book for both english and russian books.

It's less likely to be obsoleted by revisions, and includes also an epub version

There was discussion about the data science book - an exception was made.

**Comment by Urlandi** [comment]
OK, @eshellman

>I would use https://sites.google.com/site/yartikhiy/home/ipv6book for both english and russian books.

I also think it is a good deсision. My commits has been updated with this URL.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
