### PR TITLE
Add finnish podcasts

### PR DESCRIPTION
**Pull request by endormi**
## What does this PR do?
Add Resource(s)

### Description 

Add finnish podcasts

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by endormi** [comment]
I don't why it took the previous commits, since I was inside a new branch, but I'll remove the first two

**Comment by endormi** [comment]
Sorry about the extra commits

**Comment by eshellman** [comment]
shouldn't it be Finnish/Suomi?

**Comment by endormi** [comment]
Oops, my bad

**Comment by endormi** [comment]
It's fixed now.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
