### PR TITLE
Update free-programming-books-pt_BR.md

### PR DESCRIPTION
**Pull request by tomasantunes**
## What does this PR do?
Add Resource(s)

### Description 
A free book about data science in brasilian portuguese.

### Why is this valuable (or not)
It's a new resource for this page.

### How do we know it's really free?
There is no price tag on the URL.

### For book lists, is it a book?
Yes

### Checklist:
- [x ] Not a duplicate
- [x ] Included author(s) if appropriate
- [x ] Lists are in alphabetical order
- [x ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by bluetata** [comment]
I am not sure whether an *account required* book  can be added into the repository now.

**Comment by eshellman** [comment]
1. this book is really "email requested"
2. it's only 12 pages - not much of an ebook
3. is it perhaps more of a promo piece? maybe a Portuguese speaker can say. @MrS4w ?

**Comment by MrS4w** [comment]
@eshellman This is more for a slideshow than a book, I wouldn't approve this changes. :sweat_smile:

**Comment by eshellman** [comment]
Thanks @MrS4w

**Pull request closed without merging**
