### PR TITLE
Add link to learn web development

### PR DESCRIPTION
**Pull request by Ruwanthi7**
[https://drive.google.com/drive/folders/1TDD4qLjlOdvo4kk_XV_JTNc_GqgtPYlz?usp=sharing](url)

### CODE REVIEW

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by chibanem** [comment]
new pull for hacktoberfest

**Comment by eshellman** [comment]
still conflicts

**Comment by SethiPandi** [comment]
Closing this as the resources are already in the repository.

**Pull request closed without merging**
