### PR TITLE
Update free-courses-en.md

### PR DESCRIPTION
**Pull request by Sanyam-2026**
## What does this PR do?
Added Chat GPT Prompt Engineering Course 
Add resource(s) | Remove resource(s) | Add info | Improve repo

### Description
This is the free and course available on free website deeplearning.ai
### Why is this valuable (or not)?
This is free and most specifically created by  Andrew Ng (Founder, DeepLearning.AI; Co-founder, Coursera) . For beginners it is best course to start with Chat Gpt
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
add the link to mach
Please read docs/CONTRIBUTING.md guidelines!ine learning or artificial intelligence.

**Comment by Sanyam-2026** [comment]
> add the link to mach Please read docs/CONTRIBUTING.md guidelines!ine learning or artificial intelligence.

Hey @eshellman I didn't understand can you please elaborate it , where I have to put the link

**Comment by eshellman** [comment]
sorry for typo. this addition should go in the AI or machine learning category

**Comment by eshellman** [comment]
Hmmmm this says "free for a limited time". I don't think we can list it.

**Pull request closed without merging**
