### PR TITLE
Add free c# programming online book

### PR DESCRIPTION
**Pull request by tanangular**
Add C# programming in thai language.

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by tanangular** [comment]
complete checklist

**Review by LuigiImVector — COMMENTED** [review]
Please check the linter error messages and fix the problems:
```
  12:1-12:118  warning  Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2  remark-lint
  16:1-16:75  warning  Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2  remark-lint
```

**Review by davorpa — APPROVED** [review]

**Review by LuigiImVector — APPROVED** [review]
LGTM

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
