### PR TITLE
migrate fpb-lint from travisci to gh actions

### PR DESCRIPTION
**Pull request by borgified**
## What does this PR do?
migrate the fpb-lint automation running on travisci to github actions

### CODE REVIEW

**Comment by eshellman** [comment]
can we hold off on removing travis-ci until we have enough experience to see that 
- the new config does what we want
- we can modify our documentation

**Comment by jc-mindstronghealth** [comment]
was tested here: https://github.com/borgified/free-programming-books/pull/8

**Comment by borgified** [comment]
was tested here: https://github.com/borgified/free-programming-books/pull/8
i did intentionally mess up the alphabetical ordering of a file and it picked it up but you dont see that cuz i forced pushed to remove extraneous commits.

**Comment by eshellman** [comment]
travis-ci and gh-actions-lint run on both push and pull-request; shouldn't it be the same for gh actions?
I'd really like to be able to compare the two side-by-side - will that cause any problems?

**Comment by borgified** [comment]
i think they both run on pull_request based on what ive seen on a few randomly selected PRs. (eg. https://github.com/EbookFoundation/free-programming-books/pull/5188/checks)

as configured, it will re-check if a change is made to the pull request.

**Comment by eshellman** [comment]
i'm just comparing the config files for the linter action and the link-check action and not that the "on" parameter is different. I've not so much as read the actions documentation, though.

**Comment by eshellman** [comment]
merged, but restored the travis config so we can compare results and not confuse folks before documentation has changed

**Pull request merged**
