### PR TITLE
Added Python and Java Playground

### PR DESCRIPTION
**Pull request by kevinlwebb**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s)

### Description 
SOLOLEARN offer courses, but they also provide an interactive playground to do simple code.

### Why is this valuable (or not)?
1. Free
2. Allows an user to perform quick operations when resources (Python / Java / etc) are not easily accesible

### How do we know it's really free?
You can access the website without registration.

### For book lists, is it a book? For course lists, is it a course? etc.
This is an interactive playground.

### Checklist:
- [X] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [X] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by kevinlwebb** [comment]
No author to add. Owned by SoloLearn, Inc.

**Comment by SethiPandi** [comment]
Could you please change the all caps SOLOLEARN to just the regular, SoloLearn?

The text should match the name of the resource, preferably including capitalization.

**Comment by eshellman** [comment]
agree with @SethiPandi

**Comment by kevinlwebb** [comment]
@SethiPandi @eshellman oops, sorry about that! I just looked at the logo and assumed it was all capitalized.

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
