### PR TITLE
Designing Data Intensive web application pdf copy

### PR DESCRIPTION
**Pull request by ARYASINGHBJC**
## What does this PR do?
Add resource
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by ARYASINGHBJC** [comment]
> ## What does this PR do?
> Add resource Add resource(s) | Remove resource(s) | Add info | Improve repo
> 
> ## For resources
> ### Description
> ### Why is this valuable (or not)?
> ### How do we know it's really free?
> ### For book lists, is it a book? For course lists, is it a course? etc.
> ## Checklist:
> * [x]  Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
> * [x]  [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
> * [x]  Include author(s) and platform where appropriate.
> * [x]  Put lists in alphabetical order, correct spacing.
> * [x]  Add needed indications (PDF, access notes, under construction).
> * [x]  Used an informative name for this pull request.
> 
> ## Follow-up
> * Check the status of GitHub Actions and resolve any reported warnings!

#8598

**Review by shrn01 — COMMENTED** [review]
Please provide official links to the resources. Please read [CONTRIBUTING](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md) for more information

**Comment by ARYASINGHBJC** [comment]
What if this book is not free for everyone? As I have O’Reilly free subscription using Github pro but it might be case that someone else don't have ! So is it okay if I mention O'Reilly link.

**Comment by shrn01** [comment]
No only resources which are truly free for everyone to use are accepted in this list

**Comment by ARYASINGHBJC** [comment]
Then I think this PR must be closed.

**Pull request closed without merging**
