### PR TITLE
Update free-programming-books-langs.md/ Added Fundamentals of Database Systems by Elmasri, Navathe

### PR DESCRIPTION
**Pull request by PranjalAsthana**
Added Fundamentals of Database Systems by Elmasri, Navathe.

## What does this PR do?
Add resource(s) - Added above mentioned book(pdf) under DBMS topic in books section

### Description
"Fundamentals of Database Systems" by Elmasri and Navathe is a highly regarded textbook offering a concise yet comprehensive exploration of database principles, design, and application. It's an essential resource for students and professionals, blending theory with practical insights.
### Why is this valuable (or not)?
Helpful to learn the basics of a Database System before jumping into DBMS. Covers databases in great detail and is widely used in colleges
### How do we know it's really free?
It's a directly accessible pdf
### For book lists, is it a book? For course lists, is it a course? etc.
It is a Book
## Checklist:
- [+] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [+] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [+] Include author(s) and platform where appropriate.
- [+] Put lists in alphabetical order, correct spacing.
- [+] Add needed indications (PDF, access notes, under construction).
- [+] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by sohansai — COMMENTED** [review]
This distribution is unauthorized; refer to docs/CONTRIBUTING.md for guidelines. 

Can you confirm the source of this free book? If not, we'll close the PR. 

The link is from a university faculty, seemingly for class use, but its legitimacy is uncertain.

**Comment by PranjalAsthana** [comment]
It is published by Addison-Wesley publications. What specifically can I provide to confirm the source of the book?
Also there is a 7th edition of this book that is published by Pearson. Shall I add that instead if this one is problematic?

**Comment by sohansai** [comment]
Use the link with the most authoritative source, like the author's website or the official website; review the guidelines in docs/CONTRIBUTING.md for more details.

**Comment by PranjalAsthana** [comment]
Can't find the author's website(one passed away, the other doesn't have a website) or any official page(there's an entry on pearson website which is paywall protected and against the guidelines), however the pdf of the book is hosted on several university websites and on github. Will those work?

**Comment by sohansai** [comment]
Your proposed sources do not align with our guidelines and are not acceptable.

**Comment by PranjalAsthana** [comment]
Should I use the github links then?

**Comment by PranjalAsthana** [comment]
Can you approve the PR?

**Comment by eshellman** [comment]
@PranjalAsthana The publisher of this book is Pearson, they are known for attacking this sort of distribution.

**Comment by PranjalAsthana** [comment]
ok understood. I'll keep this in mind when contributing. Thanks.

**Pull request closed without merging**
