### PR TITLE
Added Android (Module 2) - Spanish | Fixed Link

### PR DESCRIPTION
**Pull request by adelwolfart**
## What does this PR do?   
Add Resource(s)

### Description 

- Added Android Course in Spanish (Module 2).
- Fixed broken link "Seguridad informática práctica".

### Why is this valuable (or not)
Free course made by **Juan Díaz** (founder of _Píldoras Informáticas_) available all year round (permanent link).
**Website:** [https://www.pildorasinformaticas.es](https://www.pildorasinformaticas.es)
**YouTube:** [https://www.youtube.com/user/pildorasinformaticas](https://www.youtube.com/user/pildorasinformaticas)
### How do we know it's really free?
We can register and enroll in courses without the need for a payment method.
### Checklist:
- [x] Not a duplicate
- [ ] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
see #3924

**Comment by eshellman** [comment]
please resolve conflicts

**Comment by adelwolfart** [comment]
> please resolve conflicts

Resolved issues, sorry for the inconvenience.

**Comment by eshellman** [comment]
thanks for persevering!

**Pull request merged**
