### PR TITLE
Adding courses content

### PR DESCRIPTION
**Pull request by adamzebiche**
## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo
Adding resources, improving the repository.
### Description 
Adding courses from popular instructors.
### Why is this valuable (or not)
YES
### How do we know it's really free?
It's really free because this is mostly available on YouTube and 
### For book lists, is it a book?
No, videos and normal courses.
### Checklist:
- [ x] Not a duplicate
- [x ] Included author(s) if appropriate
- [ x] Lists are in alphabetical order
- [ x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by adamzebiche** [comment]
Why does Travis CI is saying Build Failed 😭

**Comment by Bharles-Cabbage** [comment]
Hey, all the resources must be in alphabetical order. So place your links in the right order and you'll be good to go.

**Comment by x0rld** [comment]
as I said in the #3914 the openclassroom courses are really deprecated and/or bad from the beginning

**Comment by innocenzi** [comment]
Some of the courses here should not be promoted. Namely, the PHP one from OpenClassrooms features a bunch of bad practices that beginners should not learn, and is super outdated. There is some good in there, but also a lot of bad (the hosting/architecture parts, the coding style, the fact that it doesn't teach about modern and common practices, and basically everything that is not "basic" has examples with bad practices). 

I heard a lot of other courses from them are bad as well, but I can only tell about the PHP one, which I've read since we've been referred to them by beginners that we help on French communities. 

Before this PR gets merged, the bad content should be filtered out from this list.

**Comment by eshellman** [comment]
I suggest that @innocenzi or @x0rld should make a new PR from this, starting with the current repo, which has seen several hundred commits since this PR was created. (reference it with "fix #3938" so it will auto-close). It has a lot of changes and has many conflicts, so would have to restarted anyway. OP has abandoned it. Don't hesitate to use editorial discretion!

**Pull request merged**
