### PR TITLE
Add the first julia cource

### PR DESCRIPTION
**Pull request by nagayev**
## What does this PR do?
Add resource

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [X] Search for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by nagayev** [comment]
@davorpa okey, thank you for quick response

**Comment by nagayev** [comment]
@eshellman this project is interesting and useful for me.
So I'm agree.

**Comment by nagayev** [comment]
@eshellman Hello. Is your invitation valid? 
I thought I would become a member of your organization.

**Comment by davorpa** [comment]
Take a look at #6373 too :wink:

**Comment by nagayev** [comment]
@davorpa thank you!

**Pull request merged**
