### PR TITLE
add pyqt books

### PR DESCRIPTION
**Pull request by jil8885**
Add online books about PyQt in Korean

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s)

### Description 
This PR modify free-programming-books-ko.md to add book about pyqt5

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Please add author names where appropriate.

**Comment by jil8885** [comment]
@eshellman I add not only author but also method as HTML because you can see book as website

**Comment by eshellman** [comment]
sorry I didn't catch this, but PyQt5 is too specific as a category.
It's not helpful to add a category for a single resource. Try to find another category - probably 'Python'.

**Comment by jil8885** [comment]
@eshellman I moved to contents under python section

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
