### PR TITLE
Add PingCAP's `TiDB Introduction` book

### PR DESCRIPTION
**Pull request by yanguwan**
Added a new section NewSQL and added the first course in the section

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [x ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [x ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x ] Include author(s) and platform where appropriate.
- [ x] Put lists in alphabetical order, correct spacing.
- [x ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by LuigiImVector** [comment]
We try to avoid creating a new section for a single resource whenever possible, maybe it could be placed on "NoSql"?

> NewSQL is a class of relational database management systems that seek to provide the scalability of NoSQL systems for online transaction processing (OLTP) workloads while maintaining the ACID guarantees of a traditional database system.

**Comment by yanguwan** [comment]
Usually, we do not think NewSQL is kind of NoSQL. NewSQL is a big progress that covers both of NoSQL and traditional SQL.

**Comment by eshellman** [comment]
We can add the section, but note we need to add it to the index as well. We have no books yet on Aurora, Couchbase, or the other NewSQL databases.

**Review by davorpa — APPROVED** [review]
LGTM

I've just added the TOC entry as suggested. Check again

**Pull request merged**
