### PR TITLE
add android course track by harvard

### PR DESCRIPTION
**Pull request by Larissagilliane**
## What does this PR do?
This PR adds a free course to teach Android basis made by Harvard

### Description 
This is a track course about Android from Harvard.

### Why is this valuable (or not)?
This is a course made by Harvard teaching Android. 

### How do we know it's really free?
At the 'CS50 Certificate' section you can read that you only need to pay for the certificate but the course is Free.

### For book lists, is it a book? For course lists, is it a course? etc.
This is a course.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
I think you want https://www.edx.org/course/cs50s-introduction-to-computer-science
Please add author names where appropriate.

**Comment by Larissagilliane** [comment]
@eshellman  I updated the authors name, but I think that its important to keep this Track as a course. Specially because its a course and Its easier to people who are looking for Android material to find in a specific place. 
What do you think?

**Comment by eshellman** [comment]
If you invent a title for this, it will be hard in the future to avoid unintentional duplicates. Use the title given by the resource.

**Comment by Larissagilliane** [comment]
@eshellman  I updated the course with the youtube playlist and the correct title. What do you think?

**Comment by eshellman** [comment]
Looks good. Thanks!

**Pull request merged**
