### PR TITLE
add tailwindcss documentation

### PR DESCRIPTION
**Pull request by batrasaurabh90**
add tailwindcss documentation

### CODE REVIEW

**Comment by batrasaurabh90** [comment]
## What does this PR do?
Add Resource to HTML/CSS.

## For resources
### Description 

### Why is this valuable (or not)
Increases the list of free programming resources for interested individuals in modern CSS frameworks.

### How do we know it's really free?
It's tailwind official document available on website.

### For book lists, is it a book?
No

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

**Comment by eshellman** [comment]
usually not a good idea to add a category for a single link

**Comment by batrasaurabh90** [comment]
@eshellman Point noted. PR updated.

**Comment by eshellman** [comment]
thanks, and welcome to free-programming-books!

**Comment by SethiPandi** [comment]
> usually not a good idea to add a category for a single link

Just a small question about the formatting of this PR.  
I'd just like to verify if this is 100% how a single link section/sub-section should be added.

Is it really better to make a link in the table of contents go to an external resource directly?  
* I can't imagine many users would expect a link in the table of contents to take them to an external page.  
* Users scrolling through the content will now miss the resource entirely, since some content is now in the table of contents instead.
* There are already _many_ single link sections, should they have been done the same way as this one then?
* If this is indeed how it should be, I think it should be mentioned in the CONTRIBUTING.md?

**Pull request merged**
