### PR TITLE
Add `Scaler Topics` links as english resources

### PR DESCRIPTION
**Pull request by Vaishnaviamirayada**
Have added a useful link about the programming language from the scaler topics

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by CleanMachine1 — APPROVED** [review]
lgtm

**Review by davorpa — CHANGES_REQUESTED** [review]
Please, solve linter error(s) raised by our GitHub Action:

```
/courses/free-courses-en.md
 107:1-132:97  warning  Alphabetical ordering: swap l.132 and l.131  alphabetize-lists  remark-lint
 224:1-234:85  warning  Alphabetical ordering: swap l.234 and l.233  alphabetize-lists  remark-lint
 239:1-244:77  warning  Alphabetical ordering: swap l.244 and l.243  alphabetize-lists  remark-lint
 258:1-266:69  warning  Alphabetical ordering: swap l.266 and l.265  alphabetize-lists  remark-lint
 315:1-331:108  warning  Alphabetical ordering: swap l.331 and l.330  alphabetize-lists  remark-lint
 353:1-360:68  warning  Alphabetical ordering: swap l.360 and l.359  alphabetize-lists  remark-lint
 518:1-544:71  warning  Alphabetical ordering: swap l.544 and l.543  alphabetize-lists  remark-lint
 549:1-580:83  warning  Alphabetical ordering: swap l.580 and l.579  alphabetize-lists  remark-lint
```

**Comment by davorpa** [comment]
@eshellman, where do you think scaler topic's resources fit better as?
- [ ] `courses/free-courses-*.md`: added here in this pr
- [ ] `books/free-programming-books-*.md`: currently there are 2 but duplicated as tutorials
- [ ] `more/free-programming-interactive-tutorials-*.md`: the most of them

**Comment by eshellman** [comment]
if these don't belong in interactive tutorials, nothing does

**Comment by davorpa** [comment]
Conflicts are with #7019 which moves Bootstrap section to right place. Please preserve both changes

**Comment by davorpa** [comment]
> if these don't belong in interactive tutorials, nothing does

Then needs move all to interactive tutorials and then this PR don't take sense if it don't do this so. Close or wait for @Vaishnaviamirayada changes?

**Comment by Vaishnaviamirayada** [comment]
Hi @davorpa ,

I have fixed the linter error(s) and remove "Bootstrap section" as I don't think that would fit there.

Let me know if any other changes are required.

**Comment by davorpa** [comment]
> Hi @davorpa ,
> 
> I have fixed the linter error(s) and remove "Bootstrap section" as I don't think that would fit there.
> 
> Let me know if any other changes are required.

Could you transfer all to interactive tutorials?

**Comment by Vaishnaviamirayada** [comment]
Hi @davorpa,

I am closing this PR as i think Scaler Topics links is already been added here: https://github.com/EbookFoundation/free-programming-books/blob/main/more/free-programming-interactive-tutorials-en.md

**Comment by davorpa** [comment]
> Hi @davorpa,
> 
> I am closing this PR as i think Scaler Topics links is already been added here: https://github.com/EbookFoundation/free-programming-books/blob/main/more/free-programming-interactive-tutorials-en.md

yes you are right, but I think only some of them. feel free to add the remaining 😉

**Pull request closed without merging**
