### PR TITLE
Added "30 Days Of Vue" Book

### PR DESCRIPTION
**Pull request by mdPial**
## What does this PR do?
Add resource

### Description 
It's a book which can be read in HTML format also in PDF format can be downloaded
### Why is this valuable (or not)?
UI is very clean and explained very well. Who loves to 30 Days Challenge it's perfect for them
### How do we know it's really free?
It's declared as an free book.
### For book lists, is it a book? For course lists, is it a course? etc.
It's a book
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists  in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
Thanks!

**Comment by linuxrooter** [comment]
Please send me direct download link for that book

**Comment by mdPial** [comment]
> Thanks!
😃️ welcome!

**Comment by mdPial** [comment]
> Please send me direct download link for that book

I don't know it's legal to provide direct link, by providing direct link I am not supporting the author. To get the direct link on you own is very simple.

**Pull request merged**
