### PR TITLE
add devops free bootcamp

### PR DESCRIPTION
**Pull request by s403o**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

### Why is this valuable (or not)?
This DevOps Bootcamp will provide a comprehensive overview of the DevOps approach and how it can be used to improve the speed, quality, and reliability of software delivery.

### How do we know it's really free?
It's free but needs registration at geeksforgeeks website, you can see point number 3 from geeksforgeeks to clarify
image

### For book lists, is it a book? For course lists, is it a course? etc.
it's a course

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
I was not able to access this course. It does not appear to be free to everyone.

**Comment by s403o** [comment]
It's free but need registration at geeksforgeeks website.

**Comment by s403o** [comment]
> @eshellman It's free but needs registration at geeksforgeeks website, you can see point number 3 from geeksforgeeks to clarify image

@eshellman please review this

**Comment by eshellman** [comment]
I tried to register but couldn't

**Comment by s403o** [comment]
> I tried to register but couldn't

I tried to register using Google and it works!
image

**Comment by eshellman** [comment]
can you register with an email address?

**Comment by s403o** [comment]
> can you register with an email address?

Ya, i tried now and it works also!

**Comment by eshellman** [comment]
I tried again. I think email login is restricted to the organizations they list. So not really free.
If you investigate further you can re-open the PR

**Pull request closed without merging**
