### PR TITLE
Added section Augmented Reality

### PR DESCRIPTION
**Pull request by Aadi1659**
## What does this PR do?
Add resource(s) | Improve repo

## For resources

Added the augmented reality section and added a free course link by coursera

### Description

This course will teach you the fundamentals of augmented reality (AR), and how to build an AR experience using ARCore. Through the four week course, you'll learn:

- How to identify different types of AR experiences 
- Tools and platforms used in the AR landscape 
- What makes AR feel "real" 
- Popular use cases for AR
- How to create an AR use flow 
- How AR experiences work
- Tools like Google Poly and Unity to build AR experiences 
- Next steps to start building an AR experience using ARCore and other tools  

This course will break down complex AR concepts to make them easy to understand, while also sharing expert tips and knowledge from Daydream's ARCore team. The course is great for beginners who are just getting started with AR or ARCore.

### Why is this valuable (or not)?

It is valuable due to the rapid growth of the AR technology in the modern world

### How do we know it's really free?

I have personally enrolled in this course and its completely free.

### For book lists, is it a book? For course lists, is it a course? etc.

This is a course

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Aadi1659** [comment]
Reordered Alphabetically

**Comment by Aadi1659** [comment]
Rearranged course link alphabetically as well

**Comment by eshellman** [comment]
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category.

**Comment by Aadi1659** [comment]
Added the Introduction to Introduction to Augmented Reality and ARCore in the computer-science section

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
