### PR TITLE
fix: archive past KDD cups and update main resource link to current year

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?
Improve repo

### Why is this valuable (or not)?

Solves urlchecker fault about this resource first time added at #4346. Related with #5470

  https://github.com/EbookFoundation/free-programming-books/runs/3835571930?check_suite_focus=true#step:6:102
  ```http
  Issues :-(
  > Links 
  3. [L069] 404 https://www.kdd.org/kdd2019/kdd-cup  
  ```   

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by LuigiImVector** [comment]
I don't see any useful information on these sites, am I wrong?

**Comment by davorpa** [comment]
> I don't see any useful information on these sites, am I wrong?

The competition requirements are in the menu. KDD 2022 is still in draft. KDD is a yearly competitive meetup.

@eshellman, it's better delete it?

**Comment by eshellman** [comment]
I agree, delete it

**Comment by davorpa** [comment]
> I agree, delete it

Done!

**Comment by zhengdi1992** [comment]
<自动回复>
你好，你的来信我已收到，尽快会给你回复。

**Pull request merged**
