### PR TITLE
Added a new Book under the Machine Learning section.

### PR DESCRIPTION
**Pull request by muhammadanas365**
In the Machine Learning section, I see there is no mention of one of the best  Machine Learning books out there: Hands-on Machine Learning with Scikit Learn, Keras, and TensorFlow by Aurelien Geron. So I thought I'd add it as it would be a very valuable addition to this FREE-SOURCE Repo!

## What does this PR do?
This PR adds a new book to the Machine Learning Section. The amazing book by Aurelien Geron has to be there, as otherwise, the list wouldn't be complete!

## For resources
The link is here: https://pk1lib.org/book/5232537/308ad6 via Z-Library!

### Why is this valuable (or not)?
This is super valuable, Aurelien Geron is one the most best authors I see regarding Machine Learning. His books are bestselling on Amazon and this book contains theory and a lot of hands-on experience! A valuable, yet free recourse.

### How do we know it's really free?
It's available on several websites for absolutely free! The first edition of the book is even on Github. I've downloaded the book, put in a google drive link, and shared it here, so users can directly access the PDF without doing anything!

### For book lists, is it a book? For course lists, is it a course? etc.
It's a book

## Checklist - **Checked all**
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by muhammadanas365 — COMMENTED** [review]
Sorry, had to change the link

**Comment by LuigiImVector** [comment]
It doesn't look like a free book, but it looks like a cracked book

**Comment by muhammadanas365** [comment]
It is free. The version of this book is also on Github!

**Comment by muhammadanas365** [comment]
I'll update the link to show the Github repo instead

**Comment by LuigiImVector** [comment]
You can edit the file by committing to the PR branch

**Comment by davorpa** [comment]
Duplicate of #6941

**Pull request closed without merging**
