### PR TITLE
Add Books from Flavio Copes and Courses from Dicoding Indonesia

### PR DESCRIPTION
**Pull request by levirs565**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s). Book from Flavio Copes and Courses from Dicoding Indonesia.

### Description 
Flavio Copes have a some free books. Flavio Copes book is in English Language. Flavio Copes Book only can downloaded if you register to his newsletter. Dicoding Indonesia is a Indonesian based programming course provider. Dicoding has free course and paid course. Only beginner course that available free in Dicoding. Dicoding Course is text based and has submission to check student knowledge. Dicoding course only have in Indonesian language.

### Why is this valuable (or not)?
The Flavio Copes books valuable for who want small book for reference or learning. Dicoding Indonesia course is valuable because beginner course has been cover all of programming concept. The course is for beginner and very valuable for who want start learning programming. Also the courses has a submission to check student knowledge and student cannot finish course before they pass course submission.

### How do we know it's really free?
You can open the link. For Dicoding Courses you can find text *Gratis* in Course Logo. *Gratis* in Indonesian mean **free**.

### For book lists, is it a book? For course lists, is it a course? etc.
Yes is is a books and courses.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
We discourage links that require working emails. Hard to test if it's still available. Please remove thise items.
Dicoding links are ok.

**Comment by levirs565** [comment]
Dicoding link also require a working email for registration in order to access course. Is this accepted?

**Comment by eshellman** [comment]
We're a lot more lenient about registration for courses, because of interactive features. And I think dicoding doesn't _require_ the email.

**Comment by levirs565** [comment]
I have removed the books from the Flavio Copes

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
