### PR TITLE
Created HOWTO-zh.md

### PR DESCRIPTION
**Pull request by CH-ND-N**
HOWTO-zh.md in Chinese

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
probably you should add a link to this from CONTRIBUTING-zh.md

**Comment by CH-ND-N** [comment]
sorry sir but I didn't get that can you please elaborate.

>

**Comment by CH-ND-N** [comment]
Sir, I am not sure if I interpreted it correctly. I have added a link to HOWTO.md  in HOWTO-zh.md.

**Comment by eshellman** [comment]
right, so add a link to HOWTO-zh.md in HOWTO.md.

**Pull request merged**
