### PR TITLE
Fix caps in frags

### PR DESCRIPTION
**Pull request by b-prithvi**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

### CODE REVIEW

**Review by shrn01 — CHANGES_REQUESTED** [review]
Please add the books in the respective markdown files and update the review. Look at [CONTRIBUTING.md](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md) for more information

**Comment by shrn01** [comment]
Head on to [First Contributions](https://github.com/firstcontributions/first-contributions) if you are facing any issue raising a PR

**Comment by eshellman** [comment]
please resolve conflicts. I think we already fixed this.

**Comment by eshellman** [comment]
PR is now moot. Thank you nonetheless.

**Pull request closed without merging**
