### PR TITLE
update course id

### PR DESCRIPTION
**Pull request by arufars**
## What does this PR do?
Add info name author

## For resources
(id) Belajar React JS Dari Awal Buat Yang Nggak Jago JavaScript 
(id) Belajar Machine Learning Dari Awal Buat Yang Ga Jago Matematika 
(id) Belajar Sass Biar Nulis Kode CSS Jadi "Absurd" 
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by shrn01 — COMMENTED** [review]
Is this change required?

**Comment by arufars** [comment]
yes this is very necessary as I want to put the name of the creator of the crash course

**Comment by eshellman** [comment]
for youtube playlists, we use the attributions provided by the creators

**Comment by arufars** [comment]
okay thanks

**Pull request closed without merging**
