### PR TITLE
Add a new javascript course in bengali (changes made)

### PR DESCRIPTION
**Pull request by AwesomeArunava**
## What does this PR do?
Add resource(s)

### Why is this valuable (or not)?
This Javascript course is beneficial for beginners.
### How do we know it's really free?
This is a YouTube playlist :)
### For book lists, is it a book? For course lists, is it a course? etc.
It's a course.
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Thenlie** [comment]
@eshellman It looks like this one is not alphabetical despite passing the lint check.

**Review by Thenlie — CHANGES_REQUESTED** [review]
@AwesomeArunava There should not be any changes to the `package-lock.json`. Please remove these from the PR.

**Comment by AwesomeArunava** [comment]
I remove the package-lock.json

**Comment by eshellman** [comment]
looks like the linter is not checking the bangla file for alphabetization. Could you please add this to a list in alphabetical order? thanks!
when you've made changes, please add `(changes made)` to the title of your PR

**Comment by AwesomeArunava** [comment]
ok, I will do it.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by AwesomeArunava** [comment]
Thank you and the team ❤️

**Pull request merged**
