### PR TITLE
Adding Practical Deep learning Course

### PR DESCRIPTION
**Pull request by himanshuc3**
Its a free and super cool course on deep learning by Harvard University.

### CODE REVIEW

**Comment by himanshuc3** [comment]
I just learned how to PR! I don't know how to build with Travis CI. Can anyone guide me here, pls!

**Comment by eshellman** [comment]
This looks like a great addition, thanks! You just need to add the entry in alphabetical order. The Travis-CI syntax checker runs automatically after you commit.

**Comment by himanshuc3** [comment]
Got it! So I'll try again...

**Comment by himanshuc3** [comment]
Finally the tests passed 😄

**Comment by eshellman** [comment]
Thanks for persevering!

**Pull request merged**
