### PR TITLE
Fix issue #11260: Added (PDF). CC BY-SA. to all links

### PR DESCRIPTION
**Pull request by PritamP20**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

### Description
This PR adds "(PDF). CC BY-SA." to all relevant book links, ensuring proper attribution and clarity for file format and license.

### Why is this valuable (or not)?
The added information provides users with licensing clarity and a consistent structure for identifying PDF resources. It's important for legal transparency and user experience.

### How do we know it's really free?
All the resources linked have already been vetted for being free. This PR only updates the format and license info.

### For book lists, is it a book? For course lists, is it a course? etc.
These are all books and resources listed in the markdown files.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by PritamP20** [comment]
Merge it 😄

**Comment by PritamP20** [comment]
merge it. all test cases have passed

**Comment by eshellman** [comment]
you didn't check the resources for licenses

**Comment by PritamP20** [comment]
Ok I will look into it again

**Pull request closed without merging**
