### PR TITLE
Added 2 new sources in problem-sets-competitive-programming.md

### PR DESCRIPTION
**Pull request by kn1-gh7**
Added 2 new sites for competitive programming  problem sets.

## What does this PR do?
Add resource(s)

### Description
The problem sets of C2 ladders and Atcoder Problems are added.
### Why is this valuable (or not)?
Its valuable as its recommended by Grandmasters on codeforces.
### How do we know it's really free?
These are wesites which just list problems.
### For book lists, is it a book? For course lists, is it a course? etc.
These are problem sets.
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by kn1-gh7** [comment]
@eshellman kindly check this PR and merge it. Thank you

**Comment by kn1-gh7** [comment]
@eshellman Kindly Review this PR and Merge it.

**Comment by eshellman** [comment]
These don't seem like "Problem Sets" to me. Care to explain? Remember, the goal of the lists is to help people find things.

**Comment by kn1-gh7** [comment]
> These don't seem like "Problem Sets" to me. Care to explain? Remember, the goal of the lists is to help people find things.

The C2 ladders is similar to a2oj ladders already existing in the problem sets file. These are a set of problems chosen from codeforces to help people.
The atcoder problems tries to achieve a similar goal for atcoder site by listing all problems to users thaf can be sorted according to user.

**Comment by eshellman** [comment]
Maybe we should create a category for ladders

**Comment by kn1-gh7** [comment]
> Maybe we should create a category for ladders

Hmm...your call. Many don't exist so it will be short one.

**Comment by kn1-gh7** [comment]
> Maybe we should create a category for ladders

Should I do this and submit a PR?

**Comment by eshellman** [comment]
renaming the file can create conflicts. maybe after nov 15 or so.

yes, please create a new subcategory. Start with the links from this PR. When that gets merged, create another to move links from the CTF category.

**Comment by kn1-gh7** [comment]
> renaming the file can create conflicts. maybe after nov 15 or so.
> 
> yes, please create a new subcategory. Start with the links from this PR. When that gets merged, create another to move links from the CTF category.

@eshellman Done. I have created Ladders subcategory. This category will now serve as collections of ladders (which are public collection of good problems hosted on other sites that host problem sets). I have added links from this PR add a few more links that were wrongly kept in other categories.

**Pull request merged**
