### PR TITLE
removed some dead links

### PR DESCRIPTION
**Pull request by Astrodevil**
i removed some dead links related to this website https://www.packtpub.com
in    free-programming-books.md

### CODE REVIEW

**Comment by eshellman** [comment]
I think you want to remove the listings, not just the URLs.

**Comment by Astrodevil** [comment]
Actually i am new on github .   

 you mentioned listings that means i have to remove whole line of code/ comments along with dead links??
make me correct if i understand wrong.

i would like to do the contribution

**Comment by eshellman** [comment]
yes, remove the whole line. not much use to list a book without a link.

**Review by Marusyk — CHANGES_REQUESTED** [review]
Please remove the whole line, not only links

**Pull request closed without merging**
