### PR TITLE
Al_Sweigart_Automate_The_Boring_Stuff_With_Python_Practical_Programmi…

### PR DESCRIPTION
**Pull request by FarhaKousar1601**
Al_Sweigart_Automate_The_Boring_Stuff_With_Python_Practical_Programming is best for beginner Python.

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by sohansai** [comment]
Not a valid contribution; read docs/CONTRIBUTING.md before contributing

**Review by sohansai — COMMENTED** [review]
Not a valid contribution; read docs/CONTRIBUTING.md before contributing

**Comment by FarhaKousar1601** [comment]
> Not a valid contribution; read docs/CONTRIBUTING.md before contributing

**Review by FarhaKousar1601 — COMMENTED** [review]
please unspam me ,

**Pull request closed without merging**
