### PR TITLE
(changes made) Add Hacktoberfest 2023 badge

### LINKED ISSUE #9839: Adding Hacktoberfest 2023 badge in Readme

### PR DESCRIPTION
**Pull request by isayakmondal**
## What does this PR do?
Improve repo

### Description
Adding the Hacktoberfest 2023 badge in the Readme.
### Why is this valuable (or not)?
This will give the README new info and updates about the Hacktoberfest 2023.
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

Closes #9839

### CODE REVIEW

**Comment by isayakmondal** [comment]
Well, the badge is not generating itself even after changing the URL parameter from 2022 to 2023, so I think someone who is part of the organization has to generate the badge or if it can be done by others as well please let me know how.

**Comment by eshellman** [comment]
we should remove the old one. also #9842

**Comment by isayakmondal** [comment]
> we should remove the old one. also #9842

@eshellman  Please take a look. Clicking the badge would also take the user to the PRs made between the month of October.
image

**Comment by isayakmondal** [comment]
@eshellman  Looks like Shields.io updated their official badge support for 2023 https://github.com/badges/shields/pull/9637#issue-1927719164, so I've added the official badge.
image

**Comment by Thenlie** [comment]
@isayakmondal Can #9839 be closed as a duplicate now? It looks like this PR is the most complete and seems to cover everything that has been asked.

**Comment by isayakmondal** [comment]
> @isayakmondal Can #9839 be closed as a duplicate now? It looks like this PR is the most complete and seems to cover everything that has been asked.

Yeah I think #9839 should be closed after this PR has been successfully merged.

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
