### PR TITLE
Added a new competitive programming book

### PR DESCRIPTION
**Pull request by Manishak798**
Guide to Competitive Programming

## What does this PR do?
Add resource(s)

### Description
I have added a new competitive programming book "Guide to Competitive Programming"
### Why is this valuable (or not)?
This book provides valuable insights to the programmer to start with competitive programming.
### How do we know it's really free?
The link for the book is freely available and easy to download as it is in PDF format.
### For book lists, is it a book? For course lists, is it a course? etc.
It is a book.
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Manishak798** [comment]
Kindly review my PR.

**Review by sohansai — COMMENTED** [review]
This distribution is not authorized; refer to docs/CONTRIBUTING.md for guidelines

**Comment by 3R1Dev** [comment]
@Manishak798 Are you able to provide the original location where the author shared this book for free? If not then we will close this PR.

**Comment by Manishak798** [comment]
NO, the author has not provided the original location of this book yet.

**Pull request closed without merging**
