### PR TITLE
Added Redux Toolkit course

### PR DESCRIPTION
**Pull request by ezeamaka2**
## What does this PR do?
Add resource(s)

### Description
Free redux toolkit tutorial for beginner

### Why is this valuable (or not)?
Teaches beginners how to use the redux toolkit

### How do we know it's really free?
The course is on youtube - freecodecamp's channel

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

**Comment by ezeamaka2** [comment]
> For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

Changes implemented

**Comment by ezeamaka2** [comment]
> For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes

The change have been implemented. Please review

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by ezeamaka2** [comment]
> please resolve conflicts.

the conflict has been resolved. Please review

**Pull request merged**
