### PR TITLE
fix grammar in German book list (review requested)

### PR DESCRIPTION
**Pull request by wamserma**
## What does this PR do?
Improve repo (minor grammar fix in headings)

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [X] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
requesting german review

**Comment by tobias-wilfert** [comment]
It is a bit awkward phrasing, something like: 'Programmiersprachen unabhängig' would probably be more correct.

**Comment by wamserma** [comment]
> 'Programmiersprachen unabhängig'

that should be 'programmiersprachunabhängig' then

**Comment by lxgr-linux** [comment]
> > 'Programmiersprachen unabhängig'
> 
> that should be 'programmiersprachunabhängig' then, or [as listed in the Wiktionary](https://de.wiktionary.org/wiki/programmiersprachenunabh%C3%A4ngig): 'programmiersprachenunabhängig'

Can verify.

**Review by sebgod — APPROVED** [review]
+1 to `Programmiersprachenunabhängig`

**Review by Mikeost — APPROVED** [review]

**Comment by eshellman** [comment]
Thanks everyone!

**Pull request merged**
