### PR TITLE
Update - Removed Non-working website links

### PR DESCRIPTION
**Pull request by chetannada**
Added Correct author website link for book `Go` and `Next.js`.
Previous links are broken or not working so i search over google and found correct Author website and download link for PDF

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
the handbook links are already in our book lists. I think the non-working links should just be deleted.

**Comment by chetannada** [comment]
> the handbook links are already in our book lists. I think the non-working links should just be deleted.

Hi @eshellman Okay, So Should i need to remove both full sentence?
for ex: `[Go Handbook](https://thevalleyofcode.pages.dev/go-handbook.pdf) - Flavio Copes, The Valley of Code (PDF)`
Please confirm so I will make changes and commit to this PR. Thanks.

**Comment by eshellman** [comment]
yes

**Comment by chetannada** [comment]
> yes

Hi @eshellman I Removed the both Non-working Links and commited the changes.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
