### PR TITLE
Fixing broken ui in case of "|"

### PR DESCRIPTION
**Pull request by lakshmi930**
## What does this PR do?
Improve repo

Fixes:
image

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by lakshmi930** [comment]
@eshellman noticed this issue when navigated to one of the language documents. Fixed the issue for other pages as well.

**Comment by eshellman** [comment]
thanks for this. We won't merge it until the hacktoberfest PRs are cleared out because of the potential to create conflict

**Comment by lakshmi930** [comment]
Hello @eshellman, thanks for your reply. Is this PR going to be merged as Hacktoberfest is now over?

**Comment by eshellman** [comment]
We've cleared about half of the backlog from Hacktoberfest - you can see how many of those are waiting for conflicts to be fixed!

**Pull request merged**
