### PR TITLE
Revert 1 main

### PR DESCRIPTION
**Pull request by bytesofbec**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by shrn01 — COMMENTED** [review]
All these are valid resources. Why are they removed

**Comment by bytesofbec** [comment]
Wait I apologize for this because this is actually a mistake. I was supposed to add new resources

**Comment by bytesofbec** [comment]
#9056 please check this pull requust

**Comment by bytesofbec** [comment]
#9056 please check this pull request and do the needful.

**Pull request closed without merging**
