### PR TITLE
Added Ruby Online Playground

### PR DESCRIPTION
**Pull request by Harshit-lab**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
please resolve conflicts. There was an issue with the farsi page that broke our builds.

**Comment by Harshit-lab** [comment]
Sure.. I'll just rectify them

**Comment by Harshit-lab** [comment]
Adhering to the guidelines mentioned in the contribyting.md I removed the branch with the URLs ending with forward slash

**Comment by eshellman** [comment]
the farsi were ok the way they were; changing them may cause other people merge conflicts. Your addition is fine however.

**Comment by Harshit-lab** [comment]
Okay, I'll revert the changes and resubmit the PR. Thanks

**Comment by Harshit-lab** [comment]
I have restored the changes and resubmitted the PR. Kindly have a look

**Pull request merged**
