### PR TITLE
Update free-programming-playgrounds.md to add some online compiler links

### PR DESCRIPTION
**Pull request by debnath003**
## What does this PR do?
Add resource(s) | Improve repo

### Description

Added some more online compiler links for Java, C#, and R programming language

### Why is this valuable (or not)?

Online compilers are necessary to evaluate a code or a program instantly, so I thought of adding it, which will help other students.

### How do we know it's really free?

The changes that I have made (the links which I have added) are completely free for usage

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by debnath003** [comment]
@eshellman please add hacktoberfest accepted label, this is my first time contributing, so it will be a great help

**Comment by debnath003** [comment]
@eshellman please add "hacktoberfest accepted" label so that it can be counted as my first time participating in Hacktoberfest! Thank you!

**Comment by debnath003** [comment]
@eshellman 

> @eshellman please add "hacktoberfest accepted" label so that it can be counted as my first time participating in Hacktoberfest! Thank you!

@eshellman this one

**Comment by debnath003** [comment]
@eshellman please add "hacktoberfest accepted" label so that it can be counted as my first time participating in Hacktoberfest! Awaiting your response! Thank you!

**Comment by debnath003** [comment]
> @eshellman please add "hacktoberfest accepted" label so that it can be counted as my first time participating in Hacktoberfest! Awaiting your response! Thank you!

@eshellman please consider this

**Comment by debnath003** [comment]
@eshellman please add hacktoberfest accepted label to this PR so that it can get eligibility for hacktoberfest

**Pull request merged**
