### PR TITLE
Add Shell Scripting Tutorial (course) by Steve Parker

### PR DESCRIPTION
**Pull request by Triple1996**
## What does this PR do?
Adds "Shell Scripting Tutorial" by Steve Parker to the list `free-programming-books/courses/free-courses-en.md`.

### Description
This is a tutorial designed to help people understand the basics of shell scripting and more specifically the Bourne Again Shell.

### Why is this valuable (or not)?

This tutorial is very approachable for newcomers and easy to follow along with.

### How do we know it's really free?

The author hosts it for free on his site, with an option to buy it as a PDF for offline use.

### For book lists, is it a book? For course lists, is it a course? etc.

It is a course

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by shrn01 — COMMENTED** [review]
Shouldn't this be under books?

**Comment by Triple1996** [comment]
It was difficult to determine, to be honest. The site has excercises at the end so I thought that would be more fitting of a course rather than a book. If we feel it fits the criteria of a book more than a course, I can move the entry under books.

**Comment by Triple1996** [comment]
also notifying that this is for an official hacktoberfest PR please

**Comment by eshellman** [comment]
It's advertising for a book. not usable as a course.

**Comment by Triple1996** [comment]
It was my understanding that the site hosts all the content of the book for free - on the left-hand side you can go to each of the 17 chapters and read through the lessons. Purchasing the material in a PDF version is just there as an option for offline use.

**Comment by Triple1996** [comment]
It was my understanding that the site hosts all the content of the book for free - on the left-hand side you can go to each of the 17 chapters and read through the lessons. Purchasing the material in a PDF version is just there as an option for offline use.

**Pull request closed without merging**
