### PR TITLE
Added  python and HTML/CSS course links for beginners as part of hacktoberfest2020 (PR resubmission)

### PR DESCRIPTION
**Pull request by athirakvp**
As  part of hacktoberfest20

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by kree666** [comment]
It's not in the correct alphabetical order, which is why the build failed.

**Comment by athirakvp** [comment]
The previously added link is alphabetically arranged now as per your instruction.Please verify and let me now

**Comment by kree666** [comment]
I'm not a reviewer, just trying to help :)
It looks like you have an incorrect number of blank lines between the last section and the next heading

**Comment by kree666** [comment]
It looks like you still have one extra blank line after the Python section and before the QB64 section that's causing the build to fail.

**Comment by eshellman** [comment]
@athirakvp  Could you add the creator/platform name after the link? Really helps to distinguish when the name is something like "Python Course".
@kree666 help much appreciated!

**Comment by eshellman** [comment]
no author for  the css course? also, follow the other listings in format `[title](link) - creator (platform)`

**Comment by athirakvp** [comment]
The list of courses is updated again

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
