### PR TITLE
Added new Terraform course in "courses/free-courses-en.md"

### PR DESCRIPTION
**Pull request by Manish-Syal123**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo
Add resources
### Why is this valuable (or not)?
It helps engineers automate the process of provisioning their cloud and hybrid infrastructure. With it, we no longer need to go into the cloud provider console - AWS, Azure or GCP - and set everything up manually.
### How do we know it's really free?
The 2 courses are available free on youtube and other 4 are free Udemy courses.
### For book lists, is it a book? For course lists, is it a course? etc.
It's a course
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by Manish-Syal123 — COMMENTED** [review]
changes made for Alphabetical ordering

**Review by Manish-Syal123 — COMMENTED** [review]
changed Alphabetical ordering

**Comment by eshellman** [comment]
please start with a fresh branch

**Comment by Manish-Syal123** [comment]
As I'm new to open source and you helped me a lot. Thanks for guiding me.

**Pull request closed without merging**
