### PR TITLE
Added Contributing-hi.md file (needs Hindi review)

### PR DESCRIPTION
**Pull request by ChandraDevs1**
## What does this PR do?
 Add  Contributing-hi.md file

### Why is this valuable (or not)?
 its valuable for those people how stack with english and not read contributing guide's  but they not Hindi after reading this .md they were know it 

#11298 solved .

### CODE REVIEW

**Comment by ChandraDevs1** [comment]
@eshellman  please check the solution 
Thank you

**Comment by ChandraDevs1** [comment]
I would You to please check it and if everything is clear then please merge this pr

**Comment by eshellman** [comment]
you have not resolved the merge conflicts correctly

**Comment by ChandraDevs1** [comment]
can you please describe it where is conflicts are ??

**Comment by eshellman** [comment]
read what you have now, you will see completely duplicated content. I suggest you start with a fresh branch

**Pull request closed without merging**
