### PR TITLE
Update free-programming-books-hi.md

### PR DESCRIPTION
**Pull request by PriyanshK09**
## What does this PR do?
Add resource(s)
added the following books to the markdown file:
- Computer architecture: कम्प्यूटर ऑर्गनाइजेशन एंड आर्किटेक्चर:- एम. ए. नसीम, राजस्थान टेक्निकल यूनिवर्सिटी,

### Description
This book is a comprehensive introduction to the fundamentals of computer organization and architecture. It covers a wide range of topics, including the basic structure of a computer system, the different types of computer components, and the principles of computer design. The book is written in a clear and concise style, and it is well-suited for students who are new to the subject.

### Why is this valuable (or not)?
This book is a valuable resource for students who are interested in learning about computer organization and architecture. It provides a solid foundation in the fundamentals of the subject, and it is well-written and easy to understand. The book is also up-to-date, and it covers the latest technologies and trends in computer architecture.

### How do we know it's really free?
The book is available for free download on the AICTE website. The AICTE is a government organization in India that is responsible for the development of technical education. The AICTE has made this book available for free download as part of its initiative to promote technical education in India.

### For book lists, is it a book? For course lists, is it a course? etc.
Yes, this is a book. It is a comprehensive introduction to the fundamentals of computer organization and architecture. It is written in a clear and concise style, and it is well-suited for students who are new to the subject. The book is also up-to-date, and it covers the latest technologies and trends in computer architecture.

## Checklist:
- [✔️ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [✔️ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [✔️ ] Include author(s) and platform where appropriate.
- [✔️ ] Put lists in alphabetical order, correct spacing.
- [✔️ ] Add needed indications (PDF, access notes, under construction).
- [✔️ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by 3R1Dev** [comment]
The order has to be alphabetical, swap lines 30 and 31 so you can pass the check.

**Comment by 3R1Dev** [comment]
Great job, now just add a space to follow the formatting guide.

There needs to be 2 spaces before the next heading.

**Comment by PriyanshK09** [comment]
> Great job, now just add a space to follow the formatting guide.
> 
> There needs to be 2 spaces before the next heading.

Thanks a lot bro!! First time up with Open Source contribution, newbie uk 😛

**Comment by 3R1Dev** [comment]
No worries!

Looks good just need to wait for the approval.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books! Nice PR.

**Pull request merged**
