### PR TITLE
Add Java

### PR DESCRIPTION
**Pull request by MuhamadAzizi**
Add java section and book

## What does this PR do?
Add Resource(s) 

### Description 
Java tutorial book by rosihanari

### Why is this valuable (or not)
It's good for beginners to learn java

### How do we know it's really free?
It's really free

### For book lists, is it a book?
Yes, it's a book

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
book doesn't seem to be available from that page.

**Comment by MuhamadAzizi** [comment]
I have changed java's book

**Comment by eshellman** [comment]
please use the author's blog as the source. Also, the author deserves credit! add the author's name

**Comment by MuhamadAzizi** [comment]
I've changed it, and I think this is the last one

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
