### PR TITLE
Create free-courses file for Persian

### PR DESCRIPTION
**Pull request by kavianam**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
these are moved from books, right? then they should be removed from books. please. Thanks, this will help a lot.

**Comment by kavianam** [comment]
@eshellman  I'm a novice and sorry for not being careful enough. I'm very happy to contribute.
I removed courses from free-programming-books-fa_IR.md, so courses now are in the free-courses-fa_IR.md

**Comment by SethiPandi** [comment]
You'll need to resolve merge conflicts with master before this can be merged, sorry!

Also, just a small comment.

During the move I can see you took some books from the Laravel section put them under PHP now.

Could you please keep them under the Laravel section?

The table of contents will look like:
```
* [PHP](#php)
  * [Laravel](#laravel)
```

And the content like:
```
### PHP

#### Laravel
```

This creates a Laravel subsection under PHP.

**Comment by kavianam** [comment]
@SethiPandi I added the Laravel section and moved corresponding courses into it. About conflicts, I added some courses into the free-programming-books-fa_IR.md by mistake that now I've fixed it.

**Comment by SethiPandi** [comment]
> @SethiPandi I added the Laravel section and moved corresponding courses into it. About conflicts, I added some courses into the free-programming-books-fa_IR.md by mistake that now I've fixed it.

I've noticed you've added the Laravel section now, thank you!

Regarding the conflicts, sorry! You haven't fixed them yet.
The GitHub interface should display as well: 
> This branch has conflicts that must be resolved

---

The rest of this isn't "advance", but does require some git knowledge, it's only worth reading if you reasonably comfortable with git's CLI.

If you're using git locally, you can just add EbookFoundation as another remote, then try pull the changes from there.

```bash
# Add another remote to your local repository called "source" (it can be called anything really)
# which points to this repo instead of your one.
git remote add source https://github.com/EbookFoundation/free-programming-books.git

# Pull all changes from all repos to your local repository.
git pull --all

# Merge the changes to source/master to origin/master,
# origin presumably being the name of the remote to your fork.
git merge source/master
```

The last command will most likely throw a warning and prompt you to resolve merge conflicts, you can then just resolve them, add, commit, and push your changes back up. That will fix the issue and make this a clean merge.

```
Auto-merging free-programming-books-fa_IR.md
CONFLICT (content): Merge conflict in free-programming-books-fa_IR.md
Automatic merge failed; fix conflicts and then commit the result.
```

There are two merge conflicts you'll want to resolve, this appears to be because you're deleting these entries from the file, but in master currently, someone did a commit that properly formatted them.

**Comment by kavianam** [comment]
@SethiPandi thank you for your awesome instructions, now I've fixed the conflicts. I thought the owner should resolve the conflicts.

**Comment by eshellman** [comment]
one last conflict! this sort of thing happens when there is a lot of activity.

**Comment by kavianam** [comment]
@eshellman it's been fixed.

**Comment by kavianam** [comment]
@eshellman should I do anything else to get accepted?

**Comment by eshellman** [comment]
yay!

**Pull request merged**
