### PR TITLE
Add "Vue JS na prática" to brazilian portuguese list

### PR DESCRIPTION
**Pull request by kavalcante**
## What does this PR do?
Add Resource(s)

### Description 
Add the free ebook Vue.js na prática in the Brazilian Portuguese list

### Why is this valuable (or not)
Vue.js in Portuguese has only a few options. This ebook covers how to use the framework from the scratch.

### How do we know it's really free?
You can check it out on the LeanPub website 😄 

### For book lists, is it a book?
Yes 🚀 

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by kavalcante** [comment]
Please, consider add the `hacktoberfest` topic to the repository, for my PR be valid as a contribution on Hacktoberfest 2020 ✋

**Comment by eshellman** [comment]
the repo has the keyword `hacktoberfest2020` which should be enough.
for leanpub, I think this link requires an account - take a look at other leanpub links to make sure you have the right annotation.

**Comment by kavalcante** [comment]
Unfortunately is not enough, as you can see in the images below:
Screen Shot 2020-10-07 at 21 51 23
Screen Shot 2020-10-07 at 21 51 31

I've added the Leanpub account info to the description!

**Comment by eshellman** [comment]
changed the keyword

**Pull request merged**
