### PR TITLE
Added 2 relevant courses for React in free-courses-en.md

### PR DESCRIPTION
**Pull request by Harman1107**
## What does this PR do?
Add resources 

### Description
Added 2 new courses specific to React which are relevant to today's scenario
### Why is this valuable (or not)?
Yes, these resources are valuable. Among a number courses available on udemy these have to the point explanations and  also come with timely assignments and graded evaluations.
### How do we know it's really free?
These are available for free on udemy and only require a free account to access them.
### For book lists, is it a book? For course lists, is it a course? etc.
1. The GraphQL Apollo (with ReactJS, NodeJS and MongoDB)
2. React Fundamentals - The Complete Guide For Beginners
## Checklist:
- [ x ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ x ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ x ] Include author(s) and platform where appropriate.
- [ x ] Put lists in alphabetical order, correct spacing.
- [ x ] Add needed indications (PDF, access notes, under construction).
- [ x ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
the resources are fine but you've added a random space

**Comment by Harman1107** [comment]
> the resources are fine but you've added a random space

Sir, I have removed the extra space

**Comment by Harman1107** [comment]
> the resources are fine but you've added a random space

Sir, if there are not errors then please merge this PR

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
