### PR TITLE
(zh)PHP composer and laravel and Vue.js

### PR DESCRIPTION
**Pull request by liluoao**
add PHP **composer** zh doc and **laravel** zh doc

### CODE REVIEW

**Comment by liluoao** [comment]
thanks

**Comment by eshellman** [comment]
nice additions, you just need to sort the items using the unicode collation. If you need help with that, just ask.

**Comment by liluoao** [comment]
@eshellman Yes,I need help.

**Comment by liluoao** [comment]
I used this:[https://github.com/vhf/remark-lint-alphabetize-lists](https://github.com/vhf/remark-lint-alphabetize-lists)

**Comment by liluoao** [comment]
You know the Chinese net has a gate, and I was hard to see the travis-ci's report.
Because I'm in a new company, and I forget to install a VPN.
Now it is finished.
Thanks!

**Comment by eshellman** [comment]
谢谢

**Pull request merged**
