### PR TITLE
Added Effective Java by Joshua Bloch

### PR DESCRIPTION
**Pull request by SharmaNishchay**
## What does this PR do?
Added Effective Java by Joshua Bloch (3rd Edition) in pdf format.

### Description
It's a collection of 90 best practices for developers. Those practices cover a wide range of mostly used Java features, including generics, exceptions, concurrency, serialization, lambdas and many others. A lot of relevant code examples showing both the good and the bad code followed by a robust explanation.
### Why is this valuable (or not)?
This book helps in understanding how to write an effective code in Java.
### How do we know it's really free?
Have provided a direct link to the pdf (source: internet archive which is a free website).
### For book lists, is it a book? For course lists, is it a course? etc.
Book.
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by sohansai** [comment]
This type of link isn't allowed according to contributing guidelines, and there is already a functional link source available. 

You can review the guidelines here: [Contributing Guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)

**Comment by SharmaNishchay** [comment]
> This type of link isn't allowed according to contributing guidelines, and there is already a functional link source available.
> 
> You can review the guidelines here: [Contributing Guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)

I did not get the comment properly can you please help me understand the difference better

**Comment by eshellman** [comment]
remove the dot files

**Comment by SharmaNishchay** [comment]
> remove the dot files

I did not get that can you please elaborate more

**Comment by eshellman** [comment]
the files in  `.idea`

**Comment by SharmaNishchay** [comment]
Shall I remove all these files from .idea file?
free-programming-books.iml
misc.xml
modules.xml
vcs.xml
workspace.xml

**Comment by SharmaNishchay** [comment]
I had removed the dot files, any other changes?

**Comment by SharmaNishchay** [comment]
Sir , since it has passed all the checks, kindly provide the "Hacktoberfest-accepted label" or "PR be merged" (as stated in Hacktoberfest PR/MR guidelines) for it to be considered in the Hacktoberfest accepted PR/MR.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
