### PR TITLE
Update free-courses-en.md

### PR DESCRIPTION
**Pull request by Akashgiri1020**
i have made changes that you want

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Akashgiri1020** [comment]
plz accept it i have made changes

**Comment by davorpa** [comment]
> plz accept it i have made changes

@Akashgiri1020 **I suggest you read carefully the notes on how to proceed when requesting changes.**

You should stop submitting more PR to try to fix the work. Take your time to read and apply steps I suggested you in the other closed PRs.

**Review by davorpa — APPROVED** [review]
### Ready to merge :fireworks: :tada:

**Review by Akashgiri1020 — COMMENTED** [review]
i have seen from myself

**Review by Akashgiri1020 — COMMENTED** [review]
approved

**Pull request merged**
