### PR TITLE
Please add Django 2.0 Online Book

### PR DESCRIPTION
**Pull request by H3li0**
I would like to add this online book of Django 2.0 to the list.

Thanks in advance.

### CODE REVIEW

**Comment by H3li0** [comment]
My link has the ending slash "/".
I do not understand.  :-/

**Comment by Devinsuit** [comment]
@H3li0 could you remove slash, please?

**Comment by eshellman** [comment]
Nice addition! Thanks for the extra effort to satisfy the linter.

**Comment by eshellman** [comment]
Note. The linter flags the trailing slash when it follows the hostname, i.e. when the path is "/". I agree it's a bit too picky; maybe a PR to https://github.com/vhf/free-programming-books-lint is in order

**Pull request merged**
