### PR TITLE
Create CODE_OF_CONDUCT-ml.md (review requested)

### PR DESCRIPTION
**Pull request by hakunamatata1997**
Added translation for malyalam

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
need to also add link in docs/README.
Will ask for review help.

**Review by gaurovgiri — APPROVED** [review]

**Review by hakunamatata1997 — COMMENTED** [review]
Added in README.md

**Comment by eshellman** [comment]
no, not `README.md` -  `docs/README.md`

**Comment by Vaporjawn** [comment]
Hey @eshellman I'm back again with another PR to address your requested change #11010

**Comment by eshellman** [comment]
merged in #11010

**Pull request closed without merging**
