### PR TITLE
Add R cheatsheets

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?
Add resource(s)

### Description
- Add some R cheatsheets to new section.

### Why is this valuable (or not)?
- Adds a new section to to cheetsheet list.
- Links to RStudio cheetsheets page.
- 2 cheatsheets about data wrangling.

### How do we know it's really free?
Available on www.rstudio.com/resources/cheatsheets

### For book lists, is it a book? For course lists, is it a course? etc.
Are cheatsheets resources

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
it looks like the data wrangling cheatcheats are included on the RStudio cheatsheet site? Perhaps the way to deal with this is to just offer a bit more description about the RStudio site.

**Comment by davorpa** [comment]
> it looks like the data wrangling cheatcheats are included on the RStudio cheatsheet site? Perhaps the way to deal with this is to just offer a bit more description about the RStudio site.

Your suggestion is to remove each PDF cheatsheet and leave only site link adding a note, eg. `(site with PDF in all languages)` ?

I realized that there are some early PDF cheatsheets in English not visible in the site list until general searchbox is used (eg. "Data Wrangling..."), neither in github repo.
The first time I found it was in Pandas cheetsheet #5430 footer.
Translated versions are all listed, so spanish PDF can be removed from PR.

Then, how to organize linkings in this case? Maybe, I thought, nest into sub unordered list. Do you agree? Or not is necessary?

**Comment by eshellman** [comment]
The two considerations are 
1. How can we be most useful for someone looking for an R cheatsheet?
2. What will be easiest for us to maintain?

Probably sending the user to RStudio is the answer to both.

**Comment by davorpa** [comment]
> The two considerations are
> 
> 1. How can we be most useful for someone looking for an R cheatsheet?
> 2. What will be easiest for us to maintain?
> 
> Probably sending the user to RStudio is the answer to both.

Then, let's Keep It Simple. Thanks for instruct me in my first PRs. It helps me to improve next contributions.

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
