### PR TITLE
Create Code_of_conduct-ben.md

### PR DESCRIPTION
**Pull request by Sanhati**
Bengali translation of the Code of conduct

## What does this PR do?
adds info in another language

### Why is this valuable?
valuable for the ones who are comfortable in Bengali.

### CODE REVIEW

**Comment by eshellman** [comment]
use bn language code, not ben

**Comment by Sanhati** [comment]
I have used the language code bn

**Comment by Sanhati** [comment]
I have used bn language code, please review the newly made changes

**Comment by eshellman** [comment]
please add link in docs/README.md

**Pull request merged**
