### PR TITLE
Update free-programming-books.md

### PR DESCRIPTION
**Pull request by thewhitetulip**
added my awk tutorial https://github.com/thewhitetulip/awk-anti-textbook

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
link is a 404

**Comment by thewhitetulip** [comment]
updated. sorry, had given wrong link

**Comment by eshellman** [comment]
ok....

**Comment by teeg123** [comment]
Thank you sir, but how do I get to access  it  looks complicated to me  Sent from Mail for Windows 10 From: Eric HellmanSent: Monday, April 20, 2020 4:37 PMTo: EbookFoundation/free-programming-booksCc: SubscribedSubject: Re: [EbookFoundation/free-programming-books] Update free-programming-books.md (#3554) ok....—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by thewhitetulip** [comment]
@teeg123 you have to click on the github link.

**Pull request closed without merging**
