### PR TITLE
fix(books): free-programming-books-ru broken links

### PR DESCRIPTION
**Pull request by LuigiImVector**
## What does this PR do?
Remove resource | Improve repo

### Description

Solved a problem of #6942.

- `http://networksciencebook.com/` has only two chapters translated into Russian, do we keep it?
- `https://www.fprog.ru/` works
- `https://metanit.com/*/*` they all work
- `http://www.mcst.ru/doc/book_121130.pdf` works
- `http://lisper.ru/wiki/Cookbook`, `younglinux.info/linuxintro` deleted because in archive.org not all the chapters works

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [X] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [X] Put lists in alphabetical order, correct spacing.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
for http://networksciencebook.com/ maybe add `under construction`

**Comment by LuigiImVector** [comment]
> for http://networksciencebook.com/ maybe add `under construction`

I added `(:construction: *in process*)`, is that okay?

**Comment by eshellman** [comment]
where did you add the * in process * note?

**Comment by LuigiImVector** [comment]
> where did you add the * in process * note?

I hadn't pushed, sorry

**Pull request merged**
