### PR TITLE
Books on web accessibility and free plugins to implement in applications

### PR DESCRIPTION
**Pull request by HarukaIonaSao**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by shrn01 — COMMENTED** [review]
Please add the resources to proper files and raise a PR. Read docs/CONTRIBUTING.md for more information

**Comment by HarukaIonaSao** [comment]
OK thank you. Sorry for the inconvenience. I will adjust to redo the
pull request.


Em ter., 25 de out. de 2022 às 14:41, Sharan J ***@***.***>
escreveu:

**Comment by eshellman** [comment]
please remove your invisible file from the PR

**Comment by HarukaIonaSao** [comment]
how do I do that? The only hidden file is the .git.
I will review the files and try to pull again. Can you delete the
current P since I don't know how to edit it? Thanks


Em ter., 25 de out. de 2022 às 15:51, Eric Hellman ***@***.***>
escreveu:

**Pull request closed without merging**
