### PR TITLE
Added C언어 코딩도장 as course in C/C++ section (RESTORED REMOVED ADDITIONS)

### PR DESCRIPTION
**Pull request by jihongeek**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo
Add Resource
### Description 
  It's a C course of the series of "코딩도장"(it means coding dojo)  
### Why is this valuable (or not)?
  It's nice free C course
### How do we know it's really free?
   Because there is copyright description in site's footer (it's free but DO NOT COPY AND SHARE CONTENT. THE COPYRIGHT IS OWNED BY AUTHOR AND BOOK COMPANY YOU CAN ONLY SHARE "LINK")
### For book lists, is it a book? For course lists, is it a course? etc.
  Course
### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
please resolve conflicts. 
This is a course. please add it to the courses-ko list instead.

**Comment by jihongeek** [comment]
I just didn't realize this is a course...lol thank you 😄

**Comment by eshellman** [comment]
when resolving conflicts don't remove other people's additions!

**Comment by jihongeek** [comment]
Sorry 😭, I restored removed additions... please check!

**Pull request merged**
