### PR TITLE
Add Regular Expressions Cookbook, check_urls=free-programming-books.md 

### PR DESCRIPTION
**Pull request by kadhirash**
## What does this PR do?
Add Resource

### Description 
Regular Expressions PDF file 
### Why is this valuable (or not)?
Amazing PDF resource for free via a secure https link!
### How do we know it's really free?
Testing the url leads to a PDF version of the book
### For book lists, is it a book?
Yes
### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
This doesn't appear to be an official or authoritative source for the book.

As far as I can tell, this is not a free book. However, if you're able to find a first party or authoritative source for the resource, for example, the author, publisher, or an authorized distributor, then feel free to update the link to that instead.

**Comment by kadhirash** [comment]
It was hosted on Jerzy Karczmarczuk's website, via the University of Caen Normandy so I thought it was official enough as it also leads to a free PDF. However, if that doesn't count, I don't mind closing this PR.

**Comment by SethiPandi** [comment]
I judged based on 2 things:
* It's O'Reilly, but not the O'Reilly website.
* The name of the professor (Jerzy Karczmarczuk) doesn't appear to be any of the authors on the book (Jan Goyvaerts and Steven Levithan).

I'm not going to make a definitive statement like it _certainly_ is, or isn't a good source. I can't say with certainty if it's not truly free, for example he might have a private arrangement with the authors or O'Reilly to redistribute the book at his discretion, but this is unlikely and I see no evidence of that. (ie any educational institution or professor can redistribute work, doesn't mean it's authorized)

If you disagree, or have reason to believe otherwise, you're more than welcome to keep it open. Perhaps I'm wrong, I would hate for this to be unmerged if it's indeed a valid contribution.

**Comment by kadhirash** [comment]
Yeah I see where you are coming from. I will keep the PR open for now, but if it gets closed later it is understandable as to why

**Comment by SethiPandi** [comment]
It's a bit unfortunate, I can see from Steven Levithan's blog that the book indeed used to be free:

> O'Reilly offers DRM-free ebook copies in PDF, Mobi, and ePub formats.
> \- http://blog.stevenlevithan.com/

But I'm unable to find any such link on the O'Reilly website.

O'Reilly have had a few books like this in the past, where it was previously free, but not anymore, or at least damn near impossible to find, favoring buying the book or e-book instead.

One example is a book I read called [Understanding Open Source and Free Software Licensing](https://www.oreilly.com/library/view/understanding-open-source/0596005814/), the DRM free version is available [here](https://www.oreilly.com/openbook/osfreesoft/book/) (original author sent it to me since I couldn't find it) in a broken webpage that's no longer maintained divided into a download per section, and can't be found via search... ^-^'

**Comment by eshellman** [comment]
Thanks for understanding - this book is not free.

**Comment by slevithan** [comment]
I’m one of the authors of both the first and second edition of Regular Expressions Cookbook.

This is not a free book.

Thanks for taking the time to try to get this right.

@SethiPandi the mention of being DRM free is just that. If you buy a digital copy from O’Reilly Media, your personal copy will not be encumbered with DRM.

**Comment by kadhirash** [comment]
@eshellman @SethiPandi @slevithan awesome, thank you for helping me understand! 😅

**Pull request closed without merging**
