### PR TITLE
ci(check-urls): fix push crash on new branch creation + render awesome_bot report

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?
Improve repo

## Description

I'm improving `check-url` workflow. At this moment, I've:

### Fixed a wellknown crash 505592eea63b3213ad3c56bcc0a2d0576e610657

... fixed the crash when push event is fired the first time on a new branch. I've just change the used action (not mantained since 2020) by other one: [`tj-actions/changed-files`](https://github.com/tj-actions/changed-files). 

Also is faster since is written in bash and doesn't need Node interpreter to be runned.

### AwesomeBot run report 3d0c1091a413807cc066f37a10700ff5b19aa6d7

... added a final step to generate a report summary for the action viewable from their run details. Some outputs:

| With no issues | Having issues |
|:----------------:|:---------------:|
| [See Output](https://github.com/davorpa/free-programming-books/actions/runs/2943323971#summary-8058208277) | [See Output](https://github.com/davorpa/free-programming-books/actions/runs/2943435942#summary-8058417662) |
| With no issues | Having link issues |

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
maybe @sashashura can review

**Comment by sashashura** [comment]
Permissions look good to me. It seems `tj-actions/changed-files` doesn't need any additional permissions except content read. It is a bit of trial and error since I'm not aware of a way to test it locally. If it fails when merged try adding `pull-requests: read`, but I think it is not needed. Just ping me and I'll take a look. Happy to help.

**Comment by davorpa** [comment]
Conflicts are with #7043 but already applied in commit f56c289721bc865f8bf1e488dd96db4d5120223f .

So... peserve all ours file

**Comment by eshellman** [comment]
ready to merge?

**Comment by davorpa** [comment]
> ready to merge?

Sure! no more commits

**Pull request merged**
