### PR TITLE
Add Docker and Kubernetes courses and adjust sub headings

### PR DESCRIPTION
**Pull request by JohanneA**
## What does this PR do?
Add Resource(s) | Improve Repo

### Description 
Added two online courses for learning Docker and Kubernetes

### Why is this valuable (or not)
Docker and Kubernetes are valuable things to know given the shift towards cloud-based environments 

### How do we know it's really free?
It's under their free courses section and you can access it immediately 

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
please add a notation with the name of the platform

**Comment by JohanneA** [comment]
Done

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by JohanneA** [comment]
Also done

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by JohanneA** [comment]
Done

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
