### PR TITLE
Added free course for Ethical hacking

### PR DESCRIPTION
**Pull request by DebugAgrawal**
## What does this PR do?
Add Resource(s) 

### Description 
Hacker101 provides tutorials for ethical hacking for free it covers all the aspects required to be a good ethical hacker.
### Why is this valuable (or not)
Most of the Newbie cyber security enthusiasts don't know where to start  learning ethical hacking, Hacker101 provides knowledge through tutorials from basics.
### How do we know it's really free?
Just visit the website and there is option to play the tutorials no login required.
### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by DebugAgrawal** [comment]
Is it a quality PR now ?

**Comment by DebugAgrawal** [comment]
Please review if any changes to be done

**Comment by eshellman** [comment]
please lose the word "Cyber".

**Comment by DebugAgrawal** [comment]
> please lose the word "Cyber".

Hey its done👍

**Comment by eshellman** [comment]
in the books list, this is just "Security"

**Comment by DebugAgrawal** [comment]
> in the books list, this is just "Security"

Ok I'll do that

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by DebugAgrawal** [comment]
> Thanks, and welcome to free-programming-books!

Welcome Sir.Glad to be part of it 😊😬
_Happy Contributing_ 🚀

**Pull request merged**
