### PR TITLE
Add Mathematic Book

### PR DESCRIPTION
**Pull request by SenukDias**
## What does this PR do?
Add resource

## For resources
Guide to discrete mathematics 2016 -  David Gries,Fred B. Schneider
### Description
The objective of this book is to give the reader a flavor of discrete mathematics and
its applications to the computing field. The goal is provide a broad and accessible
guide to the fundamentals of discrete mathematics, and to show how it may be
applied to various areas in computing such as cryptography, coding theory, formal
methods, language theory, computability, artificial intelligence, theory of databases,
and software reliability. The emphasis is on both theory and applications, rather
than on the study of mathematics for its own sake.
There are many existing books on discrete mathematics, and while many of these
provide more in-depth coverage on selected topics, this book is different in that it
aims to provide a broad and accessible guide to the reader, and to show the rich
applications of discrete mathematics in a wide number of areas in the computing
field.
Each chapter of this book could potentially be a book in its own right, and so
there are limits to the depth of coverage for each chapter. However, the author
hopes that this book will motivate and stimulate the reader, and encourage further
study of the more advanced texts.

### Why is this valuable (or not)?

valuable

### How do we know it's really free?

actually it's free knowledge

### For book lists, is it a book? For course lists, is it a course? etc.

yes this is a Book

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by SenukDias — COMMENTED** [review]
new

**Review by SenukDias — COMMENTED** [review]
update place

**Review by SenukDias — COMMENTED** [review]
new

**Comment by eshellman** [comment]
The repo does not host books. Please read docs/CONTRIBUTING.md guidelines. If the book is free licensed, consider depositing in archive.org or unglue.it

**Pull request closed without merging**
