### PR TITLE
Update name of the translator

### PR DESCRIPTION
**Pull request by quangnh89**
I myself translated 'The Little Go Book' into Vietnamese. I am only updating it to correct the translator's name.

### CODE REVIEW

**Comment by HSUYATANG** [comment]
So is it to change the Vietnamese name of this program? Because it looks the same as English.

So how do you think it's different from the previous watch?

**Comment by quangnh89** [comment]
> So is it to change the Vietnamese name of this program? Because it looks the same as English.
> 
> So how do you think it's different from the previous watch?

I want to keep the original name of this book. I just translated content.

**Comment by eshellman** [comment]
Please accept the suggest change to your PR if you agree with it.

**Comment by quangnh89** [comment]
LGFM. What should I do now?

**Comment by eshellman** [comment]
you should have a button to accept the suggestion

**Pull request closed without merging**
