### PR TITLE
Add the book "Programming for Non-Programmers"

### PR DESCRIPTION
**Pull request by tunggnu**
## What does this PR do?

Add resource(s)

### Why is this valuable (or not)?

It teaches programming for non-programmers using Python 2.6.

### How do we know it's really free?

It is available under the [Creative Commons Attribution-Noncommercial-No Derivative Works License](http://creativecommons.org/licenses/by-nc-nd/2.0/).

### For book lists, is it a book? For course lists, is it a course? etc.

It is a nearly 500 page book.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
I think the author removed it from his website because the python version is so old.
Is he right about the viability of the book? (also a reason not to use the ND license, everybody.)

**Comment by tunggnu** [comment]
Yes, it uses Python 2.6, a very old version. But as a programmer, I think it's still useful for reference. It's a serious book about programming in general, not just Python in particular. The author also published a newer edition for Python 3.2, but it's not free. Maybe that's why he deleted the old edition. 

Please help me understand what is wrong with the Creative Commons Attribution-Noncommercial-No Derivative Works License. I see that this license allows anyone to **read** the book freely.

**Comment by eshellman** [comment]
ND means only the author can revise for new python versions.

**Comment by tunggnu** [comment]
Right. That license is not beneficial for those who want to revise the book to make another book. But ordinary learners who are the book's primary audience can freely read and experiment for their own learning, as long as they don't create a new book out of it. So I think No Derivative licenses are adequate for learners.

**Pull request merged**
