### PR TITLE
Updated Link from Pro Git to new book version

### PR DESCRIPTION
**Pull request by bastianschott**
This PR is a copy from [#3152](https://github.com/EbookFoundation/free-programming-books/pull/3152). I deleted my fork after pull so the update didn't integrate into my previous PR. @bluetata 

## What does this PR do?
For the german book "Pro Git" is a new version available. Updated the link for it.

### How do we know it's really free?
License notes are on the first page available.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Maybe it would be good to list both versions, since the v1 translation is smore complete than the v2 version; also maybe add a german "in-progress" annotation (see CONTRIBUTING.md)

**Comment by bluetata** [comment]
I suggest you can try to change it from
```
* [Pro Git 2009](http://git-scm.com/book/de/v1)
* [Pro Git - neue Version](http://git-scm.com/book/de/current) (:construction: *in process*)
```
to
```
* [Pro Git 1st Edition (2009)](http://git-scm.com/book/de/v1)
* [Pro Git 2nd Edition (2014)](http://git-scm.com/book/de/current) (:construction: *in process*)

<!-- or  -->

* [Pro Git (2009)](http://git-scm.com/book/de/v1)
* [Pro Git (neue Version)](http://git-scm.com/book/de/current) (:construction: *in process*)

<!-- or  -->

* [Pro Git (2009)](http://git-scm.com/book/de/v1)
* [Pro Git (2014)](http://git-scm.com/book/de/current) (:construction: *in process*)

```

**Comment by bastianschott** [comment]
I took the 2nd suggestion, because the current-tag does not guarantee, that v2 will ever be the newest version. Thank you!

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
