### PR TITLE
Updated broken link

### PR DESCRIPTION
**Pull request by bojandevic**
Updated broken link for: "Mostly Adequate Guide to Functional Programming"

### CODE REVIEW

**Comment by SethiPandi** [comment]
Hey and welcome to free programming books! :wave:

This is more of a heads up for anyone else reviewing this.
It seems this book is only available in HTML at the moment, since the links for the PDF, EPUB, and MOBI are broken.
(Though users can compile them themselves.)

Someone has already reported the problem though: https://github.com/MostlyAdequate/mostly-adequate-guide/issues/586

**Comment by bojandevic** [comment]
> Hey and welcome to free programming books! 
> 
> Thanks for fixing the link, I can see the old one just redirected to the GitBook homepage.
> 
> This is more of a heads up for anyone else reviewing this.
> It seems this book is only available in HTML at the moment, since the links for the PDF, EPUB, and MOBI are broken.
> (Though users can compile them themselves.)
> 
> Someone has already reported the problem though: [MostlyAdequate/mostly-adequate-guide#586](https://github.com/MostlyAdequate/mostly-adequate-guide/issues/586)

Do I need to add anything else?

**Comment by SethiPandi** [comment]
> > Hey and welcome to free programming books!
> > Thanks for fixing the link, I can see the old one just redirected to the GitBook homepage.
> > This is more of a heads up for anyone else reviewing this.
> > It seems this book is only available in HTML at the moment, since the links for the PDF, EPUB, and MOBI are broken.
> > (Though users can compile them themselves.)
> > Someone has already reported the problem though: [MostlyAdequate/mostly-adequate-guide#586](https://github.com/MostlyAdequate/mostly-adequate-guide/issues/586)
> 
> Do I need to add anything else?

I think it's cool, given you're updating an existing resource, not adding a new one.

If you want, it would be even better if the author/vendor could be added to added too.
Based on repository, the `package.json` indicates "Mostly Adequate Core Team".

So, it might be nice to add ` - Mostly Adequate Core Team` to the end of the line.

**Comment by bojandevic** [comment]
> > > Hey and welcome to free programming books!
> > > Thanks for fixing the link, I can see the old one just redirected to the GitBook homepage.
> > > This is more of a heads up for anyone else reviewing this.
> > > It seems this book is only available in HTML at the moment, since the links for the PDF, EPUB, and MOBI are broken.
> > > (Though users can compile them themselves.)
> > > Someone has already reported the problem though: [MostlyAdequate/mostly-adequate-guide#586](https://github.com/MostlyAdequate/mostly-adequate-guide/issues/586)
> > 
> > 
> > Do I need to add anything else?
> 
> I think it's cool, given you're updating an existing resource, not adding a new one.
> 
> If you want, it would be even better if the author/vendor could be added to added too.
> Based on repository, the `package.json` indicates "Mostly Adequate Core Team".
> 
> So, it might be nice to add ` - Mostly Adequate Core Team` to the end of the line.

Done. Thanks for the help :+1:

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
