### PR TITLE
chore: gordon.edu is back. unarchive and complete formats

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?
Add info | Improve repo

### Why is this valuable (or not)?

Address resources revision proposed at https://github.com/EbookFoundation/free-programming-books/issues/5470#issuecomment-954974665

A new book edition was released while this downsite period

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by LuigiImVector — COMMENTED** [review]
Perhaps you could continue to use a more [up-to-date archived link](https://web.archive.org/web/20220225133700/https://math.gordon.edu/ntic/) to avoid other offline site issues, what do you think?

**Comment by davorpa** [comment]
> Perhaps you could continue to use a more [up-to-date archived link](https://web.archive.org/web/20220225133700/https://math.gordon.edu/ntic/) to avoid other offline site issues, what do you think?

Acording to guidelines... author site is better than publisher and thirth party, includes website to save a backup. Seen that replacement I push is an official college website, it's better leave it so.

**Comment by eshellman** [comment]
merging, but how did you notice the site was back?

**Comment by davorpa** [comment]
> merging, but how did you notice the site was back?

A bit of lucky reviewing Hacktoberfest backlog pending tasks :wink:

**Pull request merged**
