### PR TITLE
Add Vogel's Using RxJava 2 Tutorial

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?
Add resource(s)

### Description
Add the RxJava Tutorial made by Lars Vogel & Simon Scholz

### Why is this valuable (or not)?
Reactive programming is a usefull asynchronous technique. ReactiveX is a combination of the best ideas from the Observer pattern, the Iterator pattern, and functional programming.

RxJava provides Java API for asynchronous programming with observable streams.

### How do we know it's really free?
See source: https://www.vogella.com/tutorials/RxJava/article.html

### For book lists, is it a book? For course lists, is it a course? etc.
It's a tutorial

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
most of our "interactive tutorials" are more interactive. Despite the name, at first glance this looks like a book.

**Comment by davorpa** [comment]
> most of our "interactive tutorials" are more interactive. Despite the name, at first glance this looks like a book.

Then you suggest I should move it to...
https://github.com/EbookFoundation/free-programming-books/blob/7a2abd3acb9c05be73aa43922fe5e9170b91bd60/books/free-programming-books.md#L1713-L1734
making a new section eg. `Reactive Java` between `JasperReports` and `Spring`?

It doesn't matter to close PR if it's too short as to be a book or tutorial (I mean, it can be catalog as a merelly article) too.

**Comment by eshellman** [comment]
It's usually not helpful to add a category for a single resource. We should not have split up the Springs! I'd add it in the general java list. It's long enough to have a table of contents, so it's fine to call it a book.

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
