### PR TITLE
Add esfiddle to free-programming-playgrounds.md

### PR DESCRIPTION
**Pull request by Jacob-Marshall**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
It adds esfiddle.net to free-programming-playgrounds.md

### Why is this valuable (or not)?
It allows you to experiment with ES6.

### How do we know it's really free?
It's free with ads that our unobtrusive, and don't cover content

### Checklist:
- [x] Not a duplicate
- [ ] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by kadhirash** [comment]
The Travis CI build fails due to a trailing slash at the end of https://esfiddle.net/. 

I think simply changing it to https://esfiddle.net (remove the "/" at the end) would make the build passing

**Comment by Jacob-Marshall** [comment]
@kadhirash Thanks

**Comment by eshellman** [comment]
is this a clone? just curious.
Thanks, and welcome to free-programming-books!

**Comment by Jacob-Marshall** [comment]
>is this a clone? just curious.

I don't think so

**Pull request merged**
