### PR TITLE
2539: add the coder's apprentice book, Dutch version

### PR DESCRIPTION
**Pull request by lightbringer1991**
Resolves https://github.com/EbookFoundation/free-programming-books/issues/2539

English version is already in the repo
Added new file for Dutch language

### CODE REVIEW

**Comment by eshellman** [comment]
also need to add a link in README

**Comment by lightbringer1991** [comment]
@eshellman will do, yea I forgot that bit

**Comment by lightbringer1991** [comment]
@eshellman please review and merge if possible, thank you

**Comment by eshellman** [comment]
thanks!

**Pull request merged**
