### PR TITLE
Add malayalam courses

### PR DESCRIPTION
**Pull request by iathul**
## What does this PR do?
Add resource(s) 

## For resources
Added a list of Malayalam tutorials.

### Why is this valuable (or not)?
These tutorials will help the people who know Malayalam.

### How do we know it's really free?
These are youtube playlists.

### For book lists, is it a book? For course lists, is it a course? etc.
These are courses.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
For youtube, we prefer "playlist" links and the name of the producer/creator. https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#platforms-and-access-notes

The non-playlist links meet our criterion for "long enough to be a course" > 1 hour, so this is good. It would help the reviewers a lot if you could note this in the submission. 

Thanks, and welcome to free-programming-books!

**Comment by iathul** [comment]
@eshellman Thanks

**Comment by davorpa** [comment]
@iathul @eshellman is malayalam related with hindi [`hi`](https://www.localeplanet.com/icu/hi/index.html), for which listings already exist to, or in the other hand it needs to be considered a language apart?

Moreabout, if this resources are for Malaysia, language locale is `ms`, See https://www.localeplanet.com/icu/ms/index.html

**Comment by iathul** [comment]
@davorpa Like Hindi Malayalam is a language used in Kerala (a state in India). It needs to be considered a separate language.

**Comment by davorpa** [comment]
Thanks for that clarification

> Like Hindi Malayalam is a language used in Kerala (a state in India). It needs to be considered a separate language.

**Pull request merged**
