### PR TITLE
Add Fullstack GraphQL

### PR DESCRIPTION
**Pull request by JulianMayorga**

### CODE REVIEW

**Comment by eshellman** [comment]
There's another graphql book in language agnostic. Should we make a new heading?

Also, remember that the lists should be in alphabetical order- check the output of Travis-CI after submitting a new commit.

**Comment by eshellman** [comment]
Great, thanks for taking this on (a bit more work than most revisions!)
Could you 
 - move the other GraphQL resource into the new section
 - add GraphQL to the index at the top of the page

**Comment by JulianMayorga** [comment]
Created a new GraphQL section and added it to the index.

Sorry but I could not find the other GraphQL book. I searched for GraphQL and could not find anything. I also searched for Graph but could not recognise any of those books. Could you tell me the name? That way I can add it to the new GraphQl section.

Thanks for your patience!

**Comment by eshellman** [comment]
(I failed to notice the other GraphQL resource was in interactive tutorials, not books. I think it still merits a section.) Thanks again, and welcome to free-programming-books!

**Pull request merged**
