### PR TITLE
update: broken Farsi links HELP REQUESTED #3265

### PR DESCRIPTION
**Pull request by spencer1573**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Remove Resource(s) Improve Repo(update resource)

http://agiledevelopment.ir/ebook/
- that domain is currently available for purchase
- I removed this link from this md and the c sharp category because it was the only book in the category

http://docs.occc.ir/books/Main%20Book-20110110_2.pdf
- i was able to access the pdf, it took a very long time however.

http://linuxreview.ir/archbook/ArchBook-2012-1.pdf
- this link is no longer in this md (and i couldn't find it on the site)

https://symfony.com/doc/5.0/the-fast-track/fa/index.html
- this link was moved on the site so i updated it

### Checklist:
is a duplicate of a previous request that i couldn't get travis CI to work so i just made another one
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by spencer1573** [comment]
it looks like the build on master may be failing @eshellman

**Comment by eshellman** [comment]
sorry for the broken build.

**Comment by spencer1573** [comment]
You have so many PRs! I can't imagine its easy to keep a stable build! thanks @eshellman

**Comment by spencer1573** [comment]
is there a script i can run that checks for dead links? @eshellman

**Pull request merged**
