### PR TITLE
Update free-programming-books-ta.md

### PR DESCRIPTION
**Pull request by kbdharun**
**Fixing ~broken~ http links to all books with links pointing to Wayback machine and Internet archive, press books. Also, added the author's name in Tamil beside each book.**

**Previously the links were pointing to <http://www.kaniyam.com> which is** ~offline and unreachable~ [EDIT] *in http therefore it is blocked by default in most browsers* **currently. So I searched their new website <https://freetamilebooks.com> and over there I found internet archive links to the books, for books not present in the internet archive I used the WayBack Machine to link to the old pdf download page of the book.**

Also, I added the author's name beside each book and specified (PDF).

## What does this PR do?
Improve repo

### Why is this valuable (or not)?
These books are valuable and would be very useful for students and professionals who can understand concepts in Tamil better than in English. 

### How do we know it's really free?
I updated the old links to newer ones, seeing most of the books have creative commons licensing I am pretty sure they are free. 

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

### CODE REVIEW

**Comment by LuigiImVector** [comment]
> Previously the links were pointing to https://www.kaniyam.com which is offline and unreachable currently

kaniyam.com works correctly

**Comment by kbdharun** [comment]
> kaniyam.com

I noticed the links were in HTTP and were blocked by the browser by default. It is possible for me to access it in Firefox. But not in chrome. 
The below image is displayed when I visit that site
image

Wouldn't it be better to link directly to internet archive, then redirecting to this page as it is in HTTP and HTTPS page isn't present.

**Comment by LuigiImVector** [comment]
This problem occurs when using the version with the site's HTTPS (https://www.kaniyam.com/learn-bigdata-in-tamil-ebooks/) while using HTTP, such as the original resource link, does not experience this problem even on Chrome

**Comment by kbdharun** [comment]
> This problem occurs when using the version with the site's HTTPS (https://www.kaniyam.com/learn-bigdata-in-tamil-ebooks/) while using HTTP, such as the original resource link, does not experience this problem even on Chrome

In http, version to access the webpage chrome would ask for your permission twice to access site. In https, version which the browser redirects doesn't have a proper certificate. Which might make people assume that the file isn't secure. 

Since, the original publishers had published it in internet archive wouldn't it be better because the link would be permanent and also secure. And also easy for others to download in other formats like EPUB too.

**Comment by LuigiImVector** [comment]
> Both the cases might make potential readers assume that the file isn't secure.

You are right, there are many HTTP resources in the repository, I think an effective way to make them HTTPS should be discussed, always using archive.org I think can be inconvenient sometimes.

Anyway for me these changes are fine, let's wait for others' opinion.

**Comment by davorpa** [comment]
I'm in pro of leave as http://www.kaniyam.com/learn-bigdata-in-tamil-ebooks/ with `HTTP`

**Comment by eshellman** [comment]
http links are still acceptabe.

**Pull request closed without merging**
