### PR TITLE
Updated language names with native language names.

### PR DESCRIPTION
**Pull request by Sonkaryasshu**
All the languages were only present in English, So I added the native language alongside it for better readability.

## What does this PR do?
Add info | Improve Repo

### Checklist:
-  [x] Not a duplicate
- [ ] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Good idea! Please resolve conflicts.

**Comment by Sonkaryasshu** [comment]
Thanks. Resolved the conflict.

**Comment by eshellman** [comment]
Yes, but you removed a link instead of changing it!

**Comment by Sonkaryasshu** [comment]
Hi @eshellman, Can you please point out which link is removed? I don't see any deleted link in the repo. Thanks!

**Comment by eshellman** [comment]
indonesian courses

**Comment by Sonkaryasshu** [comment]
Actually, Indonesian course was placed in wrong order during conflict management, Link is working fine.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
