### PR TITLE
Update dead link on book about algorithms

### PR DESCRIPTION
**Pull request by platinumthinker**
## What does this PR do?
 Improve repo (fix link)

### Why is this valuable (or not)?
Just fix on exist link

### How do we know it's really free?
Have license Creative Commons Attribution 4.0
## Checklist:
- [+] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [+] Search for duplicates.
- [+] Include author(s) and platform where appropriate.
- [+] Put lists  in alphabetical order, correct spacing.
- [+] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
Thanks!

**Comment by kaream671** [comment]
[art](Github.com)    kaream`

**Comment by kaream671** [comment]
Ok

**Comment by kaream671** [comment]
Go

**Pull request merged**
