### PR TITLE
Added JavaScript Podcast

### PR DESCRIPTION
**Pull request by aravind-alpha**
Added JS Podcast

## What does this PR do?
Added JavaScript Podcast

### Description 
Added Frontend First Podcast by Sam Selikoff and Ryan Toronto.
### Why is this valuable (or not)?
This is an interesting podcast by Sam Selikoff and Ryan Toronto, focuses on UI Development and JavaScript in general.
### How do we know it's really free?
Frontend First is totally free. We can listen to it on their respective websites, listen on Spotify and Apple Podcasts app.
### For book lists, is it a book? For course lists, is it a course? etc.
Not a book or course.
### Checklist:
- [x] Not a duplicate
- [ ] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Add host names

**Comment by aravind-alpha** [comment]
You are asking for show hosts right? If that is the case, It is already added. Can you please check again. It is under "Why is this valuable". Or should I add it in description??

**Comment by eshellman** [comment]
in the listing

**Comment by aravind-alpha** [comment]
Updated :)

**Comment by aravind-alpha** [comment]
Oh ok. I think it's done.  Please check.

**Pull request merged**
