### PR TITLE
Adding Two Resources into free-courses-hi.md

### PR DESCRIPTION
**Pull request by shuaibabs**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
2 spaces, heading, one space, list

**Comment by shuaibabs** [comment]
Hey There I'm new at Git and GitHub
Could you please help me for Resolved this Travis CI Checks Error
I'm Not Getting What's Wrong with this

Thanks

**Comment by eshellman** [comment]
you are removing required spaces

**Comment by eshellman** [comment]
please resolve conflicts.

**Pull request closed without merging**
