### PR TITLE
Added Python in Finance

### PR DESCRIPTION
**Pull request by RawnakMahjabib**
* [Added Python in Finance](http://index-of.es/Varios/Yves%20Hilpisch-Python%20for%20Finance_%20Analyze%20Big%20Financial%20Data-O'Reilly%20Media%20(2014).pdf)

### CODE REVIEW

**Review by RawnakMahjabib — COMMENTED** [review]
* [Added Python in Finance](http://index-of.es/Varios/Yves%20Hilpisch-Python%20for%20Finance_%20Analyze%20Big%20Financial%20Data-O'Reilly%20Media%20(2014).pdf)

**Comment by SethiPandi** [comment]
Hey, and welcome to free programming books! :wave:

This repository is _not_ for hosting resources, it's only for linking to external resources.

You can get more guidance on the formatting and conventions in this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).

**Comment by RawnakMahjabib** [comment]
Hi! Thanks for clarifying! Happy to have found this repository and many resources!

I've included the link to the external resource using the formatting guidelines below:
* [Python for Finance](http://indexof.es/Varios/Yves%20HilpischPython%20for%20Finance_%20Analyze%20Big%20Financial%20Data-O'Reilly%20Media%20(2014).pdf) - Yves Hilpisch (PDF)

**Comment by SethiPandi** [comment]
1) You'd want to push that to your PR, not just as a comment.
2) We prefer links from authoritative sources such as the author, publisher, or an authorised distributor. This is just a site that collates and aggregates PDF documents, so it's unclear if it's really free.

**Comment by eshellman** [comment]
The repo does not host books. Please read CONTRIBUTING.md guidelines

**Pull request closed without merging**
