### PR TITLE
Added Redis for Dummies from Redis site

### PR DESCRIPTION
**Pull request by mfvitale**
## What does this PR do?
Add resource

### Description
- Added Redis for Dummies book from Redis official site

### Why is this valuable (or not)?
- Valuable for beginners

### How do we know it's really free?
It's available from Redis site leaving a mail address, Then there will be a download link

### For book lists, is it a book? For course lists, is it a course? etc.
- book

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
We set a pretty high bar for books that require email addresses, because we can't check to see if it's still available.

**Comment by mfvitale** [comment]
@eshellman I saw there are many books approved that require an email addresses. This ebook is free and available. You can also put fake information e you will get the public link. As you can see https://redis.com/wp-content/uploads/2021/09/Redis-For-Dummies_FINAL.pdf

**Comment by davorpa** [comment]
@eshellman I know you have the latest word, but in this I'm with @mfvitale 

 I review this yesterday https://github.com/EbookFoundation/free-programming-books/pull/5585#pullrequestreview-768114215 and is free and accesible. Behind sign-up form, that also give access to other REDIS features, we have access to  https://redis.com/wp-content/uploads/2021/09/Redis-For-Dummies_FINAL.pdf

I've download REDIS some time ago, and today it follow being the same link

**Comment by eshellman** [comment]
problem with the alternate links is they don't last. and I tried with fake email address and din't get anything. so for now, I think we'll pass on this one.

**Comment by mfvitale** [comment]
@eshellman I not agree with you. I tried at least 3 times compiling the form with fake email and I have got the links. 

This is a free resource made by Redis an is their interest to leave it free. I think this is a useful resource for this repo.

**Pull request closed without merging**
