### PR TITLE
Update free-courses-hi.md

### PR DESCRIPTION
**Pull request by Asjdnnc**
Updated the code for the issue #11562

## What does this PR do?
Add resource(s) - javascript course in hindi 
Improve the free-courses-hi (Javascript section)

## For resources
Javascript

### Why is this valuable (or not)?
This courses is best for learning javascript for the beginners

### How do we know it's really free?
It is available on youtube

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Asjdnnc** [comment]
@eshellman pls suggest the required changes if any?

**Comment by eshellman** [comment]
> @eshellman pls suggest the required changes if any?

You removed a resource without explanation and omitted an author name

**Comment by Asjdnnc** [comment]
@eshellman 
I removed the comprehensive WEB dev course playlist from the javascript section and replaced it with a dedicated javascript course from the same YouTube channel.

**Comment by eshellman** [comment]
The course you added has a different attribution

**Pull request closed without merging**
