### PR TITLE
Added cheatsheet for Fish Shell

### PR DESCRIPTION
**Pull request by Athi223**
## What does this PR do?
Add resource(s)

### Description
Added a cheatsheet for the [Fish Shell](https://fishshell.com/) 

> fish is a smart and user-friendly command line
shell for Linux, macOS, and the rest of the family.

### Why is this valuable (or not)?
This is valuable because **fish**, although being an amazing shell alternative for _bash_ or _zsh_; has some incompatibilities with both. I first tried out **fish** a couple of weeks ago while trying out a new arch-based distro, which provided **fish** as the default shell. I liked it a lot, but also required some help for customizations. This cheatsheet provided all that I needed to get stuff up and running. Hence, hopefully this cheatsheet would help others, like me, who wish to try out **fish shell**.

### How do we know it's really free?
This cheatsheet comes from a well-known resource: **DevHints**. It is publicly available for anyone and everyone to view, as well as to contribute to.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

### CODE REVIEW

**Review by LuigiImVector — COMMENTED** [review]
Maybe you could create a more generic category, such as "Linux shell", needs review

**Comment by Athi223** [comment]
> Maybe you could create a more generic category, such as "Linux shell", needs review

Actually, I saw a category named "Bash", so thought it'd make sense to add a category for "Fish" too.

Although your "Linux Shell" category makes more sense, in a broader perspective. Will it be fine if I instead add the category, and then move both "Bash" and "Fish" into it?

Your thoughts, @LuigiImVector ?

**Comment by LuigiImVector** [comment]
I had not seen "bash," however we try to avoid creating a new section for one resource, in this case Fish is also little known so I think "Linux shell" is a good choice. Maybe we'll wait for someone else's opinion.

**Comment by davorpa** [comment]
`Shell Scripting` will be a good name to the category. Could you merge bash and fish into it?

**Comment by Athi223** [comment]
@davorpa Done! Hope the overall change was as it was expected 😄

**Comment by davorpa** [comment]
> @davorpa Done! Hope the overall change was as it was expected 😄

Sure! with a bit cleanup

**Review by davorpa — APPROVED** [review]

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
