### PR TITLE
Update free-programming-books-langs.md

### PR DESCRIPTION
**Pull request by atharva20-coder**
## What does this PR do?
Add resource

### Description
This Course basically introduces web development
### Why is this valuable (or not)?
This course designed keeping for absolute beginners
### How do we know it's really free?
The attached link redirects to the GitHub repository
### For book lists, is it a book? For course lists, is it a course? etc.
It is a course
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

### CODE REVIEW

**Comment by atharva20-coder** [comment]
@shrn01 please look into this PR

**Review by shrn01 — APPROVED** [review]

**Comment by atharva20-coder** [comment]
@shrn01 Please tag it as hactoberfest.

**Comment by shrn01** [comment]
Hey @atharva20-coder , you should be able to see this PR in your hacktober progress without the label also

**Comment by atharva20-coder** [comment]
> Hey @atharva20-coder , you should be able to see this PR in your hacktober progress without the label also 

It shows excluded

**Pull request merged**
