### PR TITLE
add Java Tutorial with example

### PR DESCRIPTION
**Pull request by andikscript**
## What does this PR do?
Add Resource(s) 

### Description 
Java Tutorial with Example (web)
### Why is this valuable (or not)
its good for beginner to learn java
### How do we know it's really free?
its really free
### For book lists, is it a book?
no, but web tutorial
### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by andikscript** [comment]
add java tutorial 8 book

**Comment by eshellman** [comment]
Good resource, but check travis-ci to see what the linter is failing for. (alphabetize the list!)(I have lots of Hacktoberfest submissions to process!)

**Comment by andikscript** [comment]
> Good resource, but check travis-ci to see what the linter is failing for. (alphabetize the list!)(I have lots of Hacktoberfest submissions to process!)

how do i check this project so it is not passed on ci travis

**Review by kadhirash — COMMENTED** [review]
Hello @andikscript  , I came across this old pull request and found the issue.

Travis-CI build fails because it is not alphabetical.

Your resource "Java Tutorial 8 : Learn Java Programming with examples" comes after "Welcome to the Java Workshop (2006)" resource. Since **J** is before **W**, this resource should be way before. 

The correct position would be after "Java Projects, Second Edition" at the current state of the repository, since the **T** in "Java Tutorial..." comes after the **P** in "Java Projects..."

**Comment by eshellman** [comment]
Can't get to book because of intrusive ads

**Pull request closed without merging**
