### PR TITLE
Added Code of Conduct in Sinhala language (review requested)

### PR DESCRIPTION
**Pull request by AaryaBalwadkar**
## What does this PR do?
Fixes Issues : Need Sinhala translation of the code of conduct #9593

### Why is this valuable ?
Diversity of resources make our initiative of spreading good learnings to our users. This increases the need of a code of conduct in their understandable language to make them clear about our guidelines. This PR solves this issue for a large community of Sinhala speakers.  
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).

### CODE REVIEW

**Comment by eshellman** [comment]
requesting sinhala review

**Comment by eshellman** [comment]
need to add link in  docs/README.md

**Review by garbalau-github — APPROVED** [review]
Really?

**Comment by AaryaBalwadkar** [comment]
I have added the Code_of_Conduct-si.md link in docs/README.md. Please have a look.
image

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!
@MaheshMadushan thanks for review.

**Pull request merged**
