### PR TITLE
Added  free-courses-eng.md

### PR DESCRIPTION
**Pull request by Ash515**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Same comment as before, eng is English, we already have an en file though which stands for English!

In other words we already have a file for English, could you please put it in the existing en file, rather than creating a new eng file?

**Comment by Ash515** [comment]
sure sir

**Review by yezz123 — CHANGES_REQUESTED** [review]
Add Algorithmes books as example [Algorithm Design
Book by Jon Kleinberg and Éva Tardos](http://www.cs.sjtu.edu.cn/~jiangli/teaching/CS222/files/materials/Algorithm%20Design.pdf)

**Comment by yezz123** [comment]
#4796 Also check this one

**Pull request closed without merging**
