### PR TITLE
Add programming books Scala Book

### PR DESCRIPTION
**Pull request by ihertanto**
## What does this PR do?
Add resource

### Description
This book provides a quick introduction and overview of the Scala programming language

### Why is this valuable (or not)?
Very useful to learn Scala

### How do we know it's really free?
Posted on the Author's Website and have `Creative Commons NonCommercial Share Alike 3.01` on the book

### For book lists, is it a book? For course lists, is it a course? etc.
It is a book

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
great resource, but one link is enough - the landing page has links to the different files.

**Comment by ihertanto** [comment]
> great resource, but one link is enough - the landing page has links to the different files.

I have remove the individual links

**Review by davorpa — APPROVED** [review]
Ready to merge :tada:

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
