### PR TITLE
Update free-programming-books-langs.md

### PR DESCRIPTION
**Pull request by vishalkrishna8**
## What does this PR do?
Add resources

### Description
Added a free book named as MySQL Tutorials by Tutorialspoint.com.

### Why is this valuable (or not)?
There were very few resources on MySQL so I thought I would add some so I added this, It is a very informative book and you can learn by reading yourself. 

### How do we know it's really free?
The book is provided by Tutorials point , anyone can download from the website.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
use the original reference

**Comment by vishalkrishna8** [comment]
> use the original reference

sorry i don't understand what you want to say

**Comment by eshellman** [comment]
content at your link is copied from tutorialspoint.com

**Comment by vishalkrishna8** [comment]
> content at your link is copied from tutorialspoint.com

Ok got it

**Pull request closed without merging**
