### PR TITLE
Add git and nodejs

### PR DESCRIPTION
**Pull request by Lakshita2002**
## What does this PR do?
Add Resources

### Description 
Notes on Git and Nodejs
### Why is this valuable (or not)
These are some good notes on Git and Nodejs :)
### How do we know it's really free?
I just downloaded it for free!
### For book lists, is it a book?
Yes
### Checklist:
- [ :heavy_check_mark: ] Not a duplicate
- [ :heavy_check_mark: ] Included author(s) if appropriate
- [ :heavy_check_mark: ] Lists are in alphabetical order
- [ :heavy_check_mark: ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Thanks!

**Comment by Lakshita2002** [comment]
I don't understand why some checks weren't succesful, could you please tell me

**Comment by eshellman** [comment]
its a new action we've added to check links. @borgified has been working on it - the links that have errored are not related to your PR and I'm in the process of merging it.

**Comment by Lakshita2002** [comment]
Ok sir, thank you for clarifying it
Cheers :)

**Pull request merged**
