### PR TITLE
Removing dead course

### PR DESCRIPTION
**Pull request by spekulatius**
Hey,

just removing a dead link.

Cheers!

### CODE REVIEW

**Comment by eshellman** [comment]
Just to confirm, the link is not dead, but the course is not free, correct?

**Comment by spekulatius** [comment]
Oh, I went by the 404 in the title of the page prior to redirection. I'm not sure - I couldn't see an information regarding pricing and don't speak Spanish

**Comment by eshellman** [comment]
as it's not marked "free", we'll remove it.

**Comment by spekulatius** [comment]
Ah, okay - good to know @eshellman

**Pull request merged**
