### PR TITLE
Update free-programming-books-ro.md

### PR DESCRIPTION
**Pull request by verkiya**
Changed HMTL to **HTML**

### CODE REVIEW

**Comment by eshellman** [comment]
looks like the link in the index is also misspelled, so correcting this section header breaks the index link.

This list needs some loving improvement! The titles of the books are missing, for example the title for "HTML" should be "Tutorial HTML - Introducere in HTML". Looking at the history, most of the maintenance has been removing broken links. @Verkiya, I'm guessing you don't speak romanian, but if you do, (or if anyone listening does), a little work could go a long way.

**Comment by Verkiya** [comment]
@eshellman I would love to work on it if I knew about Romanian. However, If I'll get in touch with someone speaking Romanian I'll surely redirect him/her here. I'm also looking forward to contributing to this repository and gain more knowledge about this project.
Thanks again, @eshellman sir.

**Comment by bluetata** [comment]
> Incorrect spelling of "HTML", fixed to the correct spelling.

Index link is incorrect~~~

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
