### PR TITLE
Add laravel course from Wahidev Academy

### PR DESCRIPTION
**Pull request by mohfirdaus**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Description 
Silahkan Belajar Laravel disini cocok untuk Pemula yang baru Belajar Pemrograman. Secara runtut silahkan dinikmati playlistnya akan kami bagi beberapa bagian. Selamat Belajar ! Salam Programming !

### How do we know it's really free?
Course diupload dalam bentuk video di playlist youtube

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Hey, and welcome to free programming books! :wave:

Could you please use URLs from the /playlist endpoint, not the /watch endpoint?

For example:
```
GOOD: https://www.youtube.com/playlist?list=PLIan8aHxsPj0XtJjWW04hN24fWXrCpLkY
BAD:  https://www.youtube.com/watch?v=AYb7l6XDlPo&list=PLIan8aHxsPj0XtJjWW04hN24fWXrCpLkY&ab_channel=WahidevAcademy
```

Also, you'll want to ensure all lists and categories are in alphabetical order!

You can get more guidance on the formatting and conventions in this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).
You can also click on the failed checks to get more information on any check failures. You'll be able to see exactly what was wrong and how to fix it!

**Comment by mohfirdaus** [comment]
Done!

**Comment by SethiPandi** [comment]
> Done!

Sorry, small question! It looks like you also removed one of the two links when you updated it, was this intentional?

**Comment by mohfirdaus** [comment]
> > Done!
> 
> Sorry, small question! It looks like you also removed one of the two links when you updated it, was this intentional?

Yes, Because I saw an error at my second commit

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
