### PR TITLE
add golang javatpoint effective tutorial

### PR DESCRIPTION
**Pull request by sanjibgirics**
## What does this PR do?
Add resource

### Description
javatpoint effective go tutorial

### Why is this valuable (or not)?
effective go tutorial. Have followed this personally.

### How do we know it's really free?
Have used it personally.

### For book lists, is it a book? For course lists, is it a course? etc.
It's a tutorial in website.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by sohansai — COMMENTED** [review]
For now, Javatpoint links are not accepted for PRs

**Comment by sanjibgirics** [comment]
> For now, Javatpoint links are not accepted for PRs

Okay. But there are Javatpoint links present in the repo.

**Comment by sohansai** [comment]
Can you please specify where the Javatpoint links are in the repo? We will review them.

**Comment by sanjibgirics** [comment]
> Can you please specify where the Javatpoint links are in the repo? We will review them.

Okay, sure. Here are the places where Javatpoint links exist.
https://github.com/EbookFoundation/free-programming-books/blob/main/more/free-programming-interactive-tutorials-en.md?plain=1#L64
https://github.com/EbookFoundation/free-programming-books/blob/main/more/free-programming-interactive-tutorials-en.md?plain=1#L218

**Comment by eshellman** [comment]
#9801 #9802

**Pull request closed without merging**
