### PR TITLE
Added Learn to Code HTML & CSS of Shay Howe

### PR DESCRIPTION
**Pull request by trash07**
## Added CSS Book
I recently add the Shay Howe's book about HTML&CSS. The book is available for free but you can also purchase a paid version whether paper or kindle on amazon.com  
* [Learn to Code HTML & CSS](https://learn.shayhowe.com/) 

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Nice addition. I prefer not to have extraneous notes about paid editions in the list. Could you remove the note?

**Comment by ShipsWithCannons** [comment]
Agreed, gets too noisy too fast.

**Comment by trash07** [comment]
I removed it.

**Comment by trash07** [comment]
I removed it.

**Comment by trash07** [comment]
I removed it.

**Comment by trash07** [comment]
I removed it.

**Comment by trash07** [comment]
I removed the paid version information

**Comment by eshellman** [comment]
@trash07 Thanks, and welcome to free-programming-books!

@ShipsWithCannons It's very helpful for me to get comments from the community - Thanks!

**Comment by ShipsWithCannons** [comment]
@eshellman Least I can do, you're welcome. I'm amazed this initiative is still running so well, so a couple of quality restrictions won't hurt anyone.

**Pull request merged**
