### PR TITLE
Docker links added

### PR DESCRIPTION
**Pull request by learn-everyday-with-me**
#3856 
Added links of docker courses.

## What does this PR do?
Add Resource(s) | Improve Repo

### Description 
Added Docker, with some interactive courses

### Why is this valuable (or not)
These courses teach about docker in detail

### How do we know it's really free?
These are the resources on youtube. The full playlist is available

### For book lists, is it a book?
No, It is not a book.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
I think these belong in the courses list. include instructor

**Comment by learn-everyday-with-me** [comment]
I have added the docker resources in file courses named free-courses-do.md please check it.

**Comment by eshellman** [comment]
Please read CONTRIBUTING.md guidelines!

**Comment by harekrishnarai** [comment]
> 
> 
> I have added the docker resources in file courses named free-courses-do.md please check it.

Thanks buddy for fixing the errors.

**Pull request closed without merging**
