### PR TITLE
Add C Programming Tutorial book

### PR DESCRIPTION
**Pull request by AyushShahh**
## What does this PR do?
Add resource.
This PR adds a C Programming tutorial book.

### Description
This is a C language programming tutorial book by which you can learn C language from scratch.

### Why is this valuable (or not)?
This book is really good for beginners. It explains the history of C, basics, installation and goes through a lot of topics in C language which makes it really useful for those who want to learn it from scratch.

### How do we know it's really free?
It is on the official website of Tutorialspoint

### For book lists, is it a book? For course lists, is it a course? etc.
It is a book

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

All the checks have passed!

### CODE REVIEW

**Comment by davorpa** [comment]
I'm not sure if this is free.

If it's free... the right site, maybe would be https://www.tutorialspoint.com/cprogramming/ where the PDF have a cost.

**Comment by AyushShahh** [comment]
@davorpa I checked on their official site and found that the PDF version of the book was not free. However, the HTML version of the book is completely free and it is on their site. I have updated the link.

Please have a check

**Comment by AyushShahh** [comment]
@davorpa I checked their official site and found that the PDF version of the book was not free. However, the HTML version of the book is completely free and it is on their site. I have updated the link.

Please have a check

**Review by davorpa — APPROVED** [review]
### Ready to merge :fireworks: :tada:

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
