### PR TITLE
Add Learn More Python the Hard Way to Python books

### PR DESCRIPTION
**Pull request by ehmsu**
## What does this PR do?
Add resource

### Description
Online Python guidebook

### Why is this valuable (or not)?
Guide to Python 3.6 

### How do we know it's really free?
From author's website 

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by LuigiImVector** [comment]
The correct category is `courses`

**Comment by ehmsu** [comment]
Hello! Sorry about that, I have added the link to the Python courses (en). Does it look alright now?

**Comment by LuigiImVector** [comment]
Yes but now we need to wait to another review

**Comment by eshellman** [comment]
This seems a bit too unfinished, and also a dead project (has a 2016 date on it) Why is there a chapter on sed in a python book?? Thank you for suggesting it, but I think we'll decline it for now.

**Comment by ehmsu** [comment]
Okay, thanks for letting me know!

**Pull request closed without merging**
