### PR TITLE
#hacktoberfest "Laravel Portugal Live" Portuguese Podcast

### PR DESCRIPTION
**Pull request by joseborges**
#hacktoberfest "Laravel Portugal Live" Portuguese Podcast

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Hey, and welcome to free programming books! :wave:

We have a dedicated type for podcasts and screencasts, could you please move your resource over there instead?
Since it'll be the first resource for of this type, in this language, you'll have to create the file yourself. (`
free-podcasts-screencasts-pt_PT.md`)

Could you also correct the spelling of Laravel in the link! (`#laravel`)

**Comment by joseborges** [comment]
Hi, could you please add this PR so that it counts to the #hacktoberfest 2020? Thanks!

**Review by joseborges — COMMENTED** [review]
All seems like you asked now.

**Comment by SethiPandi** [comment]
Since this changes nothing now and appears to be replaced by https://github.com/EbookFoundation/free-programming-books/pull/4704, could this be closed?

**Comment by joseborges** [comment]
Sure... Sorry forgot about that

**Pull request closed without merging**
