### PR TITLE
added courses

### PR DESCRIPTION
**Pull request by fawazsiddiqi**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Description 
Added courses from cognitiveclass.ai (free courses on different topics)
### Why is this valuable (or not)?
Will give beginners a good overview of various implementations
### How do we know it's really free?
It is hosted on cognitiveclass.ai which is a free course website
### For book lists, is it a book? For course lists, is it a course? etc.
Courses
### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by fawazsiddiqi** [comment]
@eshellman updated the course list in regards to the previous PR, all updated now :D

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by fawazsiddiqi** [comment]
@eshellman conflicts resolved

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
