### PR TITLE
Update free-programming-books-langs.md

### PR DESCRIPTION
**Pull request by git-create-devben**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
not free

**Comment by git-create-devben** [comment]
I thought book can be free or paid and only courses should be free

**Comment by eshellman** [comment]
you're confusing us with paid-or-free-programming-books

**Comment by git-create-devben** [comment]
Sorry! So the book is paid , what can I do should I find a free book?

**Pull request closed without merging**
