### PR TITLE
Added CONTRIBUTING-id.md

### PR DESCRIPTION
**Pull request by VicoSilalahi**
## What does this PR do?
Improve Repo

### Description 
Added CONTRIBUTING-id.md , still many flaws, but i hope to integrate most of it first and fix it along the way

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by VicoSilalahi** [comment]
Mmm, i'll check the formatting

**Comment by VicoSilalahi** [comment]
Mmmm, i don't think this should be alphabetized, like what the Travis CI said or is it, is there any rules stated to make CONTRIBUTING.md on other language like CONTRIBUTING-zh.md, i think i missed something, or is the Travis CI only for courses files?

**Comment by eshellman** [comment]
interesting problem.

**Comment by eshellman** [comment]
I think it doesn't like your markdown

**Comment by VicoSilalahi** [comment]
Huh.... i'm going to experiment with different formatting, untill... well untill it's fixed?

**Comment by eshellman** [comment]
ok

**Pull request closed without merging**
