### PR TITLE
Add a Turkish Fortran book

### PR DESCRIPTION
**Pull request by eersoy93**
Fortran Programlama Diline Giriş (Turkish)

## What does this PR do?
Add resource(s)

### Description
Fortran Programlama Diline Giriş (Turkish) - Ercan Ersoy, Erdem Ersoy

Official link: [http://dosyalar.ersoykardesler.net/yayinlar/Fortran_Programlama_Diline_Giris.pdf](http://dosyalar.ersoykardesler.net/yayinlar/Fortran_Programlama_Diline_Giris.pdf)

### Why is this valuable (or not)?
This is a free academical book.

### How do we know it's really free?
This book is written by me and my brother and we have published for free (CC BY-NC-ND 4.0).

### For book lists, is it a book? For course lists, is it a course? etc.
This is a book.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
link didn't work for me - are you sure its a publicly available link?

**Comment by eersoy93** [comment]
The server hosts the PDF is in maintenance now.

**Comment by eersoy93** [comment]
The link is active now. You would download the book (PDF).

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
