### PR TITLE
Added Jeremy Howard's book Deep Learning for Coders to the index

### PR DESCRIPTION
**Pull request by ghosh-r**
## What does this PR do?
Add resource(s)

### Description
A book sold as a printed copy made freely available as Jupyter Notebooks that teaches Deep Learning with PyTorch and fastai Deep Learning libraries.

### Why is this valuable (or not)?
It is a book that teaches Deep Learning to beginners and guides them to advanced levels with very practical examples and codes used throughout the book.

### How do we know it's really free?
It is hosted in a GitHub repository with GPL v3 License. 

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by SethFalco** [comment]
Hey, and welcome to free programming books! :wave:

It looks to me like this isn't a book, but just Jupyter notebooks which are supplementary to a book.
We have a couple of related resources already which I believe are more appropriate.

> ```md
> * [Practical Deep Learning For Coders taught](http://www.fast.ai) - Jeremy Howard
> * [Practical Deep Learning for Coders, v3 (using fastai library)](https://course.fast.ai)
> ```
> \- https://github.com/EbookFoundation/free-programming-books/blob/master/courses/free-courses-en.md#deep-learning

From the repository you're adding:

> These notebooks cover an introduction to deep learning, fastai (https://docs.fast.ai/), and PyTorch.

> These notebooks are used for a MOOC (https://course.fast.ai/) and form the basis of this book, which is currently available for purchase. It does not have the same GPL restrictions that are on this draft.

**Comment by ghosh-r** [comment]
@SethFalco , the repository is definitely a book. The README is outdated. The Notebooks are exactly the same as the printed book, and the book was written using Jupyter Notebooks. Jeremy repeatedly mentions in his MOOC how he wrote the book using Jupyter Notebooks.

> All this work has recently come together as a book, written openly on Jupyter notebooks.

~ [JupyterCon 2020 keynote speaker announcement
](https://blog.jupyter.org/jeremy-howard-8dace7b4a34a)

**Comment by SethFalco** [comment]
@ghosh-r The page you sent links to course.fast.ai which in turn links the the Jupyter Notebooks as additional material.

> Welcome to Practical Deep Learning for Coders. This web site covers the book and the 2020 version of the course, which are designed to work closely together. If you haven't yet got the book, you can buy it here. It's also freely available as interactive Jupyter Notebooks; read on to learn how to access them..

**Comment by ghosh-r** [comment]
The repository is the same as this book- https://www.goodreads.com/book/show/50204643-deep-learning-for-coders-with-fastai-and-pytorch 
And it can be read as a standalone book independent of the book. It is also sold as a standalone book- https://www.oreilly.com/library/view/deep-learning-for/9781492045519/ and I believe that the link should be here.

**Comment by eshellman** [comment]
Thanks @ghosh-r , and thanks @SethFalco for the discussion. I recently added a section in CONTRIBUTING.md to try to help folks trying to decide if something is a book. This entry really tests all the boundaries!

Personally, I think it fits best in "interactive tutorials". It's not strictly a duplicate of the course entry, as it's really the "textbook" that accompanies the course.

One useful guidance is that the creators describe it as a book. If we don't include it in the book list, then a year from now someone will think it's missing from the book list and try to add it again.

I have been nudging the ebook industry to make ebooks more like Jupyter notebooks and this is a great example of what's possible. The Jupyter folks apparently feel the same: see https://executablebooks.org/en/latest/index.html

Although I agree that the repo is not _quite_ a book, there's just a bit of glueing of pages to make it one. Maybe adding it to the list will encourage the creators to talk the publisher into letting them do it.

@ghosh-r  Thanks, and welcome to free-programming-books!

**Comment by ghosh-r** [comment]
@eshellman thanks. I look forward to  contributing further to this project. Have a good one.

**Pull request merged**
