### PR TITLE
Add three CC-BY-SA licensed, Ada's PDF resources

### PR DESCRIPTION
**Pull request by momozor**
## What does this PR do?
Add Resource(s)

## For resources
Ada free ebooks. Mainly introduction to Ada 2012, subset of Ada SPARK (for formal verification), and Ada SPARK for MISRA C developers. 

### Why is this valuable (or not)
There are not many free Ada ebooks lying around the internet, especially the good ones like these.

### How do we know it's really free?
Explicit CC-BY-SA license notice in the book page after the content indices, usually before the preface and introduction page.

### For book lists, is it a book?
Yes, ebooks.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Do you think it might be better to link to pages like: https://learn.adacore.com/courses/SPARK_for_the_MISRA_C_Developer/  ?

**Comment by eshellman** [comment]
Also, these are super additions!

**Comment by momozor** [comment]
@eshellman Do I need to put these somewhere else other than this file if I link to the pages directly instead?

**Comment by eshellman** [comment]
no, same place. but leave off the pdf indication, since it's pdf and html.

**Comment by momozor** [comment]
@eshellman Alright. I've converted it to use pages link instead.

**Comment by eshellman** [comment]
Great, thanks.

**Pull request merged**
