### PR TITLE
Clean up alphabetical ordering and headings in file, check_urls=free-programming-books.md

### PR DESCRIPTION
**Pull request by kadhirash**
## What does this PR do?
Add Resources |  Improve Repo 

### Description 
I noticed the free-progamming-books.md was out of order as well as had extra resources not in the Index section. I fixed that up. It started with Meta-Lists then jumped to Graphical Programming, etc.
### Why is this valuable (or not)?
Make the .md file look more presentable and in the correct order!

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by kadhirash** [comment]
Hello @eshellman, I noticed the merge conflicts occurred because files were added to the old ordering instead of the correct ordering I created. So the more courses that are being added to the file will keep resulting in a conflict right?

**Comment by eshellman** [comment]
sorry about the broken build!

**Comment by eshellman** [comment]
Yes. sorry about the errors introduced on cheatsheets - that's fixed. We'll need you to restart whatever you wanted to do with a freash branch off of master

**Comment by kadhirash** [comment]
@eshellman okay great I'll delete this branch and create a new one from master right now!

**Pull request closed without merging**
