### PR TITLE
Added authors and year of publication for books in the Java section.

### PR DESCRIPTION
**Pull request by tedyoung**
Deleted one duplicate entry and added httpS where available.

This is for (part of) issue #2383.

### CODE REVIEW

**Comment by tedyoung** [comment]
btw, I just saw issue #1926, so I'm happy to pull some of the dates from the past 5 years. To be honest, for Java, some of the older material isn't very useful, so anything prior to 2010 would be useful to note.

**Comment by eshellman** [comment]
@tedyoung , this is awesome. I agree with the syntax you initially used to add the year. I'll see about revising the linter, and adding some documentation so we can close the add-year issue. I may ask you to review that when it's done, if you'd be willing.

**Comment by tedyoung** [comment]
Happy to review, I was going to update the docs anyway, with respect to where the "remarks" go (the stuff in parentheses/italics), but I'll wait for your update first.

**Comment by eshellman** [comment]
I see now. The linter was complaining about
* [Java: The Legend](https://www.oreilly.com/programming/free/java-the-legend.csp) *(Just fill the fields with any values)* - Ben Evans, 2015

but is happy with 
* [Java: The Legend](https://www.oreilly.com/programming/free/java-the-legend.csp) - Ben Evans, 2015 *(Just fill the fields with any values)* 

and there are previous entries like
* [Java: The Legend (2015)](https://www.oreilly.com/programming/free/java-the-legend.csp) - Ben Evans

so I think we'll stick with the latter

**Pull request merged**
