### PR TITLE
an updated commit message

### PR DESCRIPTION
**Pull request by sumitmukharjeeeeee**
This playlist of NextJS is from youtube from youtuber ThapaTechnical.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by SethFalco** [comment]
Same comments as https://github.com/EbookFoundation/free-programming-books/pull/5543

**Comment by sumitmukharjeeeeee** [comment]
> Same comments as #5543

Yeah but I was not able to make changes to that branch so I closed that

**Comment by SethFalco** [comment]
> > Same comments as #5543
> 
> Yeah but I was not able to make changes to that branch so I closed that

I meant the same changes apply here as well, though. Could you please address them in another commit?

**Comment by SethFalco** [comment]
> I closed this as Was not able to change the line break commit from this branch.
> Please help me how to proceed

You should be able to make the changes locally and push them to your branch, just like the first commit.

```sh
# make sure you've checked out the branch you're working in
git checkout addedHindiNextJS

# make the required changes

# stage all changes to be committed
git add .

# modify the previous commit to include the current changes
git commit --amend

# push the changes to your fork
git push --force-with-lease
```

It should automatically update this pull request with new changes.

**Comment by davorpa** [comment]
> ```shell
> # make sure you've checked out the branch you're working in
> git checkout addedHindiNextJS
> 
> # make the required changes
> 
> # stage all changes to be committed
> git add .
> 
> # modify the previous commit to include the current changes
> git commit --amend
> 
> # push the changes to your fork
> git push --force-with-lease
> ```
> 
> Note: `--amend` and `--force-with-lease` modify git history, don't do that outside of feature branches.

Before checkout ensure your local repo refs are up to date with remotes. So....

```shell
# sync refs your remote repo
git fetch origin
# sync refs you remote forked repo
git fetch upstream

...
```

If you are using web interface all this is not needed.
Move to the branch where you commit last PR changes, edit files and save. All timeline will be reflected in PR. No force push is needed.

**Comment by eshellman** [comment]
this item should be listed in a subsection next to React.

**Comment by davorpa** [comment]
Due to source branch was deleted, this PR comes into a detached state.

To continue, it only can be recovered fetching remote heading refs. Use following command:

```shell
git fetch upstream pull/5547/head:pr/5547-hindi-reactjs-courses
```

to recover branch preserving timeline history 😉

**Comment by eshellman** [comment]
PR replaced

**Pull request closed without merging**
