### PR TITLE
Added cheatsheet for Cron

### PR DESCRIPTION
**Pull request by Athi223**
Added Cron cheatsheet under a new category 'Linux'

## What does this PR do?
Add resource(s)

### Why is this valuable (or not)?
Cron is widely used for scheduling periodic jobs on Linux. This cheatsheet can prove to be effective for scheduling such jobs, especially with the 5 character format that is used for scheduling.

### How do we know it's really free?
DevHints is a widely-known free resources for various cheatsheets.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category.
Maybe shell scripting?

**Comment by Athi223** [comment]
> It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category. Maybe shell scripting?

Yup `Shell Scripting` seems to be the closest. Will move it into `Shell Scripting`.

**Comment by Athi223** [comment]
@eshellman Any updates on this?

**Comment by eshellman** [comment]
sorry for delay, see #9109

**Pull request merged**
