### PR TITLE
Add DenoJS section and a free Deno Beginner Course

### PR DESCRIPTION
**Pull request by saqibameen**
## What does this PR do?
Add Resource

### Description 

Add DenoJS section and a free Deno Beginner course to get started 

### Why is this valuable (or not)?

Gives a headstart in learning the new JavaScript runtime — Deno. 

### How do we know it's really free?

Take a look at the site of the course, it is free. You may enroll and watch.

### For book lists, is it a book? For course lists, is it a course? etc.

It's a course:
[Deno Beginner](https://denobeginner.com/ )

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Did you do the course?

**Comment by saqibameen** [comment]
Yes I have watched it.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by saqibameen** [comment]
@eshellman PR Updated.

**Pull request merged**
