### PR TITLE
added free-courses-yb.md

### PR DESCRIPTION
**Pull request by Yadavbalbir**
## What does this PR do?
Added Courses

### Description
added free courses on MATLAB and Simulink

### Why is this valuable (or not)?
These courses are certified courses and in high demand for those wanting to use MATLAB and Simulink in engineering courses. 

### How do we know it's really free?
All courses are self-placed and free provided by mathsworks.com. I have personally taken one of these courses.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by shrn01 — COMMENTED** [review]
Please add the resources to one of the existing files. Read docs/CONTRIBUTING.md for more information

**Comment by Yadavbalbir** [comment]
@shrn01 made changes

**Comment by shrn01** [comment]
courses/free-courses-km.md is for resources in Khmer language. For english you might want to add them in courses/free-courses-en.md

**Comment by shrn01** [comment]
image

Looks like this is a paid course. Please remove

**Comment by eshellman** [comment]
use the existing categories!

**Comment by shrn01** [comment]
closes 8848

**Comment by eshellman** [comment]
I think you want to make 'simulink' a subcategory of 'MATLAB'

**Pull request merged**
