### PR TITLE
Added a new programming book "Let Us C"

### PR DESCRIPTION
**Pull request by HawkEye201**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Not clear if this is an authorized distribution. Please see CONTRIBUTING.md guidelines.

**Comment by dark2501** [comment]
Awesome

**Comment by SethiPandi** [comment]
I don't think this is free either.

1) GitHub shouldn't be used as a CDN or as an alternative for a file sharing site like.
2) The book doesn't contain a license in it, so there's no evidence that it's under a redistributable license.
3) There is no evidence that the author of the repo/PR are the author of the book which would infer an authorized distribution.
4) On https://en.wikipedia.org/wiki/Special:BookSources/978-1934015254#Online_text I only see places to buy the book, nowhere to get it freely however.

I can see two versions of this book in the OpenLibrary:

Let Us C 3rd Edition:
https://archive.org/details/letusc3rdrevised00

Let Us C 7th Edition:
https://archive.org/details/zdanh_test_031_letusc00yash

These aren't e-books though, just scans of a physical book, and this would require an account to access the full version anyway.

**Comment by eshellman** [comment]
there are DMCA takedowns of this book, so I'm going to close this PR
https://lumendatabase.org/notices/21428028#

**Pull request closed without merging**
