### PR TITLE
chore(books-bn): split bangla books - courses

### LINKED ISSUE #6591: bangla books list is mostly courses
Need to split (or move) the list, there are plenty of courses.

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?

Add info | Improve repo

Splits `free-programming-books-bn.md` into two files, moving to `free-courses-bn.md` the YouTube videos.

Moreover, some minor reorganizations was made to address with consistency of listings (#4579):

- books::(`Android`) :arrow_forward: courses::(`Android`)
- books::(`Bootstrap`) :arrow_forward::arrows_clockwise: courses::(`HTML and CSS :: Bootstrap`)
- books::(`C`) :scissors: courses::(`C`)
- books::(`C++`) :arrow_forward: courses::(`C++`)
- books::(`C Sharp`) :arrow_forward::arrows_clockwise: courses::(`C#`)
- books::(`Competitive Programming`) :arrows_clockwise: books::(`Algorithms`)
- books:(`CSS`) :arrow_forward::arrows_clockwise: courses::(`HTML and CSS`)
- books:(`Dart`, `Flutter`, `Git`, `Go`) :arrow_forward: courses::(`Dart`, `Flutter`, `Git`, `Go`)
- books::(`HTML`) :arrow_forward::arrows_clockwise: courses::(`HTML and CSS`)
- books::(`Java`, `JavasScript`) :scissors: courses::(`Java`, `JavasScript`)
- books:(`jQuery`, `NodeJS`, `ReactJS`) :arrow_forward::arrows_clockwise: courses::(`JavasScript :: jQuery`, `JavasScript :: Node.js`, `JavasScript :: React`)
- books::(`Kotlin`, `MySQL`, `PHP`, `Svelte`, `TypeScript`) :arrow_forward: courses::(`Kotlin`, `MySQL`, `PHP`, `Svelte`, `TypeScript`)
- books::(`Python`) :scissors: courses::(`Python`)
- books::(`OOP`) :arrow_forward::arrows_clockwise: courses::(`Programming Paradigms`)
- books::(`Visual Studio Code`) :arrow_forward::arrows_clockwise: courses::(`IDE and editors`)

### Why is this valuable (or not)?

Implements #6591, Resolves #6591

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Consistency of listings (#4579)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by davorpa** [comment]
Conflicts with #6621

**Comment by eshellman** [comment]
what do the "waiting to add in" comments mean?

**Comment by davorpa** [comment]
> what do the "waiting to add in" comments mean?

C, C++ C#, produces the same non-meaningful hash more or less: c, c_1, c_2. So

It's for having the section defined with the "special alias" but not rendered. Therefore if someone adds resources, not is necessary to be worried about homogenize with the listings in other languages.

**Review by LuigiImVector — APPROVED** [review]

**Comment by eshellman** [comment]
Could you put it in markdown comments? The students I'm working with are parsing the markdown lists into JSON files, and markdown comments should be safer.

**Comment by davorpa** [comment]
> Could you put it in markdown comments? The students I'm working with are parsing the markdown lists into JSON files, and markdown comments should be safer.

There are not a special syntax for Markdown but can be simulated using a hack with link references to be compatible with all engines.

```markdown
[//]: # (whatever you want)
```

```markdown
[//]: # (
  whatever multiline
  you
  want
)
```


Kramdown engine have extensions like:
```
{::comment}
....
....
{:/comment}
```
but doesn't works in GitHub preview. In GitHub Pages yes.

**Comment by eshellman** [comment]
let's remove them and add notes to CONTRIBUTING instead

**Comment by davorpa** [comment]
> let's remove them and add notes to CONTRIBUTING instead

Done at 6d29234fabb955c286bb39fbbe365e31456e6e7b

**Review by LuigiImVector — APPROVED** [review]

**Pull request merged**
