### PR TITLE
Added Swift podcast

### PR DESCRIPTION
**Pull request by alexandersuerof**
## What does this PR do?
Created a title in podcast section for Swift Programming Language.

### Description
Is a podcast developed by Jonh Sundall. Where he shares ideas about iOS, Mac and Swift development in general.

### Why is this valuable (or not)?
Really great content and excellent quality.

### How do we know it's really free?
In the about section of [Swift by Sundell](https://www.swiftbysundell.com/about/) say: "All of this site’s content is freely accessible to anyone, in all countries around the world, and is regularly updated with new material for a wide range of skill levels."

### For book lists, is it a book? For course lists, is it a course? etc.
It's a podcast

### CODE REVIEW

**Comment by vineetvardhan27** [comment]
https://podcasts.apple.com/us/podcast/swift-by-sundell/id1267161825

**Comment by vineetvardhan27** [comment]
https://www.swiftbysundell.com/podcast/

**Comment by vineetvardhan27** [comment]
SWIFT BY SUNDELL
https://www.swiftbysundell.com/podcast/
https://podcasts.apple.com/us/podcast/swift-by-sundell/id1267161825
it can give you insight about swift

**Comment by alexandersuerof** [comment]
> can i get the 1 pull for the hacktober fest ?

I'm doing Hacktoberfest aswell.

**Pull request merged**
