### PR TITLE
Add resource

### PR DESCRIPTION
**Pull request by LuigiImVector**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

### For book lists, is it a book? For course lists, is it a course? etc.
It is a website but I think that it must be included. The website is monothematic and everything is sorted in appropriate sections.

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [X] Search for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
It's not a book, nor is it a book-like website. Some of the embedded videos are blocked. So I don't think we can include it.

**Comment by LuigiImVector** [comment]
> 
> 
> /lockthis: off-topic, not a book

I think it's a good resource and tried adding it to the others hoping for an exception.

**Comment by eshellman** [comment]
@LuigiImVector thank you for making the effort!

**Pull request closed without merging**
