### PR TITLE
Update free-programming-books.md

### PR DESCRIPTION
**Pull request by AnkitSharma-007**
Created a new category for ASP .NET Core and added a new book to it.

### CODE REVIEW

**Comment by eshellman** [comment]
not sure its helpful for users to separate the category. and that link is not a good one to use

**Comment by AnkitSharma-007** [comment]
ASP .NET and ASP .NET Core are two different frameworks. Therefore, I have separated the categories. 

Regarding the link, The author has hosted the book on GitHub so that he can update the contents with time. I am afraid this is the only link currently available for the book. 

Do you have any suggestions regarding this?

**Comment by eshellman** [comment]
one is described as a version of the other. not helpful to separate them unless the list is longer. 

ask the author to provide a better link

**Comment by AnkitSharma-007** [comment]
Unfortunately the author cannot provide any alternative links. I am closing the PR. 

Thanks.

**Pull request closed without merging**
