### PR TITLE
Created free-courses-fr.md

### PR DESCRIPTION
**Pull request by adamzebiche**
French file including +100 courses

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo
Adding a french file including +100 courses.
### Description 
This is mainly web development.
### Why is this valuable (or not)
Yes, I followed Grafikart, Pierre Giraud and Openclassrooms courses. These courses are very popular in the French Community.
### How do we know it's really free?
Content is mostly available on YouTube, OpenClassrooms courses can be viewed without creating an account.
### For book lists, is it a book?
No

### CODE REVIEW

**Comment by eshellman** [comment]
please fix linter errors.
for youtube, we prefer playlists
we prefer atomic commits

**Comment by x0rld** [comment]
openclassrom has a really bad reputation cause they don't even update the lessons over the time and many time the lessons has bad practice for now, for exemple the C++ lessons is not C++ modern and they use `using namespace std;` who is a bad practice cause it can add conflict
image

So in general all french people do not recommend openclassroom at all.

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by SethiPandi** [comment]
Closing this PR as a duplicate of https://github.com/EbookFoundation/free-programming-books/pull/3938

**Pull request closed without merging**
