### PR TITLE
New addition 3

### PR DESCRIPTION
**Pull request by apu52**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by apu52** [comment]
image

@eshellman can you please check the PR as it's showing the error where I don't have updated any type of codes

**Comment by apu52** [comment]
Please check it

**Review by sohansai — COMMENTED** [review]
The content is in English; move it to courses/free-courses-en.md

**Comment by sohansai** [comment]
> Please check it


Follow alphabetical ordering. Refer to CONTRIBUTING.md for more details.

**Pull request closed without merging**
