### PR TITLE
Pull Request: Add Hindi Translation for CONTRIBUTING.md (Changes Made)

### PR DESCRIPTION
**Pull request by anshumangahlot**
This pull request adds a Hindi translation of the CONTRIBUTING.md file, making the contribution process more accessible for Hindi-speaking developers.

**Changes:**

- A new file named CONTRIBUTING-hi.md has been created containing the Hindi translation of the existing CONTRIBUTING.md.

- The CONTRIBUTING.md file (English) has been updated to include a link to the Hindi translation (CONTRIBUTING-hi.md).

**Benefits:**

- Increases accessibility for the Hindi developer community.

- Encourages a wider range of contributors to participate in the project.

- Fosters a more inclusive development environment.

**Testing:**

- The translation has been reviewed for accuracy and clarity in Hindi.

**Feedback Welcome:**

- We welcome any feedback or suggestions on the translation or the approach used.

**Additional Notes:**

- This pull request is ready for review and merging.

### CODE REVIEW

**Comment by anshumangahlot** [comment]
Please add me to label for hacktoberfest accepted.

**Comment by eshellman** [comment]
in addition to review, this PR needs to add a link to README

**Comment by anshumangahlot** [comment]
A link has been added to README for CONTRIBUTING-hi.md file. Kindly check the update and let me know if I have to change something else.

**Comment by eshellman** [comment]
thanks, we're just waiting for a hindi reviewer.

**Comment by GuptajiRocks** [comment]
I am a native hindi speaker. 
Can verify the authenticity.
LGTM.

**Comment by anshumangahlot** [comment]
Sure go ahead and let me know if any changes are required.
@GuptajiRocks

**Comment by GuptajiRocks** [comment]
No changed are required. 
Good to merge.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!
@GuptajiRocks thanks for review

**Comment by anshumangahlot** [comment]
Please add the Hacktober-accepted label to my PR

**Comment by GuptajiRocks** [comment]
> Thanks, and welcome to free-programming-books! @GuptajiRocks thanks for review

No problem @eshellman 
Cheers!

**Pull request merged**
