### PR TITLE
Kubernetes Deployment & Security Patterns added

### PR DESCRIPTION
**Pull request by ahmetcetin**
## What does this PR do?
Add resource

### Description
Deployment and security strategies for Kubernetes

### Why is this valuable (or not)?
Published by Cloud Native Computing Foundation, where Kubernetes project graduated from, it's practical guide for deploying and securing Kubernetes clusters

### How do we know it's really free?
Published by CNCF in their website

### For book lists, is it a book? For course lists, is it a course? etc.
Book

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [X] Search for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
you've added the book into the index; it would fit better into the kubernetes section on the languages page.

**Comment by ahmetcetin** [comment]
Hi, I've checked the languages page first in fact, and couldn't find Kubernetes section there. There were two books related with the Kubernetes but one is under Java, the other is under .NET. Then I found Cloud Computing section under books by subjects file, and in fact Kubernetes fits to Cloud Computing indeed, that's why I filed it here. Would you like me to create a Kubernetes section in languages file?

**Comment by eshellman** [comment]
just put it with the other kubernetes books - might be under containers

**Comment by ahmetcetin** [comment]
Sorry for stealing your time, I've just noticed what you mean, it was in index. Just moved it into Containers section.

**Review by davorpa — APPROVED** [review]
### Ready to merge :fireworks: :tada:

Thanks for your improvements

**Pull request merged**
