### PR TITLE
Build a Blockchain from Scratch in Go with gRPC

### PR DESCRIPTION
**Pull request by volodymyrprokopyuk**
## What does this PR do?
Add a resource

### Why is this valuable (or not)?

I've developed a blockchain from scratch in Go with gRPC for learning purposes. I've also written the guide that explains the design of the blockchain along with practical usage examples. I hope the guide will help to effectively learn the blockchain concepts and progressively build a blockchain from scratch in Go with gRPC

### How do we know it's really free?

I'm the author. The source code of the proposed blockchain and the book are available from a public repository on GitHub

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by volodymyrprokopyuk** [comment]
Hi,
I'm the author of the resource. The resource name is Build a blockchain from scratch in Go with gRPC. This name is too large to be a repository name, hence the `go-blockchain` repository name.
Thank you!

**Comment by eshellman** [comment]
how would a contributor who was not the author know that that was the title? We need to use titles that are obvious from the resource, without mindreading. This helps us avoid duplicates and edit wars. You could change the title on the README page of course, if you want us to use that title.

**Comment by eshellman** [comment]
you may be interested to know that repo names up to 100 characters are permitted in giithub

**Comment by volodymyrprokopyuk** [comment]
Hi,
The Go blockchain title was the initial placeholder in the README. Thank you for pointing this out. I've update the README to match the purpose of the proposed blockchain, as well as match the title of this pull request.
Thank you!

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
