### PR TITLE
use current node-version 16

### PR DESCRIPTION
**Pull request by Debajyotighosh654**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
needs review

**Review by vhf — APPROVED** [review]
lgtm

**Review by SethFalco — APPROVED** [review]

**Comment by SethFalco** [comment]
Worth noting you can tell the change doesn't break anything because the workflow for this very PR used Node 16.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
