### PR TITLE
add some free Arabic programming books

### PR DESCRIPTION
**Pull request by WatheqAlshowaiter**
## What does this PR do?
Add resources

### Why is this valuable (or not)?
yes :)

### How do we know it's really free?
you can watch the links from [Hsoub Academey](https://academy.hsoub.com/files/). all of their books are free.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Include author(s) and platform where appropriate.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
The linter is fussy about spaces

**Comment by WatheqAlshowaiter** [comment]
I will correct them. thank you.

**Comment by WatheqAlshowaiter** [comment]
I hope its fine now :)

**Comment by eshellman** [comment]
Looks good!
Thanks, and welcome to free-programming-books!

**Comment by WatheqAlshowaiter** [comment]
thank you first for this awesome list, which I benefited from a lot.

**Pull request merged**
