### PR TITLE
Update free-courses-ru.md

### PR DESCRIPTION
**Pull request by IgorLutiy**
Add three new courses

## What does this PR do?
Add resource(s) 

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [x] Search for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
Add instructor names to disambiguate.

**Comment by IgorLutiy** [comment]
Well, I think i added authors

**Comment by eshellman** [comment]
for the python courses, one is titled "Поколение Python": курс для продвинутых while the other is "Поколение Python": курс для начинающих
Don't invent titles! Use the title given by the resource.

**Comment by IgorLutiy** [comment]
> for the python courses, one is titled "Поколение Python": курс для продвинутых while the other is "Поколение Python": курс для начинающих
> Don't invent titles! Use the title given by the resource.

Its original titles

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
