### PR TITLE
Adding a lot of Beej's Guides and their official translations.

### PR DESCRIPTION
**Pull request by kakashi215**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s)

### Description
Adding a lot of Beej's Guides and their official translations.

### Why is this valuable (or not)?
Really valuable books.

### How do we know it's really free?
As mentioned on the official website.

### For book lists, is it a book? For course lists, is it a course? etc.
Books.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Overdue additions!
Please add author names where appropriate. (Maybe not needed where "Beej" is already in the title, consider adding translator name - your decision; I would generally add it if its on the title page.)

**Comment by kakashi215** [comment]
Is this a good way to add the translator name?
@eshellman 
* [Socket Programmierung in C](http://www.tobscore.com/socket-programmierung-in-c/) - Translated by Tobias Kerst (HTML)

**Comment by kakashi215** [comment]
> Is this a good way to add the translator name?
> @eshellman
> 
> * [Socket Programmierung in C](http://www.tobscore.com/socket-programmierung-in-c/) - Translated by Tobias Kerst (HTML)

I have made the changes according to the above format. I won't push those changes until you confirm.
Suggestions are welcome.

**Comment by eshellman** [comment]
your format for translator looks fine; the author should be added to the german entry
Socket Programmierung in C - B. Hall, translated by Tobias Kerst (HTML)

**Comment by kakashi215** [comment]
I'll add authors and translators both as per the above format on all entries.

**Comment by kakashi215** [comment]
@eshellman I think this completes the work on this PR.
Lemme know of any other requested changes.

**Pull request merged**
