### PR TITLE
Update free-programming-books.md

### PR DESCRIPTION
**Pull request by packtpartner**
Added 4 book listings

### CODE REVIEW

**Comment by eshellman** [comment]
Thanks for these additions. The lists need to be ordered alphabetically by title.

**Comment by packtpartner** [comment]
Thanks for your feedback. It's been done.

**Comment by eshellman** [comment]
Could you add back the notations about email address requests? We want the notations to be to be uniform and fair; if you prefer different wording, suggest it for discussion in an issue.

**Comment by packtpartner** [comment]
Instead of this "(Just fill the fields with any values)" email address notation, can we add/suggest "(Opt-in required)"?

**Comment by eshellman** [comment]
propose the wording on an issue. similar notes apply to OReilly, Leanpub, Bookboon and Syncfusion and I think our lists should be fair to each.

**Comment by packtpartner** [comment]
Thanks. 
We've submitted a new issue.

**Pull request merged**
