### PR TITLE
Add Runestone Interactive Python Guide

### PR DESCRIPTION
**Pull request by kevinlwebb**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s)

### Description 
The mission of Runestone Interactive is to democratize textbooks for the 21st century. Textbook prices are too high, and paper textbooks are too old fashioned. They are changing that.

### Why is this valuable (or not)?
1. Free
2. Interactive
3. The guide starts at the very beginning and delves into very complex topics

### How do we know it's really free?
You can simply access the website.

### For book lists, is it a book? For course lists, is it a course? etc.
This is an interactive tutorial

### Checklist:
- [X] Not a duplicate
- [X] Included author(s) if appropriate
- [X] Lists are in alphabetical order
- [X] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Please add author names where appropriate.

**Comment by eshellman** [comment]
Nice addition, but some attribution would help

**Comment by kevinlwebb** [comment]
@eshellman sorry for the newbie question: how do I resubmit a PR? I just pushed my changes

**Comment by eshellman** [comment]
you figured it out!

**Pull request merged**
