### PR TITLE
Added best book for programming beginner to advanced!!

### PR DESCRIPTION
**Pull request by inbuilt-aura**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by shrn01 — COMMENTED** [review]
Please add the resources in the respective files. Please read [contribution guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md) for more information

**Comment by inbuilt-aura** [comment]
@shrn01,plzz check above

**Comment by shrn01** [comment]
Hey @inbuilt-aura we have specific files for each kind of resource already available in the repo. So please use the proper file to add the links to the resources that are free and useful

**Comment by inbuilt-aura** [comment]
@shrn01, so you want me to first upload each file in Google drive and then share their link there, correct?

**Pull request closed without merging**
