### PR TITLE
add resource Belajar Dengan Jenius Golang and fix error blank lines

### PR DESCRIPTION
**Pull request by azizramdan**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s)

### Description 
Ebook (PDF) for golang in Indonesian
It also fix error i"ncorrect number of blank lines between last section and next heading" in CI

### Why is this valuable (or not)?
Because it provide an ebook it self and the resources for ebook

### How do we know it's really free?
This is hosted on github repo

### For book lists, is it a book? For course lists, is it a course? etc.
This is ebook

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
where is the book content on this resource?

**Comment by azizramdan** [comment]
@eshellman here [https://github.com/gungunfebrianza/Belajar-Dengan-Jenius-Golang/blob/master/Belajar%20Dengan%20Jenius%20Golang.pdf](https://github.com/gungunfebrianza/Belajar-Dengan-Jenius-Golang/blob/master/Belajar%20Dengan%20Jenius%20Golang.pdf) should I link a repo or PDF?

**Comment by eshellman** [comment]
much better! the repo if it presents a Readme with link to the pdf. otherwise, use the 'raw' link to the pdf.

**Comment by azizramdan** [comment]
@eshellman check my last commit, I replace with raw link

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
