### PR TITLE
Added python basics book

### PR DESCRIPTION
**Pull request by rajdeep-biswas**
## What does this PR do?
Add resource(s)

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [ ] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by rajdeep-biswas** [comment]
Requesting label: "Hacktoberfest-accepted".

**Review by shrn01 — COMMENTED** [review]
Looks like this is just a sample. Would it be a value add?

**Comment by rajdeep-biswas** [comment]
Having some of the chapter, I believe, counts as free resource.

**Comment by rajdeep-biswas** [comment]
Having some of the chapters, I believe, counts as free resource.

**Comment by eshellman** [comment]
we don't accept sample chapters

**Pull request closed without merging**
