### PR TITLE
Add markdown="1" attribute to div

### LINKED ISSUE #6691: bug: Apply kramdown `markdown="1"` attribute when necessary
Previewing #6677 I realize now that #6662 is broken.

image

To solve, it needs add `markdown="1"` attribute to `<div>` too

https://github.com/EbookFoundation/free-programming-books/blob/7fdc28d3809a001657578130f6afc79211d9bf26/README.md#L6-L11

_Originally posted by @davorpa in https://github.com/EbookFoundation/free-programming-books/issues/6677#issuecomment-1026075701_

Apply in other places where is necessary too.

### PR DESCRIPTION
**Pull request by Sync271**
## What does this PR do?
Fixes #6691 

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [x] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up
I've checked for other places where there are div(s) inside .md files, all of them already have the `markdown="1"` attribute, if I've missed any, request changes and let me know where I've missed

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by LuigiImVector — APPROVED** [review]
Next time activate "github pages" in your repository to allow us to test the page

**Comment by Sync271** [comment]
> Next time activate "github pages" in your repository to allow us to test the page; I tested your code in my repository and it works: https://luigiimvector.github.io/free-programming-books/

Will do!

**Comment by davorpa** [comment]
Thanks @LuigiImVector for testing and @Sync271 for the quick fix. You are the best :wink:

**Review by davorpa — APPROVED** [review]
LGTM too :love_you_gesture:

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books, @Sync271 !

**Pull request merged**
