### PR TITLE
add new araic courses

### PR DESCRIPTION
**Pull request by AhmedElTabarani**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by AhmedElTabarani** [comment]
I don't think this mistake check is right

```js
* [ReactJS Part 3 - Performance Optimization (react memo, use memo, use call back) [تعلم الرياكت] [الجزء الثالث]](https://www.youtube.com/playlist?list=PLejc1JbD4ZFTYdkjzqYBujf7UCVQyn_aq) - kimz codes
* [ReactJs-Build Full E-Commerce From Scratch Redux (بالعربي)](https://www.youtube.com/playlist?list=PLDQ11FgmbqQPRui5VDCSQvYt2HOYiCVep) - Programming Solutions - Academy
```

`S` is lower than `s`

I also try to sort all the React courses
and it gives me the same order of mine

image

**Comment by AhmedElTabarani** [comment]
also i notice some error here
in RTL we must put `\` after `|` like this `|\`

Screenshot 2022-04-30 222028

image

**Comment by AhmedElTabarani** [comment]
last thing, the `github lint checking` didn't warn us about this missing space here,

image

**Comment by davorpa** [comment]
> also i notice some error here in RTL we must put `\` after `|` like this `|\`
> 
> Screenshot 2022-04-30 222028
> 
> image

`\|` not is for render. it's for Markdown escape pipe. See bug #6723. So `|` should only be rendered

**Comment by davorpa** [comment]
> I don't think this mistake check is right
> 
> ```js
> * [ReactJS Part 3 - Performance Optimization (react memo, use memo, use call back) [تعلم الرياكت] [الجزء الثالث]](https://www.youtube.com/playlist?list=PLejc1JbD4ZFTYdkjzqYBujf7UCVQyn_aq) - kimz codes
> * [ReactJs-Build Full E-Commerce From Scratch Redux (بالعربي)](https://www.youtube.com/playlist?list=PLDQ11FgmbqQPRui5VDCSQvYt2HOYiCVep) - Programming Solutions - Academy
> ```
> 
> `S` is lower than `s`
> 
> I also try to sort all the React courses and it gives me the same order of mine
> 
> image

Alphabetization is much more than a merelly `Array.sort()`. The remark plugin strip some characters and use Collators to sort the result according to natural language

**Comment by AhmedElTabarani** [comment]
> See https://github.com/vhf/remark-lint-alphabetize-lists

I install it and run `remark -u lint -u lint-alphabetize-lists courses\free-courses-ar.md `

the output is more than the PR lint checking

image

**Comment by AhmedElTabarani** [comment]
ok I take the function that normalize the text from []() and try it with sort, and it gives me the right order

image

**Comment by AhmedElTabarani** [comment]
I will try to make the script that ordered all courses automatic

**Comment by davorpa** [comment]
> ok I take the function that normalize the text from [here](https://github.com/vhf/remark-lint-alphabetize-lists/blob/master/lib/alphabetical-list-items.js?rgh-link-date=2022-04-30T23%3A58%3A11Z) and try it with sort, and it gives me the right order
> 
> image

Nice minitool to quickly sort fpb resources. Thanks

**Review by davorpa — APPROVED** [review]
LGTM :heart:

Talking about pipes again.... since #6766 there are a problem with rendering and pipes.
image
https://davorpa.github.io/free-programming-books/courses/free-courses-ar.html#python

Could you solve it?

Line 299 in python section https://github.com/EbookFoundation/free-programming-books/pull/6837/files#diff-8320e28bfe50c127b098d3941c4ab68e96d90e34e8559c5b92daa3dfc875ce7fL275-R299

Escape both `||`

**Comment by davorpa** [comment]
> LGTM ❤️
> 
> Talking about pipes again.... since #6766 there are a problem with rendering and pipes. image [davorpa.github.io/free-programming-books/courses/free-courses-ar.html#python](https://davorpa.github.io/free-programming-books/courses/free-courses-ar.html#python)
> 
> Could you solve it?
> 
> Line 299 in python section [#6837 (files)](https://github.com/EbookFoundation/free-programming-books/pull/6837/files#diff-8320e28bfe50c127b098d3941c4ab68e96d90e34e8559c5b92daa3dfc875ce7fL275-R299)
> 
> Escape both `||`

**Review by davorpa — APPROVED** [review]

**Comment by eshellman** [comment]
thanks, everyone

**Pull request merged**
