### PR TITLE
Add App Inventor category and book

### PR DESCRIPTION
**Pull request by espertus**
## What does this PR do?
Add resource(s)

### Description

Add App Inventor category and book.

I added "App Inventor" as a category because "Scratch" is a category. Both are block programming languages.

If the maintainers prefer, it could be put in the existing "Android" category because App Inventor (currently) creates apps only for Android.

### Why is this valuable (or not)?

It's a free book.

### How do we know it's really free?

- I'm a co-author.
- There is a Creative Commons license on the linked page.

### For book lists, is it a book? For course lists, is it a course? etc.

It is a book.

## Checklist:
- [ X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ X] Search for duplicates.
- [ X] Include author(s) and platform where appropriate.
- [ X] Put lists  in alphabetical order, correct spacing.
- [ X] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
We choose categories to help people find the items they're interested in. And we try to avoid making categories for single items. So "Android" seems a better choice.

**Comment by espertus** [comment]
Thank you! I've posted to the App Inventor forum to ask if there are any other free books about App Inventor. When I hear back, I will either add another or remove the new category, then resubmit the PR.

**Comment by espertus** [comment]
Should the list include a [book](https://amerkashi.wordpress.com/2015/02/16/absolute-app-inventor-2-book/) available for $0.00 on commercial sites?

**Comment by eshellman** [comment]
The main problem we have with commercially offered free ebooks is that they tend to stop being free, and they're hard to link-check. Submitters can use their judgment as to whether it's worth it. Amazon actually charges authors for distribution of free ebooks!

**Comment by espertus** [comment]
I added a second App Inventor book. Let me know if you'd like App Inventor to be a subsection under Android, rather than its own section. The only caveat is that [App Inventor for iOS](https://appinventor.mit.edu/blogs/evan/2021/03/04-mit-app-inventor-ios-app-store) is being rolled out, so it is ceasing to be Android-only.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!
Thanks for making you book free! If it has an Open License, consider adding it to Unglue.it and Archive.org.

**Pull request merged**
