### PR TITLE
add roadmap.sh roadmaps as course content

### PR DESCRIPTION
**Pull request by dansholds**
## What does this PR do?
Add resource(s) 

### Description
I've added roadmap.sh roadmaps in every en course section that they exist for.

### Why is this valuable (or not)?
roadmap.sh is #6 on GitHub and it is widely regarded as a great free resource for all developer topics.

### How do we know it's really free?
You can access all roadmap without even needing to create an account.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
I think a single entry for this site belongs in https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-subjects.md#0---meta-lists  

Does roadmaps.sh link to free-programming-books?

**Comment by dansholds** [comment]
> I think a single entry for this site belongs in https://github.com/EbookFoundation/free-programming-books/blob/main/books/free-programming-books-subjects.md#0---meta-lists
> 
> Does roadmaps.sh link to free-programming-books?

I see why you say that, although various other creators like FreeCodeCamp feature in the majority of sections rather than in one location?

If you can find a logical place for Roadmap.sh to link to free-programming-books then we would be happy to!

**Comment by eshellman** [comment]
To take python as an example. We get submissions for websites about python, blogs about python, articles about python, etc. We don't accept those. Scope creep. We take books, courses, interactive tutorials, cheatsheets and playgrounds. I would describe roadmap.sh as being akin to a nonlinear course syllabus; we don't accept syllabi. The section I suggested has a number of other hard-to categorize resources that don't quite fit in our other lists.

F-P-B organizes resources in an outline. I can imagine some sort of overlay map that folks would find really useful.

**Comment by dansholds** [comment]
Ok that makes perfect sense now thanks! I'm happy to go from the 30 additions to the one in the meta section 😅

Happy to work with you in regards to what roadmap.sh can do, just let me know! 🙏

**Comment by dansholds** [comment]
@eshellman I've removed all additions of roadmap.sh and only added it to the MOOC section 👍

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
