### PR TITLE
Add zh cast file and excellent podcasts

### PR DESCRIPTION
**Pull request by Kashinggo**
## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo
Add resources

### Description
Add zh cast file and excellent podcasts

### Why is this valuable (or not)?
Audience can learn from these tech talk, focusing on different tech stack. Also find their community.

### How do we know it's really free?
These podcasts can be  listened to for free.

### For book lists, is it a book? For course lists, is it a course? etc.
Cast lists.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
could you add podcast/screencast notations and add a link from README

**Comment by Kashinggo** [comment]
Done, thanks!

**Comment by davorpa** [comment]
> Done, thanks!

It left (screencast/podcast) notations. See the english file to an example.

**Comment by Kashinggo** [comment]
> > Done, thanks!
> 
> It left (screencast/podcast) notations. See the english file to an example.

I see. Cool!

**Review by davorpa — APPROVED** [review]

**Pull request merged**
