### PR TITLE
Updated Hindi books resources

### PR DESCRIPTION
**Pull request by pineapples5972**
Added some blog links and pdf for C, Python, Java, PHP, Linux and Hindawi Project

## What does this PR do?
It adds resources and Improve repo

### Why is this valuable (or not)?
It is valuable for hindi language users to learn programming in their native language.

### How do we know it's really free?
The pdfs and blog links are publicly available. Maintainers can verify themeselve with simple google search.

### For book lists, is it a book? For course lists, is it a course? etc.
Yeah there are some free pdfs and courses with proper indexed resources.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by pineapples5972** [comment]
I dont understand whats wrong with CI checks.
I followed existing layout of file.
If anyone knows how to fix CI checks let me know.

**Comment by eshellman** [comment]
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.
don't need anchors unless topic has + in it, or needs disambiguation. See other lists.

**Comment by pineapples5972** [comment]
> Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems. don't need anchors unless topic has + in it, or needs disambiguation. See other lists.

Yes, I have done that and it look like to me all the checks have passed now.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by pineapples5972** [comment]
Thanks @eshellman.
Is hactober fest over yet. 
can you add hacktoberfest-accepted label to PR if you find fitted to it.

**Pull request merged**
