### PR TITLE
Add tutorial rails girls

### PR DESCRIPTION
**Pull request by ifdiego**
Add tutorial Rails Girls in PT-BR for Ruby section.

### CODE REVIEW

**Comment by eshellman** [comment]
I think I'd put this in free-courses-pt_BR.md

**Comment by ifdiego** [comment]
@eshellman Alright, I've just changed :)

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by ifdiego** [comment]
@eshellman Hey, I just noticed that Django Girls tutorial is listed in free-programming-books-pt_BR.md and it's duplicated too.
Can I make a pull request to changed it to free-courses-pt_BR.md and removing the duplicated one?

**Pull request merged**
