### PR TITLE
Added OdinProject Resources

### PR DESCRIPTION
**Pull request by kronicle114**
## What does this PR do?
**Add Resource(s)** 

### Description 
* Added HTML & CSS, Ruby, Ruby On Rails, and JavaScript free course tutorials from [The Odin Project](https://www.theodinproject.com/home)
### Why is this valuable (or not)
* Easy to read, step by step free courses that is project based. 
>The Odin Project is for absolute beginners and those who have tried other resources without success. In reality, The Odin Project is for anyone who wants to work as a web developer, do freelancing work, build a startup, or just hack together a homepage for yourself. All the tools you need are here.
>We’ve built an in-depth curriculum designed to take you 100% of the way to becoming a web developer. Many other resources out there teach you just the basics of programming. With The Odin Project you’ll create your own websites, games, and social media sites. 
>The curriculum has also been designed in a modular fashion, making skimming through lessons a breeze.
### How do we know it's really free?
* On Website's [F.A.Q. ](https://www.theodinproject.com/faq?ref=homehav) it says the resource is free:
>Yes! The Odin Project is an open-source project created and maintained by hard working volunteers. To find out how you can help us, please visit our how to contribute page.
### For book lists, is it a book?
* Technically it's a free course
### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
These look great! But wouldn't they fit better on the free-courses page?

**Comment by ShipsWithCannons** [comment]
@eshellman Absolutely. They're on `free-programming-books.md` while they should be on `free-courses-en.md`. Which means this feature request should be split. Remove the old link, which is indeed no longer required and was in the wrong place anyway, but add the new link to a different file.

**Comment by kronicle114** [comment]
Ah! Thanks. This feature is already added on [free-courses-en.md](https://github.com/EbookFoundation/free-programming-books/blob/master/free-courses-en.md)
This was a learning experience.

**Comment by eshellman** [comment]
Good to hear. (That it was a positive experience, *and* that we weren't missing the course.)

**Pull request closed without merging**
