### PR TITLE
Update HOWTO-zh.md

### PR DESCRIPTION
**Pull request by HelloSeaNation**
Updated minor fix for translation in HOWTO-zh.md

## What does this PR do?
Translate changes, 
I found out some mistake in the translation from previous person who did the translation, and got it fix. 

## Checklist:
- [ done] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by davorpa — APPROVED** [review]
It satify #5644 

### Ready to merge :fireworks: :tada:

**Comment by HelloSeaNation** [comment]
@davorpa I'm not sure what does the PR threads means.. Anyway I've rechecked my changes and found that I accidentally remove some existing blank lines. I've fixed those and made some translations improvement and I'm pretty happy with those changes now and they're now ready for review again.

**Comment by davorpa** [comment]
> @davorpa I'm not sure what does the PR threads means.. 

This is a PR thread, the other are issues :wink:

**Review by davorpa — APPROVED** [review]
### Ready to merge :fireworks: :tada:

**Pull request merged**
