### PR TITLE
Fixed markdown for titles

### PR DESCRIPTION
**Pull request by MerlinDuChaos**
## What does this PR do?
Improve Repo

### Checklist:
- [x ] Not a duplicate
- [x ] Included author(s) if appropriate
- [x ] Lists are in alphabetical order
- [x ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
This is a good correction, but could you resolve conflicts? thanks!

**Comment by MerlinDuChaos** [comment]
I don't think this change is needed anymore, as the update which added numbering to some entries also fixed the titles.

**Comment by MerlinDuChaos** [comment]
What I don't understand is why the version I checked out is so different that the one I can see now in the master branch (the actual one which is displayed).

It looks like I had a different version when I forked (mine has no numbering for instance).

**Comment by eshellman** [comment]
The effort is appreciated!

**Comment by MerlinDuChaos** [comment]
You're welcome, thanks for this repository !

**Pull request closed without merging**
