### PR TITLE
Update free-courses-pt_BR.md

### PR DESCRIPTION
**Pull request by lvmenezes**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Could you please keep the lists in alphabetical order?

Not sure why the checks passed for this, but it should've complained about it as well I believe.

You can get more guidance on the formatting or conventions in this repository by checking out the contribution guide (CONTRIBUTING.md).

**Comment by lvmenezes** [comment]
I have made the adjustment.

Em ter., 20 de out. de 2020 às 22:38, Eric Hellman <notifications@github.com>
escreveu:

**Comment by SethiPandi** [comment]
Please remove the extra line breaks you added.

**Review by lvmenezes — COMMENTED** [review]
Done

**Comment by lvmenezes** [comment]
Done.

Em dom., 25 de out. de 2020 às 15:29, Seth <notifications@github.com>
escreveu:

**Comment by eshellman** [comment]
Looks like the actual course is at Youtube https://www.youtube.com/playlist?list=PLHz_AreHm4dm4beCCCmW4xwpmLf6EHY9k 
your link is to a blog and is filled with low quality ads.

**Review by lvmenezes — COMMENTED** [review]
I made an adjustment pointing the URL directly to the video playlist and not to the blog that made the post.

**Comment by eshellman** [comment]
For youtube, we prefer "playlist" links and the name of the producer/creator. https://www.youtube.com/playlist?list=PLHz_AreHm4dm4beCCCmW4xwpmLf6EHY9k

**Pull request closed without merging**
