### PR TITLE
Update free-courses-pt_BR.md

### PR DESCRIPTION
**Pull request by maribarcelos1**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Could you please ensure all lists and categories retain alphabetical order?

Also for the YouTube playlists, we generally prefer links to the playlist endpoint rather than the watch endpoint, ie:
https://www.youtube.com/playlist?list=PLvE-ZAFRgX8hnECDn1v9HNTI71veL3oW0

**Comment by eshellman** [comment]
rerunning checks....

**Comment by eshellman** [comment]
Be sure to check the output of Travis-CI for linter errors. Alphabetical order and spacing are the most common problems.

**Comment by kadhirash** [comment]
Closing since full playlist link has already been added

**Pull request closed without merging**
