### PR TITLE
Correct linter error in bn language files

### PR DESCRIPTION
**Pull request by kn1-gh7**
## What does this PR do?
Improve repo

### Description
Corrects the alphabetical order of free-programming-books-bn.md and free-courses-bn.md. Highlighted in issue #10557.
### Why is this valuable (or not)?
Yes as other PRs are failing tests due to this.
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Thenlie** [comment]
Due to recent updates in free-programming-books-lint, this test is failing as it is picking up on the incorrect alphabetization in this file. If you could update these alphabetization issues that would be awesome!

**Comment by kn1-gh7** [comment]
@Thenlie that's the problem. I am using online sorters which says that this is the correct order. But the linter is picking up wrong albhabetization. And if I remove the lines the warning show, the linter shows warning with spaces and other stuff between categories.

**Comment by Thenlie** [comment]
> @Thenlie that's the problem. I am using online sorters which says that this is the correct order. But the linter is picking up wrong albhabetization. And if I remove the lines the warning show, the linter shows warning with spaces and other stuff between categories.

From what I can see that lint output is correct. This file had errors prior to this PR. I will post a diff shortly.

**Comment by sohansai** [comment]
Please keep changes on this PR. don't close it and start a new one. It's not respectful to the reviewers because it erases the reviews.

**Comment by kn1-gh7** [comment]
> > @Thenlie that's the problem. I am using online sorters which says that this is the correct order. But the linter is picking up wrong albhabetization. And if I remove the lines the warning show, the linter shows warning with spaces and other stuff between categories.
> 
> From what I can see that lint output is correct. This file had errors prior to this PR. I will post a diff shortly.

Yes you are right. I have done those changes. But the linter os facing issue when has to compare english and the bangla language and I'm unable to understand what to do here. If you're able to understand the issue kindle reciprocate. Thanks for investing time in this.

**Comment by Thenlie** [comment]
> Yes you are right. I have done those changes. But the linter is facing issue when has to compare english and the bangla language and I'm unable to understand what to do here. If you're able to understand the issue kindle reciprocate. Thanks for investing time in this.

@kn1-gh7 Here is a patch file with the correct lint changes. It looks like the alphabetizer wants bangla text to go first followed by english. You can apply this patch to your branch with `git apply path-to-diff.patch`. 

[diff.patch](https://github.com/EbookFoundation/free-programming-books/files/13056433/diff.patch)

**Comment by kn1-gh7** [comment]
> Please keep changes on this PR. don't close it and start a new one. It's not respectful to the reviewers because it erases the reviews.

Yes, I am sorry. I thought that the PR was useless at first but then thought that the errors encountered in different commits might help to debug the issue. Really sorry if it was disrespectful for anyone.

**Comment by kn1-gh7** [comment]
> > Yes you are right. I have done those changes. But the linter is facing issue when has to compare english and the bangla language and I'm unable to understand what to do here. If you're able to understand the issue kindle reciprocate. Thanks for investing time in this.
> 
> @kn1-gh7 Here is a patch file with the correct lint changes. It looks like the alphabetizer wants bangla text to go first followed by english. You can apply this patch to your branch with `git apply path-to-diff.patch`.
> 
> [diff.patch](https://github.com/EbookFoundation/free-programming-books/files/13056433/diff.patch)

sure let me try

**Comment by kn1-gh7** [comment]
@Thenlie thanks a lot for helping out. This worked now!

**Comment by Thenlie** [comment]
> @Thenlie thanks a lot for helping out. This worked now! I completely ignored the courses file and was only correcting the books file. Apologies. Also should I commit these in my previous PR in which I first noticed the issue? Or will this PR be merged separately?

Let's just leave it here for now. Thank you for making those changes!

@eshellman, this PR contains the alphabetization fixes for Bangla. That probably makes is slightly higher priority.

**Review by Thenlie — APPROVED** [review]

**Pull request merged**
