### PR TITLE
Number theory course in bangla

### PR DESCRIPTION
**Pull request by khalid586**
## What does this PR do?
Add resource(s)

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
why is it "Competitive Programming" rather than "Mathematics" or maybe "Algorithms"?

**Comment by khalid586** [comment]
Number theory is heavily used in competitive programming and the creator's intention was to help competitive programmers. That's why I added this course under this section.

**Comment by eshellman** [comment]
someone looking for a resource in number theory would never look in "competitive programming". Think about the helping the user.

**Comment by khalid586** [comment]
okay...then i can add this to algorithms section as it is focused on implementation of some number theory concepts using C++.

**Pull request closed without merging**
