### PR TITLE
Add Algorithm books to TR booklist

### PR DESCRIPTION
**Pull request by Yutyo**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s)

### Why is this valuable (or not)?
Academic books beneficial for programming

### How do we know it's really free?
Shared under public license

### For book lists, is it a book? For course lists, is it a course? etc.
They are books

### Checklist:
- [ ✔] Not a duplicate
- [ ✔] Included author(s) if appropriate
- [ ✔] Lists are in alphabetical order
- [ ✔] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Hey, and welcome to free programming books! :wave:

Could you please ensure all sections and subsections have 2 line breaks above them?
> 2 empty lines between last link and new section  
> 1 empty line between heading & first link of its section  
> 0 empty line between two links  
> 1 empty line at the end of each .md file  
> \- https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#formatting

We don't accept links to online cloud storage providers such as Google Drive, OneDrive, Nextcloud, etc. Could you please find a first party or authoritative source for the resource, for example, the author, publisher, or an authorized distributor.

You can get more guidance on the formatting and conventions in this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).

You can click on the failed checks to get more information on any check failures. You'll be able to see exactly what was wrong and how to fix it.

**Comment by Yutyo** [comment]
Done. 😁

> Hey, and welcome to free programming books! wave
> 
> Could you please ensure all sections and subsections have 2 line breaks above them?
> 
> > 2 empty lines between last link and new section
> > 1 empty line between heading & first link of its section
> > 0 empty line between two links
> > 1 empty line at the end of each .md file
> > - https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md#formatting
> 
> We don't accept links to online cloud storage providers such as Google Drive, OneDrive, Nextcloud, etc. Could you please find a first party or authoritative source for the resource, for example, the author, publisher, or an authorized distributor.
> 
> You can get more guidance on the formatting and conventions in this repository by checking out the [contribution guide](https://www.github.com/EbookFoundation/free-programming-books/tree/master/CONTRIBUTING.md).
> 
> You can click on the failed checks to get more information on any check failures. You'll be able to see exactly what was wrong and how to fix it.

**Comment by Yutyo** [comment]
Publishers accepted their sources to be shared in Internet Archive, a reliable source for public media. Is it OK?

**Comment by SethiPandi** [comment]
> Publishers accepted their sources to be shared in Internet Archive, a reliable source for public media. Is it OK?

I believe that should be cool! (If I'm wrong, someone else will correct me.)

Could you please just look through the linting errors on Travis?

* Links that go directly to a PDF file should have `(PDF)` at the end of them.
* Lists and categories should be in alphabetical order.
* There should be 2 line breaks above new sections or subsections.

**Comment by Yutyo** [comment]
I think its OK now and idk why Travis still fails.

I fixed everything imo

**Comment by SethiPandi** [comment]
```bash
/home/travis/build/EbookFoundation/free-programming-books/free-programming-books-tr.md

    29:1-32:200  warning  Alphabetical ordering: swap l.30 and l.29                              alphabetize-lists      remark-lint

    29:1-32:200  warning  Alphabetical ordering: swap l.31 and l.30                              alphabetize-lists      remark-lint

  30:211-30:260  warning  Remove trailing slash (http://ikucukkoc.baun.edu.tr)                   no-url-trailing-slash  remark-lint

    75:1-75:110  warning  Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2      remark-lint
```

You can just check the Travis CI Details to see exactly what it's complaining about.

**Comment by eshellman** [comment]
please remove the author links.
As for internet archive - please use links like this : https://archive.org/details/bilgisayar-teriminde-algoritma as those others can move around.

**Pull request merged**
