### PR TITLE
Add Android book in Portuguese (BR)

### PR DESCRIPTION
**Pull request by rafaelsakurai**
## What does this PR do?
Improve Repo

### Why is this valuable (or not)
Free book about Android in portuguese (BR) that explain many components step by step, organised by chapter and that have exercises in the end of each chapter.

### How do we know it's really free?
I write the book.

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by PPaye** [comment]
I do not want to receive this information.

**Comment by eshellman** [comment]
Please take a look at the notations required for other leanpub books in our list. You have leanpub set up so an email address must be entered to read.

**Comment by rafaelsakurai** [comment]
Thank you. I add the details to access the book.

**Comment by eshellman** [comment]
Thanks!

**Pull request merged**
