### PR TITLE
Course

### PR DESCRIPTION
**Pull request by Suhanikashyap**
## What does this PR do?
Add resource(s) 

## For resources
YouTube videos , website courses ,
books , competitive programming platform can be used 

### Description
This pull request is created for resources for data structure and algorithms . This help people without any prior knowledge of coding learn these topic easily .

### Why is this valuable (or not)?
Yes , it is valuable 

### How do we know it's really free?
Because resources provided free of cost by different platform across the world are used.
 
### For book lists, is it a book? For course lists, is it a course? etc.
Book and course both 

If accepted please mention "Hacktoberfest accepted"

## Checklist:
- [✓ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ✓] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [✓ ] Include author(s) and platform where appropriate.
- [✓ ] Put lists in alphabetical order, correct spacing.
- [✓ ] Add needed indications (PDF, access notes, under construction).
- [ ✓] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Suhanikashyap** [comment]
This time it doesn't contain any link then why it is tagged spam .

**Comment by Suhanikashyap** [comment]
@sohansai

**Comment by sohansai** [comment]
Refer to the guidelines in docs/CONTRIBUTING.md for instructions on how to contribute. If you're new to GitHub or uncertain about the process, you can check this [link](https://docs.github.com/en/get-started)

**Comment by Suhanikashyap** [comment]
I had already gone through the contribution guidelines and then created this pull request . That is why inam asking because there is not in the pull request to be tagged ' spam '.

**Comment by Suhanikashyap** [comment]
@sohansai

**Comment by sohansai** [comment]
It seems there might be some confusion. 

Your pull request appears to contain previously committed changes and a large number of commits. The 462 commits you're attempting to merge have already been added to the repository. It's crucial to understand GitHub's contribution process. 

I've tagged it as spam, as duplicating commits could clutter the repository. 

I kindly recommend familiarizing yourself with GitHub practices before contributing further. The pull request has been tagged as spam to prevent unintended duplications.

**Comment by Suhanikashyap** [comment]
@eshellman please look into this matter

**Comment by sohansai** [comment]
It appears you forked the "cookie-cutters" branch from the "free-programming-books" repo and intend to merge it. Please consider forking the main branch from the repo and contributing from there.

**Comment by sohansai** [comment]
It appears you're trying to merge commits into EbookFoundation:cookie-cutter. Instead, merge them into the main branch.

**Pull request closed without merging**
