### PR TITLE
added Go Tour by golang.org

### PR DESCRIPTION
**Pull request by rkgade**
Added "A Tour of Go" by Golang.org for Go free-courses.

### CODE REVIEW

**Comment by rkgade** [comment]
Closing because Travis CI gave a "Check Alphabetical Order Warning"

**Comment by rkgade** [comment]
Pushed another commit with correct alphabetical order.

**Comment by eshellman** [comment]
Thanks for the contribution, And welcome to free-programming-books!

Do you think a relevant link should be added to the other 6 language-specific (de/en/ru/it/pl/es/vi) courses pages?

**Comment by eshellman** [comment]
(something about that page makes me want to learn go!)

**Comment by rkgade** [comment]
> added

@eshellman Actually, No. I don't see language translations for the website. When you say language specific, you state that the website and content should also be in that language, right? But I think https://tour.golang.org/welcome/1 is only in English.

**Comment by eshellman** [comment]
https://go-tour-fr.appspot.com/welcome/1 ?

**Comment by rkgade** [comment]
@eshellman I don't know if that's the original or not. the domain appspot is what is hitting me. Any way to confirm? If you think it helps, we can merge. Anything to read/understand helps, of course. I think their code is https://github.com/dupoxy/go-tour-fr .

**Comment by rkgade** [comment]
@eshellman My bad. Found the following. Available in these languages. Let me know what all you support. Shall update accordingly.

1. Brazilian Portuguese — Português do Brasil
2. Catalan — Català
3. Simplified Chinese — 中文（简体）
4. Traditional Chinese — 中文（繁體）
5. Czech — Česky
6. French — Français
7. German — Deutsch
8. Hebrew — עִבְרִית
9. Indonesian — Bahasa Indonesia
10. Italian — Italiano
11. Japanese — 日本語
12. Korean — 한국어
13. Romanian — Română
14. Russian - Русский
15. Spanish — Español
16. Thai - ภาษาไทย
17. Turkish - Türkçe
18. Ukrainian — Українська
19. Uzbek — Ўзбекча

**Pull request merged**
