### PR TITLE
Added more course links for databases

### PR DESCRIPTION
**Pull request by Swapnil123123**
## What does this PR do?
Add Resource(s) 

### Description 
Provided links to good free courses for (mySql) and (mongoDB). One can add many more databases in this category.

### Why is this valuable (or not)
Knowledge on databases is very essential since programming is not just about frontend. Rather, it is a combination of frontend, middleware and backend to make a functional application. 

### How do we know it's really free?
These courses are free and I have carefully selected these courses. One can even visit the links to find out.

### For book lists, is it a book?
No

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
There's also an SQL section. Maybe that belongs too? also check the organization of the books list, as having one system makes it easier for users

**Comment by Swapnil123123** [comment]
> There's also an SQL section. Maybe that belongs too? also check the organization of the books list, as having one system makes it easier for users

I see Sql section is present, but shouldn't there be a common section called database under which subcategories should contain names of databases & relevant links?

**Comment by Swapnil123123** [comment]
I can remove the sql section n place it under databases section instead

**Comment by eshellman** [comment]
Think about how people would look for these things. having all the db books together makes sense.

**Pull request closed without merging**
