### PR TITLE
Update free-programming-books-id.md

### PR DESCRIPTION
**Pull request by MuhamadAzizi**
Add one

## What does this PR do?
Add Resource(s)

### Description 
Add one line to PHP category

### Why is this valuable (or not)
Because this has any other languages that were translated

### How do we know it's really free?
It's from Github based project

### For book lists, is it a book?
No, it's a website

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by MuhamadAzizi** [comment]
update checks

**Comment by eshellman** [comment]
Good resource, but check travis-ci to see what the linter is failing for. (I have lots of Hacktoberfest submissions to process!)

**Comment by MuhamadAzizi** [comment]
> Good resource, but check travis-ci to see what the linter is failing for. (I have lots of Hacktoberfest submissions to process!)

I have fixed it

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
