### PR TITLE
 added link to Directory of free Javascript ebooks

### PR DESCRIPTION
**Pull request by luanribeiros**

### CODE REVIEW

**Comment by eshellman** [comment]
any reason to point at the github repo instead of http://jsbooks.revolunet.com ? Also, please add it in alphabetical order to satisfy the linter.

**Comment by luanribeiros** [comment]
Sorry, correct the link and I put it in alphabetical order now. Thank you.

**Comment by luanribeiros** [comment]
correct the problem. What error this time?

**Comment by eshellman** [comment]
Sorry I didn't look at this closer.
This site is already listed in the meta-lists section, where it belongs. (pointing at the github repo).
for future reference, the linter complains when you point at a website and include only '/' after the hostname. Use http://jsbooks.revolunet.com instead of http://jsbooks.revolunet.com/

Will leave the PR open so you can update the link. Thanks for your forbearance.

**Comment by luanribeiros** [comment]
Ok. Thank you!

**Comment by luanribeiros** [comment]
Sorry, correct and delete the link.

**Comment by eshellman** [comment]
thanks!

**Pull request merged**
