### PR TITLE
Added howto file in gujarati language

### PR DESCRIPTION
**Pull request by AshishSharma1203**
## What does this PR do?
Improve repo by adding more languages support

### Why is this valuable (or not)?
It adds missing gujarati language 
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by AshishSharma1203** [comment]
> We won't merge this until we have resources in Gujarati

I have added resources in the Gujarati Language . Please verify it .

**Comment by AshishSharma1203** [comment]
> We won't merge this until we have resources in Gujarati

Any update regarding this ??

**Comment by AshishSharma1203** [comment]
> This Pull Request has been automatically marked as stale because it has not had recent activity during last 60 days 😴
> 
> It will be closed in 30 days if no further activity occurs. To unstale this PR, draft it, remove stale label, comment with a detailed explanation or push more commits.
> 
> There can be many reasons why some specific PR has no activity. The most probable cause is lack of time, not lack of interest.
> 
> Thank you for your patience ❤️

@eshellman can you verify this PR ??

**Review by eshellman — CHANGES_REQUESTED** [review]
Thanks for returning to this.

**Comment by AshishSharma1203** [comment]
> Thanks for returning to this.

All set now. please check it now.

**Comment by eshellman** [comment]
Be sure to check the free-programming-books-lint output for linter errors. Alphabetical order and spacing are the most common problems.

**Pull request closed without merging**
