### PR TITLE
Add Linux journey to free-programming-interactive-tutorials-en.md

### PR DESCRIPTION
**Pull request by p1utoze**
## What does this PR do?
Add resource

### Description
This website is a free, fun, and easy-to-learn Linux tutorial teaching various commands with short quizzes and exercises after each sub-topic. 

### Why is this valuable (or not)?
It is a comprehensive and progressive tutorial to learn about Linux concepts and terminal commands.

### How do we know it's really free?
It's an open-source project by Cindy Quach 
## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
great addition! maybe fits better under Operating systems?
It's usually not helpful to add a category for a single resource.

**Comment by p1utoze** [comment]
> great addition! maybe fits better under Operating systems? It's usually not helpful to add a category for a single resource.

 I felt the same but the first thing a user searches or navigates for Linux would find it convenient.

**Comment by p1utoze** [comment]
Hello! I made the changes you requested.

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by p1utoze** [comment]
Glad to contribute! Can you add   `hacktoberfest-accepted` label to this PR?

**Pull request merged**
