### PR TITLE
Update free-programming-books.md

### PR DESCRIPTION
**Pull request by miwojc**
Added Django Girls tutorial. Since it's not an interactive tutorial i have added it to books section.

### CODE REVIEW

**Comment by eshellman** [comment]
I agree that it belongs in the book list. Could you put it in the list in alphabetic position? Thanks!

**Comment by eshellman** [comment]
I see that some of the translations have been completed. Would love to see them added to the appropriate lists as well- feel free to include in this PR or create an issue to ask for assistance.

**Comment by miwojc** [comment]
moved the Django Girls Tutorial to top of the list now. sorry missed that
step in the fist pull request. Let me know if you can see that pull
request. i am new on github :) Thanks...

**Comment by miwojc** [comment]
i have crated issue for adding translations of this Tutorial. Wasn't sure
how to set a label, like "easy" or "hacktoberfest". Thanks...

**Comment by eshellman** [comment]
Thanks! We always enjoy welcoming a new F-P-B contributor to GitHub.

**Pull request merged**
