### PR TITLE
Added Reading Materials and Videos of Python for Everybody - Coursera

### PR DESCRIPTION
**Pull request by BasilVictor**
# Added Open Source Reading Materials and Videos of Python for Everybody - Coursera
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource

### Description 
This is the open source version offered by the same instructor (Charles R. Severance) of the course which is a paid one in Coursera. The link contains all the reading materials and its related youtube videos

### Why is this valuable (or not)?
It is a great course for someone trying to get started with Python.

### How do we know it's really free?
It is a `Copyright Creative Commons Attribution 3.0` website.

### For book lists, is it a book? For course lists, is it a course? etc.
It is a course.

### Screenshot of the website
image

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
Do we need to remove the coursera version, if its no longer free?

**Comment by BasilVictor** [comment]
Yes it may be removed, as this seems to be more user friendly as there is no need to create any account or enroll as well.

**Comment by eshellman** [comment]
could you remove it then?

**Comment by BasilVictor** [comment]
done!

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
