### PR TITLE
Added StackBlitz under Angular in free-programming-playgrounds page

### PR DESCRIPTION
**Pull request by AnkitSharma-007**
## What does this PR do?
Add Resource(s) 

### Why is this valuable (or not)

StackBlitz is a free online code editor for Angular. This is not included in the existing link.

### CODE REVIEW

**Comment by eshellman** [comment]
I'm not sure how we should deal with the other app flavors supported by StackBlitz. I guess we'll deal with it later. Welcome to free-programming-books!

**Comment by eshellman** [comment]
whoops - failed to notice the broken build

**Comment by AnkitSharma-007** [comment]
Thanks for accepting the PR. Maybe we can add StackBlitz under other frameworks also.

**Comment by eshellman** [comment]
we try to avoid having duplicates. If there are different links for each framework, that avoids the problem.

**Comment by AnkitSharma-007** [comment]
Yes, we have separate URL for StackBlitz playground of Angular, React, Ionic, Typescript, RxJs and Svelte. Shall i raise another PR to include these links?

**Comment by eshellman** [comment]
yes please!

**Pull request merged**
