### PR TITLE
Create free-courses-fr.md

### PR DESCRIPTION
**Pull request by Drumor**
Create french free courses page

## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [ ] Not a duplicate
- [ ] Included author(s) if appropriate
- [ ] Lists are in alphabetical order
- [ ] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by eshellman** [comment]
There are several items in the French books page with "cours" in the title - could you check to see if they should be moved to this page? also, we'll need the addition of a link from the README page.

**Comment by Drumor** [comment]
I agree with you, I deleted my additional file and add a new line in free books page. Thx!

**Comment by Drumor** [comment]
I also fixed the build issue in another PR #4811

**Comment by eshellman** [comment]
Since it requires a registration to use, we would require the addition of an access note. (it belongs on a courses page, though, I think French deserves a course, page, don't you?)

**Comment by eshellman** [comment]
It's a long access not, but it works. Merging this - I encourage you to check the out the books on the French list to see if they'd better fit as courses and we can create a french courses page. Or create an issue to ask for others to help.

**Comment by Drumor** [comment]
I'll have a complete look  to the list of books to see for a course page, that should be a good thing! Thank you for the merge.

**Pull request merged**
