### PR TITLE
Please add a new Python Book

### PR DESCRIPTION
**Pull request by H3li0**
I found this new book just released in January 2018.
It is a compilation from StackOverflow documentation and is freely available.

Thanks.

### CODE REVIEW

**Comment by ShipsWithCannons** [comment]
There's a leading space before the `http` which shouldn't be there.

**Comment by eshellman** [comment]
And the lists need to be in alphabetical order. Gee I wish we had a robot that would help correct these things.

**Comment by eshellman** [comment]
Thanks @H3li0 for the submission, and for persevering. Thanks @ShipsWithCannons for assistance.

**Comment by eshellman** [comment]
pushed the wrong button!

**Pull request merged**
