### PR TITLE
Open University courses : Most popular in Digital & Computing

### PR DESCRIPTION
**Pull request by rahul9852-dot**
## What does this PR do?
This PR introduces a new resource that covers the latest developments in digital and computing technology.

### Description
This is a freely accessible course generously provided by The Open University.

### Why is this valuable (or not)?
This resource holds significant value as it offers a cost-free educational opportunity through The Open University, enabling individuals to access quality learning materials and expand their knowledge in a convenient and affordable manner.

### For book lists, is it a book? For course lists, is it a course? etc.
It is course.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
thanks for working on this.

I think we already have categories for all of these courses, it's not helpful to invent new ones.

It's common for courses to require registration for things like grading an personalization, but not for the content itself. When I looked at a course, none of the content required registration, so I would not use the "requires email" annotation.

**Comment by eshellman** [comment]
These courses have authors. They should be crediited.

**Comment by rahul9852-dot** [comment]
@eshellman I agree that categories are already there but are you sure the entire course which doesn't need email for registration .
If not can you check the [link](https://www.open.edu/openlearn/science-maths-technology/introduction-cyber-security-stay-safe-online/content-section-overview?active-tab=description-tab) which i have mentioned here.

**Comment by eshellman** [comment]
yes

**Comment by rahul9852-dot** [comment]
Then what should i do. Close my PR

**Comment by eshellman** [comment]
add commits to your branch

**Comment by rahul9852-dot** [comment]
Hi @eshellman could you tell me the category name so that i put all the links there.

**Comment by eshellman** [comment]
Perhaps you (or others) might review the categories that we already have.

**Pull request closed without merging**
