### PR TITLE
Added a course on Generative AI in Hindi

### PR DESCRIPTION
**Pull request by Devansh0702**
## What does this PR do?
Add resource(s)

### Description
Added a course in hindi on Generative AI

### Why is this valuable (or not)?
Yes, it is valuable.

### How do we know it's really free?
It is available on YouTube.

### For book lists, is it a book? For course lists, is it a course? etc.
It is a course

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Devansh0702** [comment]
@sohansai please review this PR

**Comment by eshellman** [comment]
there is already an Artificial Intelligence category

**Comment by Devansh0702** [comment]
> there is already an Artificial Intelligence category

The category is mentioned in the index but there was no category with links defined for Artificial Intelligence in the Hindi file. I have reused the category name to create one.

**Comment by eshellman** [comment]
Great, now move the section to after Arduino to keep alphabetical order

**Comment by Devansh0702** [comment]
> Great, now move the section to after Arduino to keep alphabetical order

@eshellman I have made this change. Kindly review the PR

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
