### PR TITLE
Added playground definition

### PR DESCRIPTION
**Pull request by Suman373**
Added a small definition about programming/coding playgrounds for making it understandable to beginners

## What does this PR do?
Add Info

### Why is this valuable (or not)?
It is valuable because it explains what coding playground is in few lines.
## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by CleanMachine1** [comment]
This seems unnecessary to me since a "programming playground"  to me says "mess about with a programming language online with a repl or similar" and also out of place, since the rest of the types of resources do not have a description. 

I think if this were to be implemented into the README, it should be applied to all of the other types of resources, however this would be cluttering and make the README less succinct, which make it seem just like fluff.

Either way, this is way to long, it should be a brief description.

**Comment by Suman373** [comment]
> This seems unnecessary to me since a "programming playground" to me says "mess about with a programming language online with a repl or similar" and also out of place, since the rest of the types of resources do not have a description.
> 
> I think if this were to be implemented into the README, it should be applied to all of the other types of resources, however this would be cluttering and make the README less succinct, which make it seem just like fluff.
> 
> Either way, this is way to long, it should be a brief description.

> Should I shorten the definition instead?

**Comment by Suman373** [comment]
> That would be a good start but I'm still weary with adding this.

> Alright! No problem, I'll close the pr. Lmk if I could fix any other issues !

**Comment by CleanMachine1** [comment]
Lets get the opinion of others before closing, since I am just one of many reviewers :)

**Comment by Suman373** [comment]
> Sure. :))

**Comment by davorpa** [comment]
Related with #6107

**Comment by eshellman** [comment]
I agree this category would benefit from some explanation. The proposed explanation is perhaps too specific - there are some resources that don't quite fit the explanation. In particular, there are some games that would fit well here. The shorter the better. Maybe "try it!" is enough?

**Comment by Suman373** [comment]
> Yeah, I think shortening the explanation and adding "try it " would seem better!

**Comment by Suman373** [comment]
> That could be done as well.

**Comment by davorpa** [comment]
Closed in preference of #6817

**Pull request closed without merging**
