### PR TITLE
Create free-programming-interactive-cheat sheet-ja.md

### PR DESCRIPTION
**Pull request by Aaryan-Jordan**
Cypress commands: Cheat Sheet

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by Aaryan-Jordan** [comment]
I have created/added the required cheat sheet in more section i.e Cypress commands: Cheat Sheet

**Comment by Aaryan-Jordan** [comment]
I have created/added the required cheat sheet in more section i.e Jasmine Cheat Sheet

**Review by shrn01 — CHANGES_REQUESTED** [review]
Please try to add the link to the resource in the proper file. Adding the resource directly to the repo is not supported

**Comment by eshellman** [comment]
The repo does not host books. Please read docs/CONTRIBUTING.md guidelines. If the book is free licensed, consider depositing in archive.org or unglue.it

**Pull request closed without merging**
