### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by yashpatel08**
I add these books which helpfull in DSA and SQL
if it is helpful then please tell me ASAP so i can upload more books @EbookFoundation
@radar

### CODE REVIEW

**Comment by radar** [comment]
Why am I getting tagged on these PRs?

**Comment by yashpatel08** [comment]
because i can know this useful or not





Patel Yash J.
*"Happiness is not a destination it is a way of life "*

**Comment by radar** [comment]
I am not in charge of this repository. You’ve tagged someone random. Please stop doing this.

**Comment by yashpatel08** [comment]
Thank you for the clarification.

Patel Yash J.
*"Happiness is not a destination it is a way of life "*

**Comment by eshellman** [comment]
The repo does not host books. Please read docs/CONTRIBUTING.md guidelines. If the book is free licensed, consider depositing in archive.org or unglue.it

**Pull request closed without merging**
