### PR TITLE
Add some free ebooks and courses about bash in French

### PR DESCRIPTION
**Pull request by idrissneumann**
## What does this PR do?
Add resource(s)

### Description

Shell and bash courses in French

### Why is this valuable (or not)?

There is only one guide in the French section and those links remains the most complete free courses available in French since several years.

### How do we know it's really free?

Because licences (GPL and Creative Commons) says so and mostly because I'm one of the writers.

### For book lists, is it a book? For course lists, is it a course? etc.

Yeah I consider the first link as book because:
* you can download offline and printable PDF or epub version on each of thoses
* it is a real book of almost 100 pages and is very complete

The two other links are complementary smaller courses and exercices (but you can also download a PDF or epub version)

Of course we can debate on this.

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [X] Search for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Comment by idrissneumann** [comment]
> Thanks, and welcome to free-programming-books!

Thanks and thanks for this amazing work!

**Comment by Jeverson1Aparecido** [comment]
Stop sending me imail pls

Em dom, 29 de ago de 2021 02:01, Idriss Neumann ***@***.***>
escreveu:

**Comment by MarcondesOliveira** [comment]
I don't want to receive these emails anymore.

**Pull request merged**
