### PR TITLE
Add OpenMP reference card

### PR DESCRIPTION
**Pull request by knguyen100000010**
## What does this PR do?
Add resource(s) 

### Description

Add OpenMP cheat sheet.

### Why is this valuable (or not)?

This cheat sheet is very helpful for developers working with OpenMP frameworks.

### How do we know it's really free?

It's freely accessible to everyone.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
It's usually not helpful to add a category for a single resource. Try to find another category, or see if there are other books in our lists that would fit into your category.
Put it with C/C++

**Comment by knguyen100000010** [comment]
Will do after this https://github.com/EbookFoundation/free-programming-books/pull/7729 merged.

**Comment by knguyen100000010** [comment]
Updated.

**Comment by eshellman** [comment]
please resolve conflicts.

**Comment by knguyen100000010** [comment]
Resolved conflict.

**Pull request merged**
