### PR TITLE
Create free-courses-ta.md

### PR DESCRIPTION
**Pull request by GH05T-HUNTER5**
Create free-courses-ta.md

### CODE REVIEW

**Comment by GH05T-HUNTER5** [comment]
We have added tamil but tamil file is not available

File Name ( free-courses-ta.md )

**Comment by davorpa** [comment]
### PRO TIP:

Please avoid post incremental PRs. It turns it review into a headache process.

Instead of this, push changes into the same branch where PR was opened initially: #7001 and [`patch-9`](https://github.com/GH05T-HUNTER5/free-programming-books/tree/patch-9) as branch

**Comment by davorpa** [comment]
### PRO TIP:

Please avoid post incremental PRs. It turns it review into a headache process.

Instead of this, push changes into the same branch where PR was opened initially: #7001 and [`patch-9`](https://github.com/GH05T-HUNTER5/free-programming-books/tree/patch-9) as branch

**Comment by davorpa** [comment]
### PRO TIP:

Please avoid post incremental PRs. It turns it review into a headache process.

Instead of this, push changes into the same branch where PR was opened initially: #7001 and [`patch-9`](https://github.com/GH05T-HUNTER5/free-programming-books/tree/patch-9) as branch

**Comment by davorpa** [comment]
### PRO TIP:

Please avoid post incremental PRs. It turns it review into a headache process.

Instead of this, push changes into the same branch where PR was opened initially: #7001 and [`patch-9`](https://github.com/GH05T-HUNTER5/free-programming-books/tree/patch-9) as branch

**Comment by davorpa** [comment]
### PRO TIP:

Please avoid post incremental PRs. It turns it review into a headache process.

Instead of this, push changes into the same branch where PR was opened initially: #7001 and [`patch-9`](https://github.com/GH05T-HUNTER5/free-programming-books/tree/patch-9) as branch

**Comment by davorpa** [comment]
Duplicate of #7001

**Pull request closed without merging**
