### PR TITLE
Added a new HTML CSS book PDF english

### PR DESCRIPTION
**Pull request by pranav7955**
## Hacktoberfest notes:

- due to volume of submissions, we may not be able to review PRs that do not pass tests and do not have informative titles.
- please read our [contributing guidelines](/CONTRIBUTING.md)
- be sure to check the output of Travis-CI for linter errors
- if this is your first open source contribution, make sure it's not your last!

## What does this PR do?
Add Resource(s) | Remove Resource(s) | Add info | Improve Repo

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by SethiPandi** [comment]
Wouldn't this belong under the HTML & CSS section?

You've out it in the table of contents.

**Comment by pranav7955** [comment]
> Wouldn't this belong under the HTML & CSS section?
> 
> You've put it in the table of contents.

I have generated a new pull request for the changes :)

**Comment by SethiPandi** [comment]
Awesome, I see it here! https://github.com/EbookFoundation/free-programming-books/pull/4294  
Perhaps close this PR ahead of time then since it's now a duplicate.

**Comment by pranav7955** [comment]
> Awesome, I see it here! #4294
> Perhaps close this PR ahead of time then since it's now a duplicate.

Closed all the Invalid PR's, Waiting for the new ones to be approved and merged :) #4296 #4295 #4294 #4291

**Pull request closed without merging**
