### PR TITLE
Fix order of elements in ID library

### PR DESCRIPTION
**Pull request by marcelbrode**
## What does this PR do?
Improve repo

### Description
Fix wrong arrangement for ID

### Why is this valuable (or not)?
E.g. There were multiple bullet points for React, which should have been merged

### How do we know it's really free?
-

### For book lists, is it a book? For course lists, is it a course? etc.
-

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
This is the sort of work that can easily run into conflicts when there are a lot of other contributions, as we expect in October. don't hesitate to break up the effort into pieces.

**Comment by marcelbrode** [comment]
You mean into multiple MRs?

**Comment by eshellman** [comment]
multiple PRs are fine

**Comment by marcelbrode** [comment]
Guess that makes sense. I'll try that!

**Pull request merged**
