### PR TITLE
Update free-courses-en.md

### PR DESCRIPTION
**Pull request by chessboards**
Adds a course for Javascript

## What does this PR do?
Add Resource(s) 

## For resources
Javascript
### Why is this valuable (or not)
It's a very quality course, and is updated frequently to meet the latest Javascript specifications.

### How do we know it's really free?
It's open to contribution, and is available to teach new developers how to program and learn how the web works at no cost.

### For book lists, is it a book?
It's a course

### Checklist:
- [x] Not a duplicate
- [x] Included author(s) if appropriate
- [x] Lists are in alphabetical order
- [x] Needed indications added (PDF, access notes, under construction)

### CODE REVIEW

**Comment by chessboards** [comment]
check_urls=free-courses-en.md

**Comment by eshellman** [comment]
fix the linter errors

**Comment by chessboards** [comment]
The linter seems to have difficulty when presenting with symbols like `:`

**Comment by eshellman** [comment]
the linter enforces unicode collation

**Pull request closed without merging**
