### PR TITLE
Update free-programming-books-ru.md

### PR DESCRIPTION
**Pull request by alexeykovyazin**
Russian resources for FirebirdSQL

## What does this PR do?
Add resource(s) | Remove resource(s) | Add info | Improve repo

## Checklist:
- [ ] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [ ] Search for duplicates.
- [ ] Include author(s) and platform where appropriate.
- [ ] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by eshellman** [comment]
Be sure to check the output of Travis-CI for linter errors. Alphabetical order and spacing are the most common problems.

**Comment by joe192** [comment]
diff --git a/books/free-programming-books-ru.md b/books/free-programming-books-ru.md
index 1c0fa85026c..ed27a54f8a9 100644
--- a/books/free-programming-books-ru.md
+++ b/books/free-programming-books-ru.md
@@ -63,6 +63,7 @@
 * [Smalltalk](#smalltalk)
 * [SQL](#sql)
   * [PostgreSQL](#postgresql)
+  * [FirebirdSQL](#firebirdsql)
 * [Swift](#swift)
 * [TypeScript](#typescript)
 * [Unix](#unix)
@@ -518,6 +519,12 @@
 * [Работа с PostgreSQL - настройка и масштабирование](http://postgresql.leopard.in.ua) - А. Ю. Васильев
 * [PostgreSQL для начинающих](https://postgrespro.ru/education/books/introbook) (PDF)
 
+#### FirebirdSQL
+* [Краткое руководство по миграции на Firebird 4.0] (https://github.com/sim1984/fbmigrgd40/releases/download/1.0/doc.rus.pdf)(PDF)
+* [Руководство по языку Firebird 4.0] (https://www.ibase.ru/files/firebird/Firebird_4_0_Language_Reference_RUS.pdf?v=20210523) (PDF)
+* [Руководство по языку Firebird 3.0] (https://www.ibase.ru/files/firebird/Firebird_3_0_Language_Reference_RUS.pdf) (PDF)
+* [Руководство по аппаратному обеспечению для Firebird] (https://www.ibase.ru/files/firebird/Firebird_Hardware_Guide_2015_rus.pdf) (PDF)
+* [Руководство по написанию UDR на Pascal] (https://github.com/sim1984/udr-book/releases/download/1/udr.pdf)(PDF)
 
 ### Swift

**Review by davorpa — CHANGES_REQUESTED** [review]
I just propose following inline changes to:

- [ ] Add book creators
- [ ] Url cleaning: remove marketing/tracking parameters
- [ ] Fix markdown hyperlink syntax.
- [ ] Fix SSL `NET::ERR_CERT_DATE_INVALID` on ibase.ru resources. `https -> http`
- [ ] Fix Travis linting errors (https://app.travis-ci.com/github/EbookFoundation/free-programming-books/builds/226979159#L219-L224)
   ```http
   $ fpb-lint ./books/
   /home/travis/build/EbookFoundation/free-programming-books/books/free-programming-books-ru.md
      65:3-66:32  warning  Alphabetical ordering: swap l.66 and l.65                              alphabetize-lists  remark-lint
    517:1-520:86  warning  Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2  remark-lint
    522:1-522:17  warning  Incorrect number of blank lines between heading and section            blank-lines-1-0-2  remark-lint
  523:1-527:114  warning  Alphabetical ordering: swap l.525 and l.524                            alphabetize-lists  remark-lint
  523:1-527:114  warning  Alphabetical ordering: swap l.526 and l.525                            alphabetize-lists  remark-lint
  523:1-527:114  warning  Incorrect number of blank lines between last section and next heading  blank-lines-1-0-2  remark-lint
   ```

Please @alexeykovyazin merge them manualy and check again

**Review by davorpa — APPROVED** [review]
A detached review is treated at #5538

/labelthis: resolved, stale
/lockthis: resolved

**Pull request closed without merging**
