### PR TITLE
ci(sync-labels): Create `sync-labels.yml` workflow

### PR DESCRIPTION
**Pull request by davorpa**
## What does this PR do?
Improve repo

### Description

- Using a wide used [`crazy-max/ghaction-github-labeler`](https://github.com/crazy-max/ghaction-github-labeler) action
- Save current repository labels in a file
- Monitor this file to auto import labels to the repo.
- Having a manual way to run it with granularity over input parameters (test and deletions)
- If a PR is open test CRUD, if merged... do modifications but without deleting any label (the least destructive action)

#### Why this?

Allows to collaborators add manage the repo labels having the last desision whom have write permissions.

E.g. add the labels of new locale (see https://github.com/EbookFoundation/free-programming-books/issues/7024#issuecomment-1238004325)

Dry-run over this repository: https://github.com/EbookFoundation/free-programming-books/runs/8230716302?check_suite_focus=true#step:3:218

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
I don't understand the problem this is trying to address.

**Comment by davorpa** [comment]
> I don't understand the problem this is trying to address.

Sorry if I can't explain it better in english

See `Why this?` section. One more...

- Have same repo labels in forks than in upstream repo

**Comment by eshellman** [comment]
this appears to have created  4 new checks. This will tend to obscure the checks we want people to pay attention to. It's a feature that adds complexity and maintenance burden for the benefit of only a small number of maintainers. I think a better course would be to reduce the number of labels to something that can more easily managed by hand. The fact that you feel a need for automation to manage the labels suggests that there are too many labels!!

**Comment by davorpa** [comment]
I understand :+1: . Let's keep it simple!

It was only an idea to start to triage resources using labels.

The reason I added the locale labels in the past was for classifying resources, and if someone want to susbcribe to this files changes, e.g. a mantainer in charge of review PRs of this country/language. Obviously, the second part is not developed yet (extract locale slug from files and do the label triage https://github.com/EbookFoundation/free-programming-books/issues/7024#issuecomment-1224403600).

But maybe https://github.com/EbookFoundation/free-programming-books/issues/7024#issuecomment-1238445280 would be a better aproach to group resources by locale and mantain files low sizing. A big breaking change for us that needs coordination!!

> this appears to have created 4 new checks...

Acording to `on` events these checks only appears if any of both files (`labels.yml`, `sync-labels.yml`) change!

I have this other workflow if only one job (or whatever you call "check") and 4 steps if is needed in a future.

https://github.com/davorpa/testing-github-actions/commit/4722aba24c9f9164a69f43dcb423e6a1ed591952#diff-a877ed9f27d115d95934fd904f2475dcec6ce4125da686dd5b3c75a696fff1c6R4-R10

Some workflow runs at:
- https://github.com/davorpa/testing-github-actions/actions/runs/3012994861 for sync labels
- triggered by commit https://github.com/davorpa/testing-github-actions/commit/4578cbb8134f28dd391dc38718196cefed41e915 which autoadd a label needed by [my stale workflow](https://github.com/davorpa/testing-github-actions/actions/runs/3012994862) 
- More at https://github.com/davorpa/testing-github-actions/actions. 

Feel free to take a look.

Said that.... next workflow: `auto-conflicts` :rocket:

**Pull request closed without merging**
