### PR TITLE
“The API” by Sergey Konstantinov [English version] added

### PR DESCRIPTION
**Pull request by twirl**
## What does this PR do?
Add resource

### Description
“The API” by Sergey Konstantinov

### Why is this valuable (or not)?
600 stars on GitHub.
Also, the Russian version of the book is already added.

### How do we know it's really free?
I'm the author, I'm telling you ;)
Also, see [LICENCE.md](https://github.com/twirl/The-API-Book/blob/gh-pages/LICENSE.md) in the book's repository

### For book lists, is it a book? For course lists, is it a course? etc.
It is a book

## Checklist:
- [✅] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [✅] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [✅] Include author(s) and platform where appropriate.
- [✅] Put lists in alphabetical order, correct spacing.
- [✅] Add needed indications (PDF, access notes, under construction).
- [✅] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
not sure why the linkchecker script fails maybe @Thenlie can take a look - the last commit was a version pump

**Comment by Thenlie** [comment]
> not sure why the linkchecker script fails maybe @Thenlie can take a look - the last commit was a version pump

The problem is with my last PR, when creating the output name I had incorrectly assumed all file names would end in `.yml`. In this case, the file ends in `.md` so the regex I made failed. A fix PR will be up momentarily.

**Comment by Thenlie** [comment]
The lint check should pass after #11051 is merged. Sorry about that!

**Comment by eshellman** [comment]
@twirl it looks like you need to update your branch from main to pick up the corrected actions. Let us know if you have trouble doing that.

**Comment by twirl** [comment]
@eshellman done, all checks passed

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!
Thanks for making you book free! If it has an Open License, consider adding it to Unglue.it and Archive.org.

**Pull request closed without merging**
