### PR TITLE
Add "Holm School" - How to be a Computer Scientist for Hamiltons a Month

### PR DESCRIPTION
**Pull request by ryheimat**
## What does this PR do?
Add resource Holm School (You Might Learn Something), my public domain ebook about learning computer science cheaply.

### Description
How to use Open Educational Resources (like this very repo) to learn to program for free, and what to do with the money you save. My experience and takeaways using this repo to become a programmer.

### Why is this valuable (or not)?
Describes techniques for minimizing debt while still young and studying CS.

### How do we know it's really free?
Public Domain

### For book lists, is it a book? For course lists, is it a course? etc.
It's a book

## Checklist:
- [X] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md)
- [X] Search for duplicates.
- [X] Include author(s) and platform where appropriate.
- [X] Put lists in alphabetical order, correct spacing.
- [X] Add needed indications (PDF, access notes, under construction)

## Followup

- Check the output of Travis-CI for linter errors!

### CODE REVIEW

**Comment by melano-21** [comment]
Please the rate at which you are send me emails is too much. Can you kindly
reduce it. Or better still remove me frim the subscribers.

On 5 Jun 2021 23:06, "ryheimat" ***@***.***> wrote:

What does this PR do?

Add resource Holm School (You Might Learn Something), my public domain
ebook about learning computer science cheaply.
For resources Description

How to use Open Educational Resources (like this very repo) to learn to
program for free, and what to do with the money you save. My experience and
takeaways using this repo to become a programmer.
Why is this valuable (or not)?

Describes techniques for minimizing debt while still young.
How do we know it's really free?

Public Domain
For book lists, is it a book? For course lists, is it a course? etc.

It's a book
Checklist:

   - Read our contributing guidelines
   <https://github.com/EbookFoundation/free-programming-books/blob/master/CONTRIBUTING.md>
   - Search for duplicates.
   - Include author(s) and platform where appropriate.
   - Put lists in alphabetical order, correct spacing.
   - Add needed indications (PDF, access notes, under construction)

Followup

   - Check the output of Travis-CI for linter errors!

------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/EbookFoundation/free-programming-books/pull/5409
Commit Summary

   - My book: Holm School - How to be a computer scientist for Hamiltons a
   Month (public domain)

File Changes

   - *M* books/free-programming-books.md
   <https://github.com/EbookFoundation/free-programming-books/pull/5409/files#diff-67587b9175aab6f3aa01bef2b9f39eae48453c3c1297a90c391b9dcc2048bb9c>
   (1)

Patch Links:

   -
   https://github.com/EbookFoundation/free-programming-books/pull/5409.patch
   -
   https://github.com/EbookFoundation/free-programming-books/pull/5409.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/EbookFoundation/free-programming-books/pull/5409>, or
unsubscribe

**Comment by eshellman** [comment]
Thanks for making your book free! As it has an Open License, consider adding it to Unglue.it and Archive.org.
Consider using "Releases" for your generated epub - the epub link is broken in some places.
Welcome to free-programming-books!

**Comment by ryheimat** [comment]
Whoops, thanks for the dead link heads up and the Releases tip. I have added to Archive.org, will look into Unglue.it.

Thank you for your work in making OER a success! Take care, eshellman, best of luck.

**Comment by joe192** [comment]
diff --git a/books/free-programming-books.md b/books/free-programming-books.md
index 8fb1cdc3881..e5fc8662b04 100644
--- a/books/free-programming-books.md
+++ b/books/free-programming-books.md
@@ -679,6 +679,7 @@
 * [Hacknot: Essays on Software Development](http://www.lulu.com/shop/ed-johnson/hacknot-essays-on-software-development/ebook/product-17544641.html) - Ed Johnson
 * [Hello SDL](https://lazyfoo.net/tutorials/SDL) - Lazy Foo' Productions
 * [High-Performance Scientific Computing](https://andreask.cs.illinois.edu/Teaching/HPCFall2012) (class lectures and slides)
+* [Holm School (You Might Learn Something) - How to Teach Yourself To Be A Computer Scientist for Hamiltons a Month](https://ryheimat.github.io/holm-school) - Ryhen Holm
 * [HoloLens Succinctly](https://www.syncfusion.com/ebooks/hololens_succinctly) - Lars Klint
 * [How Computers Work](http://www.fastchip.net/howcomputerswork/p1.html) - R. Young
 * [How to Become a Programmer](http://softwarebyrob.wpengine.netdna-cdn.com/assets/Software_by_Rob%20_How_to_Become_a%20_Programmer_1.0.pdf) (PDF)

**Pull request merged**
