### PR TITLE
Added License Notes to 3 Books

### PR DESCRIPTION
**Pull request by MananJain-IITJ**
## What does this PR do?
Add info 

### Description
Add License Notes to the following books 
First 2 books are in books/free-programming-books-subjects.md
Last book is in books/free-programming-books-langs.md

1. [Clever Algorithms Nature-Inspired Programming Recipes](https://bjpcjp.github.io/pdfs/ruby/Clever-Algorithms.pdf) - Jason Brownlee (PDF)  

**License Line found on Page 2 of the PDF.**

"This work is licensed under a Creative Commons
Attribution-Noncommercial-Share Alike 2.5 Australia License.
The full terms of the license are located online at
http://creativecommons.org/licenses/by-nc-sa/2.5/au/legalcode. 
Added (CC BY-NC-SA) "

2. [Digital Circuit Projects: An Overview of Digital Circuits Through Implementing Integrated Circuits - Second Edition](https://cupola.gettysburg.edu/cgi/viewcontent.cgi?article=1000&context=oer) - Charles W. Kann (PDF)

**License Line found on Page 3 and 5 of the PDF.**

"Creative Commons License
This work is licensed under a Creative Commons Attribution 4.0 License."
Added (CC BY)

3. [Modern C++ Tutorial: C++11/14/17/20 On the Fly](https://www.changkun.de/modern-cpp/pdf/modern-cpp-tutorial-en-us.pdf) - Changkun Ou (PDF)

**License Line found on Page 1 of the PDF.**

"License
This work was written by Ou Changkun and licensed under a Creative Commons
Attribution-NonCommercial-NoDerivatives 4.0 International License.
https://creativecommons.org/licenses/by-nc-nd/4.0/"

Added (CC BY-NC-ND)

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [ ] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [ ] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by MananJain-IITJ** [comment]
This is PR For the Issue #11355 .

I had a small doubt will this count for the Hacktober Fest ? Its my first time doing open source so I have no idea how this works .

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!
Perfect start for this new feature!

**Comment by AbhinandanRoy7** [comment]
@MananJain-IITJ Could you please tell me how you found the licenses for the books? Please contact me at my email: abhinandancr7@gmail.com.

**Comment by MananJain-IITJ** [comment]
@AbhinandanRoy7 Below are the steps you can follow to find the licenses.

1. Go the book url or website url 
2. Press ctrl+F (Windows) or cmd+F (Mac) and type license [Note Some Books might not contain licenses ignore them]
3. You would find license page in the pdf like below.  image
4. Search on the internet for Creative Commons Attribution-Noncommercial-Share Alike 2.5 Australia License.
5. The first link on the internet would be from creative commons website . image
6. Select the CC BY-NC-SA part not the version number and edit the book in the code respectively and make a PR respectively.
 
If you face any issues in the steps you can comment here. Also some suggestions for the books/sites on which you can add Licenses to.
 
Present in file ` /books/free-programming-books-langs.md`
- [Java 23 - Key Concepts in Brief](https://petrucci.dev/java23.html) - Sergio Petrucci (PDF)
- [Java Programming for Kids](https://yfain.github.io/Java4Kids/) - Yakov Fain

**Comment by AbhinandanRoy7** [comment]
Thanks for your help
I'll try to do it
However I have a doubt,since they have accepted your pr, did they merge it?
And did you get your hacktoberfest one pr?

**Comment by eshellman** [comment]
that's one way to do it. good suggestion

**Comment by kamranzafar4343** [comment]
Thanks for sharing!

**Pull request merged**
