### PR TITLE
Updated free-courses-en.md (REVISED)

### PR DESCRIPTION
**Pull request by emSoumik**
## What does this PR do?
Add resource(s)

### Description
Added two new Java courses in free-courses-en.md

### Why is this valuable (or not)?
It's a free course on Java and will also help with DSA.

### How do we know it's really free?
It's a free course by Kunal Khushwa, it's available on youtube.

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Review by emSoumik — COMMENTED** [review]
Added resource platform

**Review by emSoumik — COMMENTED** [review]
Arrange the line 701 and 703 in alphabetical order. Also fixed the Incorrect number of blank lines between last section and next heading

**Comment by eshellman** [comment]
For youtube, we prefer "playlist" links and the name of the producer/creator. docs/CONTRIBUTING.md#platforms-and-access-notes
No need for `youtube`

**Comment by eshellman** [comment]
Thanks, and welcome to free-programming-books!

**Pull request merged**
