### PR TITLE
Remove unavailable resources from more section

### PR DESCRIPTION
**Pull request by jatin-dua**
## What does this PR do?
Remove resource(s)

### Description
Removed unavailable links (resources) from the more section of the repo. Status: **404 Not Found**

### Why is this valuable (or not)?
This will display only available resources and improve the quality of repo.

### How do we know it's really free?
NA

### For book lists, is it a book? For course lists, is it a course? etc.
NA

## Checklist:
- [x] Read our [contributing guidelines](https://github.com/EbookFoundation/free-programming-books/blob/main/docs/CONTRIBUTING.md).
- [x] [Search](https://ebookfoundation.github.io/free-programming-books-search/) for duplicates.
- [x] Include author(s) and platform where appropriate.
- [x] Put lists in alphabetical order, correct spacing.
- [x] Add needed indications (PDF, access notes, under construction).
- [x] Used an informative name for this pull request.

## Follow-up

- Check the status of GitHub Actions and resolve any reported warnings!

### CODE REVIEW

**Comment by eshellman** [comment]
removing the pt_BR file requires that the link be removed from README; that's in another PR, though. I think closing and opening will make the diff go away

**Comment by jatin-dua** [comment]
> ok that didn't work maybe update from main?

I'll remove it from main then, and will report back.

**Comment by jatin-dua** [comment]
@eshellman I've made the changes and removed it from main index, Can you please review it?

**Comment by eshellman** [comment]
more/free-programming-interactive-tutorials-pt_BR.md is still being deleted even though it already has been. will look more closely in the morning

**Pull request merged**
